### ISSUE TITLE
broadcast功能失效

### ISSUE THREAD

**Issue by ice-b-114** [Tsuk1ko/cq-picsearcher-bot#101]
1. Bug 描述
   如题，其他功能正常，唯独群发功能失效。无论是否加额外指令均失效，稳定复现
2. 截图、日志、配置
   debug模式下的日志截图，可以看到对broadcast命令无回应（已用reload命令确认发送者有管理者权限）
![image](https://user-images.githubusercontent.com/57836568/93002064-9a27f280-f566-11ea-8871-751e4a2513b8.png)
  群列表不为空
![image](https://user-images.githubusercontent.com/57836568/93002245-45857700-f568-11ea-9539-c52a3cec2545.png)

3. 运行环境
   - 系统Windows Server 2019
   - Node 版本v14.1.0
   - go-cqhttp 版本 v0.9.24-fix2 
   - cq-picsearcher-bot 版本 v2.18.0

**Comment by Tsuk1ko** [comment]
已修复
