### ISSUE TITLE
希望支持CQ:record

### ISSUE THREAD

**Issue by SEAFHMC** [Tsuk1ko/cq-picsearcher-bot#102]
希望加的功能：
支持CQ:record
理由：
    想通过语言库功能来发送.amr文件，但多次尝试总是发送出原CQ码。翻阅了CQCode.js时发现没有关于CQ:record的项目。

**Comment by Tsuk1ko** [comment]
`CQCode.js` 与是否支持该 CQ 码无关，只要 go-cqhttp 支持就可以发送（go-cqhttp v0.9.15 起支持）

你需要观察 go-cqhttp 日志来确定无法发送的原因，并检查是否是路径问题，尝试使用绝对路径`file://C:/path/to/amr`来避免不必要的路径坑

**Comment by SEAFHMC** [comment]
好的 谢谢麒麟大佬
