### ISSUE TITLE
管理员组问题

### ISSUE THREAD

**Issue by FoundTheWOUT** [Tsuk1ko/cq-picsearcher-bot#105]
我做了一个 [小修改](https://github.com/FoundTheWOUT/cq-picsearcher-bot/commit/becb35c17d67a61c6689fcc5d16e2bbbfd5e95b2) 让其支持管理员组。
在`test`的时候它一切运作正常（实现了多管理员）。
但在真正部署的时候还是只能一个人，这个人与其在数组中的位置并没有关系。

**Comment by Tsuk1ko** [comment]
pm2 守护的没更新？

```
npm run restart
```

**Comment by FoundTheWOUT** [comment]
确实是pm2的问题,由于我是新建了一个目录然后conle自己的,原进程又没有删除,在新目录下restart还是重启了之前的进程.
后来删除原来的进程再重启就好了
