### ISSUE TITLE
setu 功能中捕获组无效

### ISSUE THREAD

**Issue by EDHY-233** [Tsuk1ko/cq-picsearcher-bot#106]
沙雕群友玩bot的时候会发一些“**整一张****的涩图”，但是貌似没啥作用
直到我刚刚在setu.js中加了一个console.log(keyword)，然后发现无论你发什么给bot它都是false
然后r18参数也一样
本来想修一下的，但是发现自己还是太菜了XD
   - CentOS 8.2
   - Node v12.19.0
   - go-cqhttp 0.9.27
   - cq-picsearcher-bot 2.18.1

**Comment by Tsuk1ko** [comment]
那么 config 中的正则表达式设置你写的是什么

**Comment by EDHY-233** [comment]
"setu": "^阿辽.\*[来來发發给給整][一亿]?[张張个個幅点點丶份]?(?<keyword>.\*?)?的?(?<r18>[Rr]18的?)?[色涩瑟][图圖]|^--setu$"

**Comment by EDHY-233** [comment]
"setu": "^阿辽.\*[来來发發给給整][一亿]?[张張个個幅点點丶份]?(?\<keyword\>.\*?)?的?(?\<r18\>[Rr]18的?)?[色涩瑟][图圖]|^--setu$"

**Comment by Tsuk1ko** [comment]
我试了你这个正则表达式工作正常，你可以用 [regex101](https://regex101.com/) 看看是不是你的发言没有命中

```
还有，markdown 发这种特殊符号较多的内容你可以直接发代码块，就不用一个个转义了
```

**Comment by EDHY-233** [comment]
好的谢谢xd
