### ISSUE TITLE
setu，图片经常不显示，只显示链接

### ISSUE THREAD

**Issue by yy666693** [Tsuk1ko/cq-picsearcher-bot#108]
![11](https://user-images.githubusercontent.com/72908230/97127830-aadaa380-1775-11eb-8936-07f507de606b.png)
就好像如图所示，不是每次都会这样，有时候就会这样发个image，这是什么原因，开太久了吗

**Comment by Tsuk1ko** [comment]
可以试试链接是否可以访问（把`&amp;`替换成`&`），不能的话说明反代服务挂了尝试重启 cq-picsearcher-bot，能的可能是 go-cqhttp 的问题，看看是否有新版本更新再试

**Comment by yy666693** [comment]
全部重启了，还是会有这种情况，也许是网络问题，机器人是部署在阿里云服务器中的，也会不会跟特定色图有关系？
竹竹来张刻晴色图
https://pixiv.net/i/84998219 (p0)
[CQ:image,file=http://127.0.0.1:60233/?key=s303tdl2y0b&amp;url=https://i.pximg.net/img-original/img/2020/10/14/00/00/45/84998219_p0.jpg]

竹竹来张刻晴色图
https://pixiv.net/i/85109066 (p0)
[CQ:image,file=http://127.0.0.1:60233/?key=s303tdl2y0b&amp;url=https://i.pximg.net/img-original/img/2020/10/19/12/50/13/85109066_p0.jpg]



之前旧版用酷Q普通版的时候，机器人会发个不用翻墙能访问图片网址，这个其实挺好的，不用撤回，发R18也没事，点开链接就能看，响应时间也快，能设置吗？

**Comment by Tsuk1ko** [comment]
可以设置 [pximgProxy](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#pximgproxy%E8%AF%B4%E6%98%8E) 来使用网络反代而不是本地反代

目前没有只发链接的设定

**Comment by yy666693** [comment]
设置了，好像是变好了，谢谢！
