### ISSUE TITLE
私聊图片无法发送

### ISSUE THREAD

**Issue by foxwhite25** [Tsuk1ko/cq-picsearcher-bot#109]
1. Bug 描述
目前私聊会无法发送图片，而是发送一堆看似代表图片base64的文字，但是群聊却正常。
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
这是私聊看到的截图
![image](https://user-images.githubusercontent.com/39846845/98785272-4e46dc00-2437-11eb-9d22-68b3b3059917.png)
这是cqhttp的log
https://paste.ubuntu.com/p/jz7RKXFgBs/
3. 运行环境
Win10
go-cqhttp 0.9.30
cq-picsearcher-bot 2.19.0

**Comment by Tsuk1ko** [comment]
希望提供出错的 CQ 码全文（可以存到 txt 里直接拖到评论框中上传），我好排查原因

另外 go-cqhttp 可以设置 `"ignore_invalid_cqcode": true,`，在失败的时候将不会原样发送 CQ 码，防止刷屏

**Comment by foxwhite25** [comment]
[Error.txt](https://github.com/Tsuk1ko/cq-picsearcher-bot/files/5524588/Error.txt)
@Tsuk1ko

**Comment by foxwhite25** [comment]
这个很可能和#110是同一个问题，在更新之前就是那样。

**Comment by Tsuk1ko** [comment]
见 Mrs4s/go-cqhttp#378

有提供修复版本，可以临时先用着

**Comment by foxwhite25** [comment]
解决了
