### ISSUE TITLE
run test可以运行，start不行；成功调用setu功能一次之后会报错WS重连

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#113]
![VBPVHDBC`@~ K1QFBBT U90](https://user-images.githubusercontent.com/66856838/100894393-68844f00-34f7-11eb-9259-a3d3614f96f4.png)

下面这张图是群员成功调用一次setu之后发生的
![)@R9Y__CTM$GDT)RT}WWBNW](https://user-images.githubusercontent.com/66856838/100894342-5acec980-34f7-11eb-8f63-e36b8ea7c255.png)

**Comment by Tsuk1ko** [comment]
1. 将本项目和 go-cqhttp 更新到最新版本，别漏了更新依赖的命令
2. 重启 PC
3. 启动 go-cqhttp。然后进入项目直接 `npm start`
4. 如果仍无法正常启动，查看 `logs` 文件夹内的错误日志

**Comment by Miuzarte** [comment]
重启之后可以npm start了，感谢；
调用setu之后go-cq上还会报错：处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
go-cq和bot都是最新的amd64
![B{ ZY}%(R@UUF@R5%QZ5NC](https://user-images.githubusercontent.com/66856838/100963844-45db5000-3562-11eb-9228-52083b2f29ba.png)

**Comment by Miuzarte** [comment]
![image](https://user-images.githubusercontent.com/66856838/100963985-95ba1700-3562-11eb-961c-6f10e10681ca.png)
这个是npm的log

**Comment by Tsuk1ko** [comment]
> 重启之后可以npm start了，感谢；
> 调用setu之后go-cq上还会报错：处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
> go-cq和bot都是最新的amd64
> ![B{ ZY}%(R@UUF@R5%QZ5NC](https://user-images.githubusercontent.com/66856838/100963844-45db5000-3562-11eb-9228-52083b2f29ba.png)

感觉是 go-cqhttp 的问题，确定使用的版本是 [v0.9.33-fix1](https://github.com/Mrs4s/go-cqhttp/releases/tag/v0.9.33-fix1) 么，我看说明中有“修复发送消息时可能导致崩溃的错误”

另外建议暂时先用 [v0.9.32](https://github.com/Mrs4s/go-cqhttp/releases/tag/v0.9.32)，v0.9.33 引入了一个 CQ 解析 bug 会对机器人的搜图功能产生影响，我已经反馈给作者了，他也修复了，但是还没发新 release

**Comment by Miuzarte** [comment]
好的

**Comment by Magic-Xin** [comment]
go-cqhttp 更新至 v0.9.34 后问题依旧
