### ISSUE TITLE
开启搜图指令不可用

### ISSUE THREAD

**Issue by yingyingmaster** [Tsuk1ko/cq-picsearcher-bot#116]
1. Bug 描述
如题，其他功能正常，唯独搜图指令失效。群聊中以 “机器人名字+搜图” 的指令无响应，群聊中 “@机器人+图片” 的指令形式搜图可用
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
日志：
[log.txt](https://github.com/Tsuk1ko/cq-picsearcher-bot/files/5684866/log.txt)
配置：
![QQ截图20201213224203](https://user-images.githubusercontent.com/69996161/102015841-e3235900-3d98-11eb-8d36-4f8c7353f62a.png)

3. 运行环境
   - Ubuntu 18.04.5 LTS
   - node.js v14.15.0
   - go-cqhttp-v0.9.34-fix1-linux-amd64
   - cq-picsearcher-bot 版本：2.21.0

**Comment by Tsuk1ko** [comment]
感谢发现问题，已修复
