### ISSUE TITLE
在linux上部署一直报错require stack和code ELIFECYCLE

### ISSUE THREAD

**Issue by CabbCat** [Tsuk1ko/cq-picsearcher-bot#117]
前几天在win上部署的时候没什么问题，今天在linux上试的时候npm run test报这两个错，按网上说的清cache和module也没用QAQ
还有一个问题，用最新版js（不确定，14.15.1和10.16.0好像都有）直接npm i的话会有一个canvas2.6.1文件缺失，后面我是加了--unsafe-perm --allow-root才完整下载下来

https://imgchr.com/i/rm49fA

https://imgchr.com/i/rm4PSI

**Comment by Tsuk1ko** [comment]
1. 建议学一下 markdown
2. 建议看一下 wiki - 常见问题 - tips - 1
