### ISSUE TITLE
增加通过私聊机器人增加、删除语言库 功能

### ISSUE THREAD

**Issue by Quan666** [Tsuk1ko/cq-picsearcher-bot#118]
请说明：

1. 增加通过私聊机器人增加、删除语言库 功能
2. 每次添加回复还要打开服务器去添加太麻烦

提交 issue 前请删除这句话及上面的说明内容

**Comment by Tsuk1ko** [comment]
目前没有改动打算

1. 参数比较多，使用命令删除和编辑会很麻烦，相当于要 list 一下然后根据 id 再删改，参考 rmd 指令，我着实不想再放一个这样的操作进去
2. 由于使用了 jsonc 现在没法直接动配置文件了需要新开一个配置保存，会增加维护成本
