### ISSUE TITLE
可以加个新能吗

### ISSUE THREAD

**Issue by vanish1008** [Tsuk1ko/cq-picsearcher-bot#120]
1. 搜番指令anime自定义，或者回复哪个番剧几分几秒
2. 手机搜番不方便，满足水友们的热情

**Comment by Tsuk1ko** [comment]
1. 不考虑增加图库关键字的自定义能力
1. 提供两个建议
   1. 如果搜番使用的最频繁，可以修改 `bot.saucenaoDefaultDB` 使其成为默认库
   1. 使用回复的形式触发搜图，见[日常食用-群组](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E5%A6%82%E4%BD%95%E9%A3%9F%E7%94%A8#%E6%97%A5%E5%B8%B8%E9%A3%9F%E7%94%A8)

**Comment by vanish666** [comment]
那好吧，我想修改源码，感觉难度有点大，实在不行就算了
