### ISSUE TITLE
搜图返回的短链无法访问

### ISSUE THREAD

**Issue by YipSzeho** [Tsuk1ko/cq-picsearcher-bot#124]
已是最新 cq-picsearcher-bot 和 go-cqhttp
搭配 ELF_RSS 订阅插件
若SauceNAO搜图返回的链接是推特的，会被转换成短链，且短链无法访问，有没有办法不转换成短链
![Image](https://raw.githubusercontent.com/YipSzeho/gittalk/main/QQ%E6%88%AA%E5%9B%BE20201231124115.png)

**Comment by Tsuk1ko** [comment]
不是推特，这个转短链最初是为了防止 danbooru 和 yandere 等红链在手Q上打不开的，用的 is.gd 短链，以前没事，可能现在被墙了

现在手Q已经可以复制部分消息了，确实也不需要短链接了，过会我把它去掉

**Comment by YipSzeho** [comment]
okkk辛苦大佬了

**Comment by Tsuk1ko** [comment]
已更新
