### ISSUE TITLE
bot会重复发送同一tag下的相同涩图

### ISSUE THREAD

**Issue by 530647726** [Tsuk1ko/cq-picsearcher-bot#127]
1.多次要求相同tag的涩图时，会发送相同的涩图。
2.希望能做一个规避重复的功能。

**Comment by Tsuk1ko** [comment]
1. 这个功能依赖我个人的图库运作，一般是因为该 tag 图比较少甚至就只有这一张，这点没有办法
2. 在机器人层面重复请求来规避不合理，在服务端规避重复成本过高，因此没有实现此功能的计划

**Comment by 530647726** [comment]
啊，这样啊，我以为时P站现搜的呢。那没事啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "神代綺凜"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 上午10:48
收件人: "Tsuk1ko/cq-picsearcher-bot"<cq-picsearcher-bot@noreply.github.com&gt;; 
抄送: "残香覆睫"<530647726@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tsuk1ko/cq-picsearcher-bot] bot会重复发送同一tag下的相同涩图 (#127)





  
这个功能依赖我个人的图库运作，一般是因为该 tag 图比较少甚至就只有这一张，这点没有办法
 
在机器人层面重复请求来规避不合理，在服务端规避重复成本过高，因此没有实现此功能的计划
