### ISSUE TITLE
npm run log里出现了报错 ，[error] check update

### ISSUE THREAD

**Issue by 0769559** [Tsuk1ko/cq-picsearcher-bot#128]
root@v163494:~/cq-picsearcher-bot# npm run log

> cq-picsearcher-bot@2.21.6 log /root/cq-picsearcher-bot
> pm2 logs CQPF

[TAILING] Tailing last 15 lines for [CQPF] process (change the value with --lines option)
/root/cq-picsearcher-bot/logs/normal-0.log last 15 lines:
0|CQPF     | 1/13/2021, 12:00:01 AM 连接失败[/event]#1104
0|CQPF     | 1/13/2021, 12:00:01 AM 连接失败[/api]#1104
0|CQPF     | 1/13/2021, 12:00:06 AM 连接中[/event]#1105
0|CQPF     | 1/13/2021, 12:00:06 AM 连接失败[/event]#1105
0|CQPF     | 1/13/2021, 12:00:06 AM 连接中[/api]#1105
0|CQPF     | 1/13/2021, 12:00:06 AM 连接失败[/api]#1105
0|CQPF     | 1/13/2021, 12:00:11 AM 连接中[/event]#1106
0|CQPF     | 1/13/2021, 12:00:11 AM 连接失败[/event]#1106
0|CQPF     | 1/13/2021, 12:00:11 AM 连接中[/api]#1106
0|CQPF     | 1/13/2021, 12:00:11 AM 连接失败[/api]#1106
0|CQPF     | 1/13/2021, 12:04:43 AM 配置已加载
0|CQPF     | 1/13/2021, 12:04:54 AM 连接中[/event]#1
0|CQPF     | 1/13/2021, 12:04:54 AM 连接中[/api]#1
0|CQPF     | 1/13/2021, 12:04:54 AM 连接成功[/event]#1
0|CQPF     | 1/13/2021, 12:04:54 AM 连接成功[/api]#1

/root/cq-picsearcher-bot/logs/error-0.log last 15 lines:
0|CQPF     | error: unknown option `sort=v:refname'
0|CQPF     | usage: git ls-remote [--heads] [--tags] [--refs] [--upload-pack=<exec>]
0|CQPF     |                      [-q | --quiet] [--exit-code] [--get-url]
0|CQPF     |                      [--symref] [<repository> [<refs>...]]
0|CQPF     | 
0|CQPF     |     -q, --quiet           do not print remote URL
0|CQPF     |     --upload-pack <exec>  path of git-upload-pack on the remote host
0|CQPF     |     -t, --tags            limit to tags
0|CQPF     |     -h, --heads           limit to heads
0|CQPF     |     --refs                do not show peeled tags
0|CQPF     |     --get-url             take url.<base>.insteadOf into account
0|CQPF     |     --exit-code           exit with exit code 2 if no matching refs are found
0|CQPF     |     --symref              show underlying ref in addition to the object pointed by it
0|CQPF     | 
0|CQPF     | 1/13/2021, 12:05:54 AM [error] check update

刚开始启动的时候就算有这样的报错 机器人还是能运行，但是不定时机器人就出问题，也不知道什么原因 总之先求助一下我遇到的这个错误。算下来用了有大半年了，以前没出现这样的报错。大概在1、2个月前才发现有这种情况。

3. 运行环境
   - 系统，Debian9
   - node.js 版本 v10.22.0
   - go-cqhttp 版本  go-cqhttp-v0.9.25-linux-amd64.tar ，也试过替换成v0.9.32 问题依旧
   - cq-picsearcher-bot 版本  2.21.6

**Comment by Tsuk1ko** [comment]
@0769559 尝试更新一下 git 版本

**Comment by Tsuk1ko** [comment]
需要 2.18.0 以上的 git

**Comment by 0769559** [comment]
看了下我是2.11的git看来的确是版本问题。谢谢~
