### ISSUE TITLE
【公告】saucenao 搜索失败问题

### ISSUE THREAD

**Issue by Tsuk1ko** [Tsuk1ko/cq-picsearcher-bot#130]
貌似目前 saucenao 要使用 json api 必须使用 api key，只要去其官网注册一个帐号就可以获得 api key，无需付费，写入 `saucenaoApiKey` 配置项然后更新项目到最新版并重启即可

**Comment by YD-Cat** [comment]
好家伙，刚才发现搜不了图，加个打印一看403了

**Comment by Tsuk1ko** [comment]
@YD-Cat 是啊，好像是今天刚加的限制

**Comment by dragonxash** [comment]
跑npm i 的时候卡在Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169688:5: note: here 这里了 1cpu 1g内存

**Comment by kirastar63p** [comment]
> 跑npm i 的时候卡在Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169688:5: note: here 这里了 1cpu 1g内存

试下用yran，npm i -g yarn->yarn install

**Comment by dragonxash** [comment]
> > 跑npm i 的时候卡在Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169688:5: note: here 这里了 1cpu 1g内存
> 
> 试下用yran，npm i -g yarn->yarn install

已解决谢谢大佬

**Comment by Orca-web** [comment]
版本 ：go-cqhttp-v0.9.40-fix2 和cq-picsearcher-bot v2.22.3
操作系统：windows 10
问题描述：go-cqhttp-v0.9.40-fix2正常运行，`npm run test ` 测试bot，QQ聊天界面显机器人已上线，用管理者QQ发送图片，回复 

> 搜索失败惹 QAQ
> 有可能是服务器网络爆炸，请重试一次，或尝试二次截图后发送
> 
> ascii2d 搜索失败

配置文件是config.jsonc，内容和config.default.jsonc几乎一样，修改了"admin"和“saucenaoApiKey”字段

saucenaoApiKey 的获取途径 ：https://saucenao.com/user.php?page=search-api

cmd 命令窗口见下：

```
2021-2-28 12:59:37 配置已加载
2021-2-28 12:59:40 连接中[/event]#1
2021-2-28 12:59:40 连接中[/api]#1
2021-2-28 12:59:40 连接成功[/event]#1
2021-2-28 12:59:40 连接成功[/api]#1
fatal: No remote configured to list refs from.
2021-2-28 13:00:40 [error] check update
2021-2-28 13:00:57 [error] saucenao[0][request]
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27)
{
  "message": "read ECONNRESET",
  "code": "ECONNRESET",
  "config": {}
}
2021-2-28 13:00:57 [error] saucenao[0][request]
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27)
{
  "message": "read ECONNRESET",
  "code": "ECONNRESET",
  "config": {}
}
2021-2-28 13:00:57 [error] saucenao[0][request]
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27)
{
  "message": "read ECONNRESET",
  "code": "ECONNRESET",
  "config": {}
}
```

**Comment by Tsuk1ko** [comment]
@Orca-web 连接重置一般是机器网络问题，国内机器建议挂代理，配置 `bot.proxy`

**Comment by Orca-web** [comment]
@Tsuk1ko 再次为作者项目点赞，简直秒回。

挂完代理后，已成功，谢谢。
![image](https://user-images.githubusercontent.com/59247295/109408641-4ac76880-79c6-11eb-9812-05419b1b9532.png)

咨询一下，可以把这个bot放到QQ群里，供群员使用嘛？先行感谢

**Comment by Tsuk1ko** [comment]
@Orca-web 群内可以使用，见 wiki - 如何食用

**Comment by zhenfeifei** [comment]
额，目前saucenao正常但是ascii2d出错是啥原因
我是完全不懂计算机的壬
2021/4/18 下午6:15:01 [error] nhentai
Error: connect ETIMEDOUT 78.16.49.15:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
{
  "message": "connect ETIMEDOUT 78.16.49.15:443",
  "code": "ETIMEDOUT",
  "config": {}
}
2021/4/18 下午6:15:03 [error] ascii2d
Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
{
  "message": "write ECONNRESET",
  "code": "ECONNRESET",
  "config": {}
}
2021/4/18 下午6:21:11 [error] ascii2d
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
{
  "message": "read ECONNRESET",
  "code": "ECONNRESET",
  "config": {}
}
@Tsuk1ko
