### ISSUE TITLE
番剧截图搜索功能错误

### ISSUE THREAD

**Issue by gzzhongqi** [Tsuk1ko/cq-picsearcher-bot#133]
目前trace.moe是无法正常使用的，即使config.jsonc中确实写了trace.moe的网址，在log中还是会报错，而机器人回复也不会包含这个结果。稍微调查了一下，发现是现在whatanime.js写得有一个小bug，第18行目前为
`const tokens = global.config.whatanimeTokens;`
实际上config.jsonc采用的是whatanimeToken，所以里面只要修改成
`const tokens = global.config.whatanimeToken;`
就好了

**Comment by Tsuk1ko** [comment]
确实，感谢报告这个错误
