### ISSUE TITLE
搜图相关功能需求，以及一个文字转语音功能

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#136]
①在搜索过程中如果获取到第二张同样(一样的.image)的图片后似乎并不会调用缓存 而是又搜索了一遍，希望能改进（做了②之后好像有没有也差不多）

②在bot获取到图片后如果5s(可自定义)内未发送结果，则回复一条“在搜了在搜了，再等等再等等”(可自定义)，避免因yande.re、danbooru之类的搜索慢而导致用户多次发送图片多次搜索造成刷屏
以及在自动退出搜图模式之后如果过程中没有收到一图片的话，回复另外的一条消息 用于报告这次搜图过程没有收到任何一张图
--说明一下情况，我几乎只让bot在群里用，关掉了临时会话，要么就加好友用，有时候群里用户发的图片被腾讯吃了，如果没人提醒这用户就懵了
![-6322060bb71bb395](https://user-images.githubusercontent.com/66856838/106014968-a0d18500-6083-11eb-8219-a7d9d3b1780a.png)

③如果能实现的话，用合并转发来发送结果（最好是能包括进自动a2d搜索的结果）*也许能避免风控之类的导致a2d要么少颜色要么少特征（毕竟要风控也是一起没）

最后再求个小功能，文字转语音（用QQ的API），做成跟setu一样正则匹配再带个冷却时间

工程量好像很大，没法做的话当废话就好（

**Comment by Tsuk1ko** [comment]
1. 搜图缓存的功能是确实有发挥作用的，但仍会出现你虽然发的是同一张但是在 cq 里拿到的文件名不同，这种情况无能为力
2. 可以，会安排
3. 可以，会安排
4. 对我来说意义不大，且不是必要功能，懒得安排
