### ISSUE TITLE
群聊中的搜图结果无法正确发送为回复消息

### ISSUE THREAD

**Issue by Lancercmd** [Tsuk1ko/cq-picsearcher-bot#137]
## Bug 描述
- 搜图时无法正常发送回复消息
## 截图、日志、配置（issue 内上传图片或文件可直接粘贴）

![image](https://user-images.githubusercontent.com/59906398/106237298-77f2f080-6239-11eb-8208-53e9573accfe.png)

## 运行环境
   - Windows 10 20H2
   - node v14.15.3 (LTS)
   - go-cqhttp 0.9.39
   - cq-picsearcher-bot 2.22.0

**Comment by Tsuk1ko** [comment]
这不是我这边的问题，请检查 go-cqhttp 是否有错误信息，以及 go-cqhttp 必须开启数据库，详见其配置[文档](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/config.md#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF)的 `enable_db`

**Comment by Lancercmd** [comment]
啊这，原来如此，那没事了
