### ISSUE TITLE
setu无法发送

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#139]
log如下：
[2021-02-06 19:13:31] [WARNING]: 转换CQ码 [CQ:image,file=http://127.0.0.1:60233/?key=cjt4wyekhfl&amp;url=https://i.pximg.net/img-master/img/2018/10/28/15/21/09/71385704_p1_master1200.jpg] 时出现错误: Get "http://127.0.0.1:60233/?key=cjt4wyekhfl&url=https://i.pximg.net/img-master/img/2018/10/28/15/21/09/71385704_p1_master1200.jpg": EOF 将忽略. 
[2021-02-06 19:13:31] [WARNING]: 好友消息发送失败: 消息为空. 

npm run test没有报错，只有连接成功的info

我尝试访问https://i.pximg.net/img-master/img/2018/10/28/15/21/09/71385704_p1_master1200.jpg返回403

config如下：
    // setu 相关功能，部分配置的详细说明请查看“wiki-附加功能-setu”以了解更多
    "setu": {
      // 是否启用
      "enable": true,
      // APIKEY
      "apikey": "马赛克",
      // 反和谐方式（0：关闭，1：轻微修改，2：旋转）
      "antiShielding": 2,
      // 是否允许私聊使用
      "allowPM": true,
      // P站图本地反代端口，若端口冲突请修改此项
      "pximgServerPort": 60233,
      // 设置使用的P站本地反代服务地址
      "usePximgAddr": "",
      // 设置使用的P站在线反代服务地址
      "pximgProxy": "",
      // 是否发送 master1200 大小的图片，以节省流量或加快发送速度，关闭时将发送原图
      "size1200": true,
      // 发送后这么多秒自动撤回（0 则不撤回，-1 为发送闪照）
      "deleteTime": 10,
      // 群内使用冷却时间（秒），每名用户独立，0 则无冷却，私聊无 cd
      "cd": 6,
      // 每名用户每日次数限制
      "limit": 100,
      // 群组白名单
      "whiteGroup": [马赛克],
      // 仅允许白名单群使用（与上面的私聊使用是独立的）
      "whiteOnly": true,
      // 白名单群组的群内使用冷却时间（秒），每名用户独立，0 则无冷却
      "whiteCd": 6,
      // 白名单群组内发送后这么多秒自动撤回（0 则不撤回，-1 为发送闪照）
      "whiteDeleteTime": 10,
      // 只允许在白名单群组中发送 r18 setu
      "r18OnlyInWhite": false
    },

环境：
amd64 linux
nodejs：10.21.0
go-cqhttp：0.9.39 (amd64)
cq-picsearcher-bot：2.22.0

**Comment by Miuzarte** [comment]
不会markdown（（

**Comment by Tsuk1ko** [comment]
一般是机器网络问题，如果是国内机器建议上代理

直接访问是肯定 403 的因为P站有防盗链，机器人内置的本地反代会解决防盗链问题

**Comment by Miuzarte** [comment]
原来config里能填代理的啊，才看到，建议写进wiki（（（

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/107956245-d827b780-6fd9-11eb-8a06-0d226c284a6c.png)

我以为一般人都会先看一遍 config

![image](https://user-images.githubusercontent.com/24877906/107956310-f1c8ff00-6fd9-11eb-8595-9311d0be9ea9.png)
