### ISSUE TITLE
【奇怪的问题】机器人账号和admin账号引发的一点问题

### ISSUE THREAD

**Issue by KatsumiAya** [Tsuk1ko/cq-picsearcher-bot#152]
首先先说结论：某些逻辑可能需要处理一下？

今天突发奇想，尝试了把admin设置为机器人同账号

然后出现了这种情况
![16D442DF-E730-4500-8950-47664E4F5E45.jpeg](https://i.loli.net/2021/03/21/Diaw3U69pMm4NKS.jpg)

于是尝试对着自己发图片来搜，果不其然也是对着自己一番轰炸，这里就不放图了

至于群组里的情况，我估计会是一样的

虽然我不知道为什么我会这么无聊要这么整（

如果可能的话是否可以进行一下优化呢？虽然不是必要的

**Comment by Tsuk1ko** [comment]
🤔确实是有这个问题，机器人上线的时候会对 admin 私聊发送已上线的信息，导致自己会收到自己的私聊信息，于是就会无限对自己发送这个默认回复消息
