### ISSUE TITLE
通过api放大图片，获取更高清晰度的图片

### ISSUE THREAD

**Issue by hbksinukse** [Tsuk1ko/cq-picsearcher-bot#158]
https://bigjpg.com/
可以通过api使用最新人工智能深度学习技术——深度卷积神经网络。它会将噪点和锯齿的部分进行补充，实现图片的无损放大
我想实现和搜图api一样的做法来进行放大图片

**Comment by Tsuk1ko** [comment]
不建议，QQ 会压缩图片，要获得高质量的图自行操作更好

**Comment by hbksinukse** [comment]
哦哦我懂了
