### ISSUE TITLE
语言库（自动回复）无法发送合并消息[CQ:node]

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#168]
看了看js，似乎是没法用语言库去发，想用来写个help的回复

**Comment by Tsuk1ko** [comment]
`[CQ:node]` 本来就无法以字符串形式发送

https://docs.go-cqhttp.org/cqcode/#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF%E8%8A%82%E7%82%B9
