### ISSUE TITLE
搜番剧没有返回预览视频

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#172]
1. Bug 描述
没有返回预览视频,私聊和群聊
2. 截图、日志、配置
![image](https://user-images.githubusercontent.com/66856838/117161650-abbf5280-adf4-11eb-9671-f37df7ea900e.png)
![image](https://user-images.githubusercontent.com/66856838/117161876-da3d2d80-adf4-11eb-94d5-04419577c680.png)
![image](https://user-images.githubusercontent.com/66856838/117162518-69e2dc00-adf5-11eb-9514-fa4f8a11acef.png)

3. 运行环境
   - linux AMD64
   - node -v14.16.1
   - gocq -v1.0.0 beta3
   - cq-picsearcher-bot -v2.26.0

**Comment by Tsuk1ko** [comment]
你要看 go-cqhttp 日志是不是发送失败了，这个比较迷，有时候会出现，和本项目无关，不知道是不是网络问题

**Comment by Miuzarte** [comment]
> 你要看 go-cqhttp 日志是不是发送失败了，这个比较迷，有时候会出现，和本项目无关，不知道是不是网络问题

![IMG_20210506_003329.jpg](https://user-images.githubusercontent.com/66856838/117176767-db8b3d80-ad95-11eb-82a2-f19c3e814671.jpg)
![Screenshot_2021-05-06-00-36-54-901_com.termux.jpg](https://user-images.githubusercontent.com/66856838/117177199-5f452a00-ad96-11eb-923b-1b0b174ce627.jpg)
视频链接是anidb.net的吗，我这边curl不动

**Comment by Tsuk1ko** [comment]
不是，是 media.trace.moe 的

你可以开 debug 模式来看具体 url，在 `[CQ:video]` 内，把 `&amp;` 替换成 `&`

**Comment by Miuzarte** [comment]
> 不是，是 media.trace.moe 的
> 
> 你可以开 `bot.debug` 来看具体 url，在 `[CQ:video]` 内，把 `&amp;` 替换成 `&`

访问似乎是没问题，能ping也能curl到
![IMG_20210506_010732.jpg](https://user-images.githubusercontent.com/66856838/117181238-a1706a80-ad9a-11eb-8fca-1509ff4a12e3.jpg)
![IMG_20210506_010815.jpg](https://user-images.githubusercontent.com/66856838/117181296-b0571d00-ad9a-11eb-99d0-f608dedd07a5.jpg)


wget和curl视频链接一直报'syntax error near unexpected token `(''

**Comment by Tsuk1ko** [comment]
curl 的时候链接要用双引号包裹……

总之这个发送问题只能看造化了，先用一段时间再说

**Comment by Miuzarte** [comment]
> curl 的时候链接要用双引号包裹……
> 
> 总之这个发送问题只能看造化了，先用一段时间再说

wget到了
![Screenshot_2021-05-06-01-16-41-867_com.termux.jpg](https://user-images.githubusercontent.com/66856838/117182319-cf09e380-ad9b-11eb-8324-1783d5556f5d.jpg)

**Comment by Miuzarte** [comment]
> curl 的时候链接要用双引号包裹……
> 
> 总之这个发送问题只能看造化了，先用一段时间再说

[https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042](url)gocq的一个closed issue中有人提到用手机QQ把视频以`视频`形式发出去(非`群文件`)之后,gocq那边无论是在线链接还是本地文件都可以发送成功,我自己也复现了
所以你用的gocq什么版本  能成功收到预览视频吗

**Comment by Miuzarte** [comment]
服务器安装了ffmpeg之后gocq似乎就不会报错70了，我中午再试试

**Comment by Tsuk1ko** [comment]
噢噢，原来是因为缺少 ffmpeg

**Comment by Tsuk1ko** [comment]
那我尝试直接在项目中带上 ffmpeg 吧 #173

**Comment by Miuzarte** [comment]
> 那我尝试直接在项目中带上 ffmpeg 吧 #173

安装了ffmpeg之后gocq会去调用，确实没再失败过了

**Comment by Miuzarte** [comment]
> 那我尝试直接在项目中带上 ffmpeg 吧 #173

[gocqdoc](https://docs.go-cqhttp.org/cqcode/#%E7%9F%AD%E8%A7%86%E9%A2%91)

**Comment by Tsuk1ko** [comment]
以“摸了”告终

https://github.com/Tsuk1ko/cq-picsearcher-bot/issues/173#issuecomment-833291370

**Comment by Miuzarte** [comment]
> 以“摸了”告终
> 
> https://github.com/Tsuk1ko/cq-picsearcher-bot/issues/173#issuecomment-833291370

项目是就改了个默认false吗，安装ffmpeg在wiki部署流程里写就好了吧

**Comment by Tsuk1ko** [comment]
会在里面提一嘴
