### ISSUE TITLE
[feat] Change format with mp4 to reduce error

### ISSUE THREAD

**Issue by sam01101** [Tsuk1ko/cq-picsearcher-bot#173]
> https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-832884166

请说明：

1. 加什么功能: 使用ffmpeg手动转换出成mp4
2. 理由 减少gocq的70错误问题

https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/61ab71c8f0f9f168d744e035dd5093633b3fa343/src/whatanime.js#L95-L99

这里，在push之前先下载视频下来然后转换成`mp4`会比较好，但只能缓解情况

**Comment by Tsuk1ko** [comment]
有些细节想咨询一下

我查了下 go-cqhttp 源码，目前我只看到这段有用到 ffmpeg 转换

https://github.com/Mrs4s/go-cqhttp/blob/d8a373cfa4cc6a99b6f9f5ed5e0bb763c319d07c/coolq/cqcode.go#L948-L994

它的逻辑貌似是判断文件头部字节，如果不是 mp4 就转换

而我实际将我要发送的视频文件下载下来，发现他确实是 mp4 格式的，这个判断也是通过的

https://user-images.githubusercontent.com/24877906/117246995-1b265800-ae70-11eb-97f1-cce2c62ca5d6.mp4

![image](https://user-images.githubusercontent.com/24877906/117246699-a94e0e80-ae6f-11eb-8600-e5b15428d31a.png)

<img src="https://user-images.githubusercontent.com/24877906/117246725-b408a380-ae6f-11eb-8c5e-12270effc46b.png" width="400" />

就……感觉很奇怪，还是说如果要直接发的话视频参数也有严格要求，转换逻辑在其它包里面

**Comment by sam01101** [comment]
不知道，_总之就是非常_奇怪

**Comment by sam01101** [comment]
本人为了~滥用~不对，~白嫖~研究短视频的极限在哪儿，曾经尝试过以1Frame的黑画面发送，而且成功
最终大小1700b左右

使用了ffmpeg来生成


总之，先用ffmpeg的-c copy转换一下把

**Comment by Tsuk1ko** [comment]
测试了
```bash
ffmpeg -i test1.mp4 -c copy test.mp4
```
和
```bash
ffmpeg -i test1.mp4 -c:v h264 -c:a mp3 test.mp4
```
生成的 `test.mp4` 都无法直接发送

**Comment by sam01101** [comment]
首先检查是不是漏了什么，正常来说是可以发的

在 2021年5月6日週四 下午3:06，神代綺凛 ***@***.***> 寫道：

**Comment by Tsuk1ko** [comment]
思考，这样弄下去还是有点麻烦，相当于我这边需要做下载、临时文件管理、转换等，这些本来是 go-cqhttp 就已经做好了的，我再为这个不算是很重要的功能重复造轮子挺划不来的

还是引导用户安装 ffmpeg 算了

![image](https://user-images.githubusercontent.com/24877906/117257094-14064680-ae7e-11eb-993a-c959bf6285b8.png)

**Comment by sam01101** [comment]
好，非常好

在 2021年5月6日週四 下午3:18，神代綺凛 ***@***.***> 寫道：

**Comment by Tsuk1ko** [comment]
@sam01101 @Miuzarte 🤔我好像懂了，应该是发送短视频必须要提供 cover，否则 go-cqhttp 会使用 ffmpeg 来截取一帧作为 cover，所以即使发的就是 mp4 也依然会用到 ffmpeg

我原来以为 cover 是可选参数（因为 go-cqhttp 没有报错），现在提供了 cover 以后实测没 ffmpeg 也可以发送

**Comment by Miuzarte** [comment]
> @sam01101 @Miuzarte 🤔我好像懂了，应该是发送短视频必须要提供 cover，否则 go-cqhttp 会使用 ffmpeg 来截取一帧作为 cover，所以即使发的就是 mp4 也依然会用到 ffmpeg
> 
> 我原来以为 cover 是可选参数（因为 go-cqhttp 没有报错），现在提供了 cover 以后实测没 ffmpeg 也可以发送

🌿我刚刚想试一下能不能自定义封面 然后被手机QQ的自动播放背刺，手上有电脑的试试能不能这么玩

**Comment by sam01101** [comment]
> @sam01101 @Miuzarte 🤔我好像懂了，应该是发送短视频必须要提供 cover，否则 go-cqhttp 会使用 ffmpeg 来截取一帧作为 cover，所以即使发的就是 mp4 也依然会用到 ffmpeg
> 
> 我原来以为 cover 是可选参数（因为 go-cqhttp 没有报错），现在提供了 cover 以后实测没 ffmpeg 也可以发送

？那么如果里面不是视频也可以发送吗？

**Comment by Tsuk1ko** [comment]
> > @sam01101 @Miuzarte 🤔我好像懂了，应该是发送短视频必须要提供 cover，否则 go-cqhttp 会使用 ffmpeg 来截取一帧作为 cover，所以即使发的就是 mp4 也依然会用到 ffmpeg
> > 我原来以为 cover 是可选参数（因为 go-cqhttp 没有报错），现在提供了 cover 以后实测没 ffmpeg 也可以发送
> 
> ？那么如果里面不是视频也可以发送吗？

file 如果不是 mp4 格式 go-cqhttp 会自动调用 ffmpeg 转换，转换不了大概会报错吧🤔

**Comment by sam01101** [comment]
> > > @sam01101 @Miuzarte 🤔我好像懂了，应该是发送短视频必须要提供 cover，否则 go-cqhttp 会使用 ffmpeg 来截取一帧作为 cover，所以即使发的就是 mp4 也依然会用到 ffmpeg
> > > 我原来以为 cover 是可选参数（因为 go-cqhttp 没有报错），现在提供了 cover 以后实测没 ffmpeg 也可以发送
> > 
> > 
> > ？那么如果里面不是视频也可以发送吗？
> 
> file 如果不是 mp4 格式 go-cqhttp 会自动调用 ffmpeg 转换，转换不了大概会报错吧🤔

我再测试好了, 如果狠到检测格式就算了
