### ISSUE TITLE
涩图time!

### ISSUE THREAD

**Issue by Rewrite0** [Tsuk1ko/cq-picsearcher-bot#174]
如题,能否增加一个指定时间发送涩图的功能(涩图time!),感觉很有意思,也能增加Bot存在感.

**Comment by Tsuk1ko** [comment]
现在可以使用[定时提醒](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#setu-1)功能自动发 setu

**Comment by Rewrite0** [comment]
好耶！
