### ISSUE TITLE
請問定時提醒可以發送音視頻嗎？

### ISSUE THREAD

**Issue by Annabel0530** [Tsuk1ko/cq-picsearcher-bot#178]

**Comment by aimiku** [comment]
喂！三点几嚟！喂！三点几嚟！喂！三点几嚟！喂！三点几嚟！喂！三点几嚟！

**Comment by Annabel0530** [comment]
😂我確實是想整這個

**Comment by Tsuk1ko** [comment]
目前只能通过随便加一个提醒，然后手动修改 `data/rmd.json`，正常按[CQ码](https://docs.go-cqhttp.org/cqcode/)来写，再发送 `--reload` 重载配置即可

后续我改进下来支持直接按原文添加，大概像这样

```
--time=xxx --origin --rmd=[CQ:record,file=xxx]
```

**Comment by Annabel0530** [comment]
原來是這樣  非常感謝
