### ISSUE TITLE
Pixiv本地反代服务的监听地址设置有误

### ISSUE THREAD

**Issue by hecheng337** [Tsuk1ko/cq-picsearcher-bot#181]
我的QQ机器人平时是运行在docker里的。因为各插件和后端都运行在独立的容器中，所以这个反代服务必须监听在非本机地址。
前几天更新后之后，我发现bot出现了**无法私聊发出色图**的情况，今天阅读源码之后发现了问题所在

![Screenshot_20210519_130948_com.github.android.png](https://user-images.githubusercontent.com/57560866/118760142-dc979100-b8a4-11eb-88f5-59c0a327db9d.png)
如图，**config.jsonc**里设置反代服务监听的配置项叫“**pximgServerHost**”
![Screenshot_20210519_131026_com.github.android_edit_600844739153630.jpg](https://user-images.githubusercontent.com/57560866/118760253-123c7a00-b8a5-11eb-979d-8c6c78b9f629.jpg)
而在**src/plugin/pximg.js**中调用这个配置时，名称确变成了“**pximgServerAddr**”，这导致bot无法读取正确配置而使用了**默认的127.0.0.1**，mirai所在的容器就没法访问cq-picsearcher的本地反代服务了。

经过测试，在config.jsonc中添加" **'pximgServerAddr': '0.0.0.0'** "之后bot功能恢复正常。

**Comment by Tsuk1ko** [comment]
确实，是我粗心写错了……本来代码中应该为 `pximgServerHost`

**Comment by hecheng337** [comment]
> 确实，是我粗心写错了……本来代码中应该为 `pximgServerHost`

哈哈哈，你好快呀😂那没事我就关闭issue了

**Comment by Tsuk1ko** [comment]
稍后我会更新个新版本

**Comment by Tsuk1ko** [comment]
更新了
