### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by xipesoy** [Tsuk1ko/cq-picsearcher-bot#186]
涩图图片也跟着链接一起发出来
r18图片发链接 私发图片

**Comment by Tsuk1ko** [comment]
图片不跟链接一起发是因为图片有可能被屏蔽，这样整条消息包括链接都没了

第二个功能已经有了啊

**Comment by xipesoy** [comment]
涩图 链接和图片分开两条发的功能能整么owo

**Comment by Tsuk1ko** [comment]
也就是加多一个设置项来控制原图链接是跟 pixiv 链接还是跟图片么

**Comment by xipesoy** [comment]
一个涩图 分开两条回复 一条原p链接+镜像链接  一条只有图片

**Comment by xipesoy** [comment]
我收到涩图 只有链接和镜像地址没有图片aqa

**Comment by Tsuk1ko** [comment]
那就是发图片出了问题，如果你网络直连 i.pximg.net 不行就设置在线图片反代

**Comment by xipesoy** [comment]
没有国外服务器只有国内的能整吗aqa

**Comment by Tsuk1ko** [comment]
- 方法1：设置 [`bot.setu.pximgProxy`](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#pximgproxy%E8%AF%B4%E6%98%8E)
- 方法2：设置 `bot.proxy` 让本地 pximg 反代走这个代理

**Comment by xipesoy** [comment]
aqa 现在能发图了 不知道是速度慢还是啥… 五张只会发两张左右的图片 要等几分钟 有没有啥解决办法呀owo
