### ISSUE TITLE
群聊内搜图结果是唯一的

### ISSUE THREAD

**Issue by Lancercmd** [Tsuk1ko/cq-picsearcher-bot#195]
简单地说，群聊内搜图的结果永远是同一个
但私聊正常

nodejs v14.16.0
go-cqhttp v0.9.39
cq-picsearcher-bot v2.28.5~v2.29.2

**Comment by Tsuk1ko** [comment]
开启 `bot.debug` 在群里搜几次图，提供一下相应的日志（记得脱敏）
