### ISSUE TITLE
群聊中回复图片消息@机器人时获取到的 url 不正确

### ISSUE THREAD

**Issue by NekoAria** [Tsuk1ko/cq-picsearcher-bot#198]
群聊中回复图片消息@机器人时获取到的 url 不正确。

---

情形如下：
![image](https://user-images.githubusercontent.com/23137034/119951948-15cfaf80-bfcf-11eb-997a-23f0b1fe43ed.png)
![image](https://user-images.githubusercontent.com/23137034/119955202-685e9b00-bfd2-11eb-9c7d-dc94cc7b0e64.png)
![image](https://user-images.githubusercontent.com/23137034/119952076-34ce4180-bfcf-11eb-9e5f-732e8d234cb7.png)
![image](https://user-images.githubusercontent.com/23137034/119955317-875d2d00-bfd2-11eb-815b-90f8fcd21650.png)

上面图中错误的 url ：
```text
https://c2cpicdw.qpic.cn/offpic_new/0/0-0-DD953D467F10B7C600FEEC30FD7B20A0/0
https://c2cpicdw.qpic.cn/offpic_new/0/0-0-6E7ABD451C8FA1AC8F6B6C5B8186EE80/0
```

对应的日志：
```text
05-28 15:09:42 [INFO] nonebot | CQHTTP xxx | [message.group.normal]: Message -2003465364 from xxx@[群:xxx] "[CQ:image,file=dd953d467f10b7c600feec30fd7b20a0.image,url=https://gchat.qpic.cn/gchatpic_new/[发图片的群友 qq ]/747598003-2983752310-DD953D467F10B7C600FEEC30FD7B20A0/0?term=3]"
05-28 15:57:39 [INFO] nonebot | CQHTTP xxx | [message.group.normal]: Message 370583266 from xxx@[群:xxx] "[CQ:image,file=6e7abd451c8fa1ac8f6b6c5b8186ee80.image,url=https://gchat.qpic.cn/gchatpic_new/[发图片的群友 qq ]/747598003-2570598220-6E7ABD451C8FA1AC8F6B6C5B8186EE80/0?term=3]"
```

---

运行环境：
- 系统：Debian GNU/Linux 10 (buster) x86_64
- Node.js 版本：v14.16.1
- go-cqhttp 版本：v1.0.0-beta4
- cq-picsearcher-bot 版本：v2.29.4

**Comment by Tsuk1ko** [comment]
这个其实是修复 #195 时做的一个调整

404 原因是机器人这边获取到的链接 `https://gchat.qpic.cn/gchatpic_new/X/Y-Z-HASH/0` 中的 `Z` 好像莫名其妙丢失了，这本应是个合法 qq 号，因此目前干脆直接统一替换成 `10000` 了

至于 `X` 和 `Y` 是不关键的因此干脆统一脱敏处理了，`https://gchat.qpic.cn/gchatpic_new/` 和 `https://c2cpicdw.qpic.cn/offpic_new/` 是通用的
