### ISSUE TITLE
利用服务端程序延迟来绕过 setu 模块节制时间

### ISSUE THREAD

**Issue by Kotoki1337** [Tsuk1ko/cq-picsearcher-bot#200]
不是很会描述，希望能传达到位

### Bug 描述
在 Bot 处理第一张色图指令但并没有发出第一张色图的这段时间中，接下来的所有色图指令无视节制时间
   - 是否稳定复现，是的话说明步骤
      - 使用一台延迟较高的服务器部署（可选，低延迟也会触发此问题，区别在数量的多少）
      - 像 gif 图中的方式一样在第一张色图出来之前快速发送色图指令
      - 问题复现
   - 期望的正常行为是怎么样的
      - 防止人们使用这个 Bug 无视节制时间
### 截图、日志、配置
可以无视 `Gugu Sillylemon` 这个 bot，我没有它的控制权，所以我不清楚它具体的版本号。
![动画](https://user-images.githubusercontent.com/35394151/120010380-a7f7a800-c00f-11eb-9ced-aabb53fbd0ca.gif)

### 运行环境
   - Windows Server
   - cq-picsearcher-bot `2.29.5`
   - node.js `14`
   - go-cqhttp `1.0.0beta4`

### Others
不熟悉 js，应该是 Bot 从发出第一张图时才开始计时节制时间，导致 Bot 在找图的间隙中收到了其他的异步指令导致绕过了第一张图的节制时间。

可以尝试在收到首个色图指令的时候直到第一张图发送之前无视同一用户的其他色图指令并返回 None（或者`你发的太快了`之类的）？

**Comment by Tsuk1ko** [comment]
原来 bot 收到搜图和 setu 请求会判断剩余配额，直到请求成功才扣除配额，因此会有这个漏洞

现在改为收到请求时直接扣除配额，如果失败则返还配额

（`你发得太快了` 倒是没有加，这种单独的小逻辑不太想搞）
