### ISSUE TITLE
OCR识别问题

### ISSUE THREAD

**Issue by HiyoriTUK** [Tsuk1ko/cq-picsearcher-bot#203]
1. Bug 描述
   - 向bot发送--ocr后无任何回复
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
1|cqps     | TypeError: Cannot read property 'catch' of undefined
1|cqps     |     at handleOcrResult (/home/hiyori/cq-picsearcher-bot/main.js:558:38)
1|cqps     |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
3. 运行环境
   - 系统，ubuntu 20.04
   - node.js 版本 14.17.0
   - go-cqhttp 1.0.0-bate4
   - cq-picsearcher-bot 版本 2.29.8

**Comment by HiyoriTUK** [comment]
@Tsuk1ko 

如果使用QQ的OCR会出现
1|cqps  | 6/2/2021, 7:00:10 PM [error] OCR
1|cqps  | TypeError: Cannot read property 'texts' of null
1|cqps  |     at Proxy.default (/home/hiyori/cq-picsearcher-bot/src/plugin/ocr/qq.js:11:13)
1|cqps  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
并提示OCR发生错误

如果使用百度的OCR的话则bot什么回复也没有，并且log什么也没有

**Comment by Tsuk1ko** [comment]
开启 `bot.debug` 再使用 ocr 功能，然后发下日志中 bot 收到的消息内容，图片链接会带有q号或群号，用 0 替换

**Comment by HiyoriTUK** [comment]
> 开启 `bot.debug` 再使用 ocr 功能，然后发下日志中 bot 收到的消息内容，图片链接会带有q号或群号，用 0 替换

QQ的ocr似乎又没什么问题，但百度ocr问题依旧
1|cqps  | 6/2/2021, 9:16:22 PM 收到私聊消息 qq=0
1|cqps  | [CQ:image,file=a4f771e047939241e066738604d07594.image,url=https://c2cpicdw.qpic.cn/offpic_new/0//0-3178870148-A4F771E047939241E066738604D07594/0?term=3]
1|cqps  | --ocr

**Comment by Tsuk1ko** [comment]
确定 `bot.akhr.ocr` 是 `qq`？

项目 data 目录下有 akhr.json 么

**Comment by HiyoriTUK** [comment]
> 确定 `bot.akhr.ocr` 是 `qq`？
> 
> 项目 data 目录下有 akhr.json 么

确定，有

**Comment by Tsuk1ko** [comment]
🤔这也太奇怪了，我都不知道要怎么排查问题了

**Comment by HiyoriTUK** [comment]
@Tsuk1ko 重新弄了一个配置文件发现QQ的ocr以及公招计算器都没问题了，但百度ocr依然不会有回复

**Comment by Tsuk1ko** [comment]
百度 OCR 我测试了是没有问题的

**Comment by HiyoriTUK** [comment]
> 百度 OCR 我测试了是没有问题的

![image](https://user-images.githubusercontent.com/45660358/121364338-479b2b80-c96a-11eb-92bd-2ea45585a615.png)
发现是百度这边的调用额度没了
