### ISSUE TITLE
回复搜图可以搜索撤回的图片

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#208]
通过检索gocq的log，有防撤回的手机端在回复撤回的图片时也能进行搜图

**Comment by Tsuk1ko** [comment]
看来是撤回并不会使 go-cqhttp 从它的数据库中删除这条消息，因此仍然可以获取到消息内容

这也没什么吧，防撤回终归是防不住的，就算不能回复搜图人家也可以手动保存图片再去搜图呀

**Comment by Miuzarte** [comment]
> 这也没什么吧，防撤回终归是防不住的，就算不能回复搜图人家也可以手动保存图片再去搜图呀

然后就'⚠️未在本次搜图模式中收到过图片'

**Comment by Miuzarte** [comment]
主要是方便搜索撤回的setu（

**Comment by Miuzarte** [comment]
> 主要是方便搜索撤回的setu（

不对啊  又不是没链接  搜什么搜
sb群友  我也sb了

**Comment by Tsuk1ko** [comment]
草，你也不说全，我以为能搜，那就是不能搜呗，go-cqhttp 拿不到消息内容，那就拿不到吧

**Comment by Miuzarte** [comment]
> 草，你也不说全，我以为能搜，那就是不能搜呗，go-cqhttp 拿不到消息内容，那就拿不到吧

我试了下/get_msg这个API确实能拿到撤回的消息（不用去特地检索log），可是bot不会搜图

**Comment by Tsuk1ko** [comment]
🤔要看给到的CQ:reply有没有消息ID

**Comment by Miuzarte** [comment]
> 🤔要看给到的CQ:reply有没有消息ID

没事了，单纯的因为gocq没有自己本身发出的消息记录所以获取不到🌿
