### ISSUE TITLE
添加e-hentai/exhentai本子搜索

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#211]
添加e-hentai/exhentai本子搜索
让用户提供ehent的账号cookie去访问exhent
![IMG_20210607_183930.jpg](https://user-images.githubusercontent.com/66856838/121003217-e64d3f80-c752-11eb-84df-c7c265b66ccf.jpg)
![IMG_20210607_183915.jpg](https://user-images.githubusercontent.com/66856838/121003233-ea795d00-c752-11eb-90d6-efd6ba999063.jpg)

**Comment by Tsuk1ko** [comment]
是最新版的？我这都能搜到，之前有个版本修了下搜索的 bug，按理来说只要N站里有的都搜得到了，只不过可能没汉化而已

![image](https://user-images.githubusercontent.com/24877906/121015745-e9394600-c7cd-11eb-8def-c3c964379660.png)

![image](https://user-images.githubusercontent.com/24877906/121015784-f48c7180-c7cd-11eb-9a5a-c7024d658ec7.png)

**Comment by Miuzarte** [comment]
> 是最新版的？我这都能搜到，之前有个版本修了下搜索的 bug，按理来说只要N站里有的都搜得到了，只不过可能没汉化而已
> 
> ![image](https://user-images.githubusercontent.com/24877906/121015745-e9394600-c7cd-11eb-8def-c3c964379660.png)
> 
> ![image](https://user-images.githubusercontent.com/24877906/121015784-f48c7180-c7cd-11eb-9a5a-c7024d658ec7.png)

草，那就很奇怪了，还以为是梯子问题，但是梯子确实规则到了，梯子也是正常的
![IMG_20210607_213619.jpg](https://user-images.githubusercontent.com/66856838/121026275-96c73d80-c76b-11eb-9928-2f7ae3a76c35.jpg)

你去试试这图？
![-72bfed28e0502b67.jpg](https://user-images.githubusercontent.com/66856838/121026299-9c248800-c76b-11eb-9378-9cf69071f192.jpg)

**Comment by Tsuk1ko** [comment]
也没问题……

![image](https://user-images.githubusercontent.com/24877906/121026916-1fc88e00-c7d9-11eb-9073-90dd546dea82.png)

**Comment by Miuzarte** [comment]
--debug
'''
0|cqps  | {"header":{"user_id":"46759","account_type":"1","short_limit":"6","long_limit":"200","long_remaining":111,"short_remaining":4,"status":0,"results_requested":3,"index":{"0":{"status":0,"parent_id":0,"id":0,"results":3},"2":{"status":0,"parent_id":2,"id":2,"results":3},"5":{"status":0,"parent_id":5,"id":5,"results":3},"6":{"status":0,"parent_id":6,"id":6,"results":3},"8":{"status":0,"parent_id":8,"id":8,"results":3},"9":{"status":0,"parent_id":9,"id":9,"results":6},"10":{"status":0,"parent_id":10,"id":10,"results":3},"11":{"status":0,"parent_id":11,"id":11,"results":3},"12":{"status":0,"parent_id":9,"id":12,"results":6},"16":{"status":0,"parent_id":16,"id":16,"results":3},"18":{"status":0,"parent_id":18,"id":18,"results":3},"19":{"status":0,"parent_id":19,"id":19,"results":3},"20":{"status":0,"parent_id":20,"id":20,"results":3},"21":{"status":0,"parent_id":21,"id":21,"results":3},"22":{"status":0,"parent_id":22,"id":22,"results":3},"23":{"status":0,"parent_id":23,"id":23,"results":3},"24":{"status":0,"parent_id":24,"id":24,"results":3},"25":{"status":0,"parent_id":9,"id":25,"results":6},"26":{"status":0,"parent_id":9,"id":26,"results":6},"27":{"status":0,"parent_id":9,"id":27,"results":6},"28":{"status":0,"parent_id":9,"id":28,"results":6},"29":{"status":0,"parent_id":9,"id":29,"results":6},"30":{"status":0,"parent_id":9,"id":30,"results":6},"31":{"status":0,"parent_id":31,"id":31,"results":3},"32":{"status":0,"parent_id":32,"id":32,"results":3},"33":{"status":0,"parent_id":33,"id":33,"results":3},"34":{"status":0,"parent_id":34,"id":34,"results":3},"35":{"status":0,"parent_id":35,"id":35,"results":3},"36":{"status":0,"parent_id":36,"id":36,"results":3},"37":{"status":0,"parent_id":37,"id":37,"results":3},"38":{"status":0,"parent_id":38,"id":38,"results":3},"39":{"status":0,"parent_id":39,"id":39,"results":3},"40":{"status":0,"parent_id":40,"id":40,"results":3},"41":{"status":0,"parent_id":41,"id":41,"results":3},"42":{"status":0,"parent_id":42,"id":42,"results":3},"51":{"status":0,"parent_id":5,"id":51,"results":3},"52":{"status":0,"parent_id":5,"id":52,"results":3},"53":{"status":0,"parent_id":5,"id":53,"results":3},"211":{"status":0,"parent_id":21,"id":211,"results":3},"341":{"status":0,"parent_id":341,"id":341,"results":3}},"search_depth":"128","minimum_similarity":49.6,"query_image_display":"userdata/h3uw9y3yF.jpg.png","query_image":"h3uw9y3yF.jpg","results_returned":3},"results":[{"header":{"similarity":"71.65","thumbnail":"https://img1.saucenao.com/res/nhentai/361763%20%281919150%29%20--%20%5BCAT%20GARDEN%20%28Nekotewi%29%5D%20Gerda%20to%20Ayesha%20no%20Shiawase%20no%20Katachi%20%28Fate_Grand%20Order%29%20%5BDigital%5D/16t.jpg?auth=Jz7r3flw9VnKNQApM9XsGg&exp=1623178800","index_id":18,"index_name":"Index #18: H-Misc (nhentai) - 16t.jpg","dupes":3},"data":{"source":"Gerda to Ayesha no Shiawase no Katachi","creator":["nekotewi","cat garden"],"eng_name":"[CAT GARDEN (Nekotewi)] Gerda to Ayesha no Shiawase no Katachi (Fate_Grand Order)","jp_name":"[CAT GARDEN (ねこてゐ)] ゲルダとアーシャのしあ わせのか たち (Fate/Grand Order)"}},{"header":{"similarity":"66.43","thumbnail":"https://img3.saucenao.com/ehentai/9f/5e/9f5e0ec66f09ab6c5872032bbcdb860bd49c912a.jpg?auth=l1-b25qaFm8k_1-E63giXg&exp=1623178800","index_id":38,"index_name":"Index #38: H-Misc (E-Hentai) - 9f5e0ec66f09ab6c5872032bbcdb860bd49c912a.jpg","dupes":1},"data":{"source":"Gerda to Ayesha no Shiawase no Katachi","creator":["nekotewi","cat garden"],"eng_name":"(C97) [CAT GARDEN (Nekotewi)] Gerda to Ayesha no Shiawase no Katachi (Fate/Grand Order)","jp_name":"(C97) [CAT GARDEN (ねこてゐ)] ゲルダとアーシャのしあわせ の かたち (Fate/Grand Order)"}},{"header":{"similarity":"48.60","thumbnail":"https://img1.saucenao.com/res/pixiv/6799/manga/67995108_p3.jpg?auth=TSaBIrdkH1LTwsm0lUWZ9g&exp=1623178800","index_id":5,"index_name":"Index #5: Pixiv Images - 67995108_p3.jpg","dupes":0},"data":{"ext_urls":["https://www.pixiv.net/member_illust.php?mode=medium&illust_id=67995108"],"title":"【プリジャン20】 にのゆい本","pixiv_id":67995108,"member_name":"maimu","member_id":20049}}]}
'''

**Comment by Tsuk1ko** [comment]
大概懂了，你这个搜索的时候匹配的 nhentai 的索引，这个英文名有点问题，`/` 变成 `_` 了，导致没搜出来，不知道为什么它的索引会这样，nhentai 上的英文名都是正常的……

我的搜索匹配到 ehentai 的索引上了名字是正常的

我直接暴力替换一下算了，我看了看没有本子名带 `_` 的

**Comment by Miuzarte** [comment]
解决了
