### ISSUE TITLE
setu功能关键词无法搜索tag

### ISSUE THREAD

**Issue by assassingyk** [Tsuk1ko/cq-picsearcher-bot#212]
如题。不清楚这个issue是不是该在这边提……

总之就是lolicon API的色图功能现在带keyword时似乎不能像之前一样模糊搜索作品tag及tag中英文翻译了，只会返回标题及作者名中含有keyword的结果。

不知道这是出的bug还是说迁移后取消了这个功能了所以来问一下……

**Comment by Tsuk1ko** [comment]
确实，我会修下

**Comment by Tsuk1ko** [comment]
修复了
