### ISSUE TITLE
使用npm start启动时出现以下错误

### ISSUE THREAD

**Issue by Bearlele** [Tsuk1ko/cq-picsearcher-bot#219]
[PM2] Applying action restartProcessId on app [cqps](ids: [ 1 ])
[PM2][ERROR] Process 1 not found
Process 1 not found
/root/cq-picsearcher-bot/node_modules/pm2/lib/API.js:1720
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read property 'pm2_env' of undefined
    at /root/cq-picsearcher-bot/node_modules/pm2/lib/API.js:1720:25
    at Array.forEach (<anonymous>)
    at API.speedList (/root/cq-picsearcher-bot/node_modules/pm2/lib/API.js:1719:18)
    at /root/cq-picsearcher-bot/node_modules/pm2/lib/binaries/CLI.js:301:15
    at wrapper (/root/cq-picsearcher-bot/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at replenish (/root/cq-picsearcher-bot/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:76:25)
    at iterateeCallback (/root/cq-picsearcher-bot/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:65:17)
    at /root/cq-picsearcher-bot/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at /root/cq-picsearcher-bot/node_modules/pm2/lib/binaries/CLI.js:292:11
    at /root/cq-picsearcher-bot/node_modules/pm2/lib/API.js:334:21
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cq-picsearcher-bot@2.29.10 start: `pm2 start ecosystem.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cq-picsearcher-bot@2.29.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by Bearlele** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.13
3 info using node@v14.17.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cq-picsearcher-bot@2.29.10~prestart: cq-picsearcher-bot@2.29.10
6 info lifecycle cq-picsearcher-bot@2.29.10~start: cq-picsearcher-bot@2.29.10
7 verbose lifecycle cq-picsearcher-bot@2.29.10~start: unsafe-perm in lifecycle true
8 verbose lifecycle cq-picsearcher-bot@2.29.10~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/cq-picsearcher-bot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle cq-picsearcher-bot@2.29.10~start: CWD: /root/cq-picsearcher-bot
10 silly lifecycle cq-picsearcher-bot@2.29.10~start: Args: [ '-c', 'pm2 start ecosystem.config.js' ]
11 silly lifecycle cq-picsearcher-bot@2.29.10~start: Returned: code: 1  signal: null
12 info lifecycle cq-picsearcher-bot@2.29.10~start: Failed to exec start script
13 verbose stack Error: cq-picsearcher-bot@2.29.10 start: `pm2 start ecosystem.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid cq-picsearcher-bot@2.29.10
15 verbose cwd /root/cq-picsearcher-bot
16 verbose Linux 4.19.0-16-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.17.1
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error cq-picsearcher-bot@2.29.10 start: `pm2 start ecosystem.config.js`
22 error Exit status 1
23 error Failed at the cq-picsearcher-bot@2.29.10 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Miuzarte** [comment]
什么环境 比如arm还是x86(我也不太懂 问问

**Comment by Bearlele** [comment]
> 什么环境 比如arm还是x86(我也不太懂 问问

amd64 之前一直可以的 只是重启一下就不行了

**Comment by Miuzarte** [comment]
> > 什么环境 比如arm还是x86(我也不太懂 问问
> 
> amd64 之前一直可以的 只是重启一下就不行了

有试过重新拉取么

**Comment by Tsuk1ko** [comment]
试试万能的
```
npx pm2 kill
npm start
```

**Comment by Bearlele** [comment]
> > > 什么环境 比如arm还是x86(我也不太懂 问问
> > 
> > 
> > amd64 之前一直可以的 只是重启一下就不行了
> 
> 有试过重新拉取么

试过的 重新部署了也不行

**Comment by Bearlele** [comment]
> 试试万能的
> 
> ```
> npx pm2 kill
> npm start
> ```

ohhhh！可以了谢谢

**Comment by Miuzarte** [comment]
> 试试万能的
> ```
> npx pm2 kill
> npm start
> ```

🌿

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/123464537-86460c80-d61f-11eb-8a48-531e604cf0fa.png)
