### ISSUE TITLE
提示二次截图的回复似乎没有正常工作

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#232]
![image](https://user-images.githubusercontent.com/66856838/127303127-502554e2-50d7-4aaf-8759-74aeaee7b7ee.png)
![image](https://user-images.githubusercontent.com/66856838/127303259-6ebb72e7-d7a1-4699-9aae-50f00e45b9c1.png)

**Comment by Tsuk1ko** [comment]
……看起来是这个回复改了，后面多了个 `(404 - url)`
