### ISSUE TITLE
在接收到含有大量图片的转发消息时出现无响应情况

### ISSUE THREAD

**Issue by waya13** [Tsuk1ko/cq-picsearcher-bot#236]
如题，go-cqhttp接收到合并的含有大量图片的转发消息时，cqps相关功能会出现无响应情况
出现问题后 我首先用pm2 status命令确认了cqps的运行情况为online

发现问题后我使用debug模式和npm run test私聊进行了复现

![QQ图片20210810142357](https://user-images.githubusercontent.com/31008802/128818398-099e8b20-c9fb-43a0-be21-eeb3ffa8c94d.png)
![QQ图片20210810142418](https://user-images.githubusercontent.com/31008802/128818463-a12ab3ef-bbc1-47d7-90a6-d0373ecadfec.png)

在引发无响应后我尝试使用Ctrl+C强制退出，但无果
请问是否有办法可以在检测到CQ:forward时忽略掉消息？目前好像暂时只有转发消息会引发问题

系统版本为CentOS 8.3.2011
nodejs版本为v16.3.0 go-cqhttp版本为八天前更新的v1.0.0-beta5 cq-picsearcher-bot版本为2.29.14

**Comment by Tsuk1ko** [comment]
这个问题是 go-cqhttp v1.0.0-beta5 才出现的么

以及在群聊中是否会出现

**Comment by waya13** [comment]
是更新go-cqhttp后才出现的 但是在更新go-cqhttp的同时我也更新了放了两个月没有更新的cqps
出现问题时一开始我没有找到原因 尝试把cqps重新安装但是没有效果 可能问题的确出在go-cqhttp上

群聊中也会出现此问题 这个问题一开始就是在群聊中发现的

**Comment by Tsuk1ko** [comment]
了解了，回头研究下，如果是 go-cqhttp 相关问题我会到那边提 issue

话说 @Miuzarte 你遇到的卡死现象会不会也是这个原因（虽然说我要试用但因为太懒又咕咕咕了）

**Comment by waya13** [comment]
好的，非常感谢

**Comment by Miuzarte** [comment]
> 了解了，回头研究下，如果是 go-cqhttp 相关问题我会到那边提 issue
> 
> 话说 @Miuzarte 你遇到的卡死现象会不会也是这个原因（虽然说我要试用但因为太懒又咕咕咕了）

我的gocq没事，我出事之后重启cqps就好了

**Comment by Tsuk1ko** [comment]
> > 了解了，回头研究下，如果是 go-cqhttp 相关问题我会到那边提 issue
> > 话说 @Miuzarte 你遇到的卡死现象会不会也是这个原因（虽然说我要试用但因为太懒又咕咕咕了）
> 
> 我的gocq没事，我出事之后重启cqps就好了

说的是 cqps 卡死

**Comment by Miuzarte** [comment]
> > > 了解了，回头研究下，如果是 go-cqhttp 相关问题我会到那边提 issue
> > > 话说 @Miuzarte 你遇到的卡死现象会不会也是这个原因（虽然说我要试用但因为太懒又咕咕咕了）
> > 
> > 我的gocq没事，我出事之后重启cqps就好了
> 
> 说的是 cqps 卡死

（没仔细看
我回beta5用几天看看  我问题都是在中午十二点和凌晨十二点左右出现的  非常的固定  不知道怎么回事

**Comment by Moehentai2333** [comment]
呜呜呜,鹅鹅的是,然后cpu就满载了,看了下gocq上次更新,修复: 合并转发消息未遵守onebot协议的问题,是不是这里的问题.

**Comment by NekoAria** [comment]
巧了，我也是今天遇到了这个 BUG 。
同样的合并转发多图，同样的 CPU 满载。
gocq 是 beta5 。

**Comment by NekoAria** [comment]
不过我不确定这是 gocq 升级到 beta5 才有的问题，因为我之前也遇到过一次 CPU 满载。
当时没细看日志，直接重启了相关的所有机器人进程，包括 gocq 和 cqps 。

**Comment by waya13** [comment]
我把go-cqhttp回滚到了v1.0.0-beta4，目前已经不会出现这个问题了
大概是go-cqhttp的beta5版本对合并转发消息做出的修改才导致了问题吧

**Comment by Tsuk1ko** [comment]
我看那边有一个可能相关的 issue Mrs4s/go-cqhttp#999

我试了下最新的 dev 版本，多图合并转发没有卡死，各位也试看？

https://github.com/Mrs4s/go-cqhttp/actions/runs/1115680902

**Comment by waya13** [comment]
> 我看那边有一个可能相关的 issue [Mrs4s/go-cqhttp#999](https://github.com/Mrs4s/go-cqhttp/issues/999)
> 
> 我试了下最新的 dev 版本，多图合并转发没有卡死，各位也试试看？
> 
> https://github.com/Mrs4s/go-cqhttp/actions/runs/1115680902

目前使用最新的dev版本没有再出现这个问题了，非常感谢

**Comment by Miuzarte** [comment]
> 我看那边有一个可能相关的 issue [Mrs4s/go-cqhttp#999](https://github.com/Mrs4s/go-cqhttp/issues/999)
> 
> 我试了下最新的 dev 版本，多图合并转发没有卡死，各位也试试看？
> 
> https://github.com/Mrs4s/go-cqhttp/actions/runs/1115680902

我这4天用的就是dev  确实没出过问题

**Comment by NekoAria** [comment]
> 我看那边有一个可能相关的 issue [Mrs4s/go-cqhttp#999](https://github.com/Mrs4s/go-cqhttp/issues/999)
> 
> 我试了下最新的 dev 版本，多图合并转发没有卡死，各位也试试看？
> 
> https://github.com/Mrs4s/go-cqhttp/actions/runs/1115680902

那可以关闭这个 issue 了
