### ISSUE TITLE
精准度低于60%的能不能直接过滤掉？

### ISSUE THREAD

**Issue by Minori-ty** [Tsuk1ko/cq-picsearcher-bot#237]
请说明：
精准度低于60%的能不能直接过滤掉？
已经配置了saucenao的api，但有时后搜不到，就老是会匹配到一些精准度非常低的黄图，迟早炸群。

**Comment by Miuzarte** [comment]
合并消息腾讯管不到，我用了11个月  日均20次调用  没炸群

**Comment by Minori-ty** [comment]
> 合并消息腾讯管不到，我用了11个月 日均20次调用 没炸群

关键不是炸群，而是精确度很低的话，那就没有意义

**Comment by Tsuk1ko** [comment]
可以用 `bot.hideImgWhenLowAcc` 配置隐藏相似度低于 `bot.saucenaoLowAcc` 的结果图

**Comment by Minori-ty** [comment]
> 可以用 `bot.hideImgWhenLowAcc` 配置隐藏相似度低于 `bot.saucenaoLowAcc` 的结果图

![image](https://user-images.githubusercontent.com/79521943/130312554-a63e5eb9-e607-4ac2-96a7-8ca7d7ac8ebc.png)
一直显示服务器炸了，并且配置了api也无法启用saucenao的搜图功能

**Comment by Tsuk1ko** [comment]
看一下错误日志

**Comment by Minori-ty** [comment]
> 看一下错误日志

![image](https://user-images.githubusercontent.com/79521943/130313021-f42f85ce-3f64-4db8-be52-e620c7b5983e.png)

**Comment by Tsuk1ko** [comment]
网络问题……挂代理吧

**Comment by Minori-ty** [comment]
> 网络问题……挂代理吧

没挂，不过我是放在docker里面运行的，不知道算不算代理。
docker的好处是，我不用去买服务器，并且每次电脑开机都能自启动，永久化。

**Comment by Tsuk1ko** [comment]
我的意思是你这个就是单纯的网络问题而已，要稳点就自行挂代理
