### ISSUE TITLE
ascii2d 增加错误提示

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#238]
描述：ascii2d搜索总是失败，控制台出现类似html的内容（太长导致只能看到中间的部分，再往上没法滚动，头上有啥不太清楚）
系统 win7 
nodejs 14.17.5（强行手动安装于win7）
版本 2.29.14/1.0.0-beta6
重新部署问题依旧，挂代理等无效

![Screenshot_20210821-224500](https://user-images.githubusercontent.com/89308692/130325550-6f32cd10-a07d-45da-b09f-84a11640efac.png)
![Screenshot_20210821-224523](https://user-images.githubusercontent.com/89308692/130325558-da3de334-4fa2-4015-9a8d-fef00297cfce.png)

**Comment by Miuzarte** [comment]
日志文件在cq-picsearcher-bot/logs/

**Comment by A2Sumie** [comment]
> 日志文件在cq-picsearcher-bot/logs/

没有这个文件夹，需要先设置什么才会记录日志吗，没有看见相关的配置

**Comment by A2Sumie** [comment]
> 日志文件在cq-picsearcher-bot/logs/

有了，平时用的npm run test所以没记录的样子 
[error.log](https://github.com/Tsuk1ko/cq-picsearcher-bot/files/7025719/error.log)
这就是了

**Comment by A2Sumie** [comment]
再排查了一遍，是搜索的图超过a2d的5m大小限制了，用的样本全是大尺寸原图所以误认为整个功能挂了

**Comment by Tsuk1ko** [comment]
我会补充个图片过大的错误提示
