### ISSUE TITLE
reminder的时间与系统时间不一致

### ISSUE THREAD

**Issue by SEAFHMC** [Tsuk1ko/cq-picsearcher-bot#239]
1. Bug 描述
服务器地区为美国洛杉矶，已更改系统时间为东8区。但reminder似乎仍旧使用的是美国时间。
2. 截图、日志、配置
![IMG_20210824_090713](https://user-images.githubusercontent.com/9484642/130539186-9ece2d80-b2a6-47fd-b5ad-cf9ac8c4a97f.jpg)
![IMG_20210824_090131](https://user-images.githubusercontent.com/9484642/130538794-2d7809cb-69cd-45d0-b6a0-812d3ad29870.jpg)
3. 运行环境
   - 系统：CentOS 8
   - node.js 版本：14.17.5
   - go-cqhttp 版本：1.0.0-beta6
   - cq-picsearcher-bot 版本：2.29.15

**Comment by Tsuk1ko** [comment]
更改时区后有试过重启 bot 吗

我也是用的洛杉矶服务器调了时区，是正常的

**Comment by SEAFHMC** [comment]
> 更改时区后有试过重启 bot 吗
> 
> 我也是用的洛杉矶服务器调了时区，是正常的

刚刚重启了一遍bot，还是不行，我试试把系统重启一遍。

**Comment by SEAFHMC** [comment]
> > 更改时区后有试过重启 bot 吗
> > 我也是用的洛杉矶服务器调了时区，是正常的
> 
> 刚刚重启了一遍bot，还是不行，我试试把系统重启一遍。

emmm，重启系统也没效果。

**Comment by Tsuk1ko** [comment]
> 更改时区后有试过重启 bot 吗
> 
> 我也是用的洛杉矶服务器调了时区，是正常的

噢噢我之前记错了，我换了服务器之后就没用过这个功能了

看了下 cron-parser 确实有个时区选项，我加个自动检测时区

**Comment by SEAFHMC** [comment]
> > 更改时区后有试过重启 bot 吗
> > 我也是用的洛杉矶服务器调了时区，是正常的
> 
> 噢噢我之前记错了，我换了服务器之后就没用过这个功能了
> 
> 看了下 cron-parser 确实有个时区选项，我加个自动检测时区

嗯！谢啦，期待后续版本。

**Comment by Tsuk1ko** [comment]
不对，怪了，我又测试了一下，确实默认就是符合时区的

![image](https://user-images.githubusercontent.com/24877906/130626709-d496d904-f475-4e6f-9f62-ea2472cc43db.png)

而且 cron-parse 的默认表现也没问题

![image](https://user-images.githubusercontent.com/24877906/130626754-7b78747b-0401-4ebc-941a-4449f7496859.png)

你试一下在项目目录下执行 `node` 然后跟上面一样执行这个代码看看会输出什么

```js
const parser = require('cron-parser')
parser.parseExpression('0 0 * * *').next().toString()
```

**Comment by SEAFHMC** [comment]
> 不对，怪了，我又测试了一下，确实默认就是符合时区的
> 
> ![image](https://user-images.githubusercontent.com/24877906/130626709-d496d904-f475-4e6f-9f62-ea2472cc43db.png)
> 
> 而且 cron-parse 的默认表现也没问题
> 
> ![image](https://user-images.githubusercontent.com/24877906/130626754-7b78747b-0401-4ebc-941a-4449f7496859.png)
> 
> 你试一下在项目目录下执行 `node` 然后跟上面一样执行这个代码看看会输出什么
> 
> ```js
> const parser = require('cron-parser')
> parser.parseExpression('0 0 * * *').next().toString()
> ```
> 
> 顺便看一下 `Date()` 的输出
> 
> ![image](https://user-images.githubusercontent.com/24877906/130627562-457840cc-16e9-4fd7-8780-f6c892d8bda7.png)

刚开始说没有安装cron-parse，安装并运行代码之后显示确实差了12小时
![IMG_20210825_130707](https://user-images.githubusercontent.com/9484642/130730052-c0bbc9b4-4ca7-42ad-899b-fdc37030f3a3.jpg)

**Comment by Tsuk1ko** [comment]
在 node 里面分别执行这两句

```
process.env.TZ
Intl.DateTimeFormat().resolvedOptions().timeZone
```

看看输出结果

------

以及执行

```
process.env.TZ = 'Asia/Shanghai'
```

之后，重复之前 cron-parser 那个操作看看输出

**Comment by SEAFHMC** [comment]
![IMG_20210825_215105](https://user-images.githubusercontent.com/9484642/130803348-2aee672f-5a3e-40ab-a0e8-a2a17b762d05.jpg)
OH～ 变成中国时间了

**Comment by Tsuk1ko** [comment]
看来你这个问题是 node 读取到的系统时区不正确引起的，node 默认认为你的时区是纽约，我也不清楚原因，只能通过环境变量指定时区了

更新至 v2.30.0 后，在项目根目录创建一个 `.env` 文件，往里面写入

```
TZ=Asia/Shanghai
```

就可以了
