### ISSUE TITLE
使用base64发送saucenao图片

### ISSUE THREAD

**Issue by foxwhite25** [Tsuk1ko/cq-picsearcher-bot#244]
现在saucenao的图片需要挂代理才能发，但是貌似go cqhttp不走系统代理，也没有代理的选项，导致很多saucenao的图片都发不出来。
这边建议在picsearcher就把图片先转化为base64，就不会有这样的问题。

```
var request = require('request').defaults({ encoding: null });
request.get('http://tinypng.org/images/example-shrunk-8cadd4c7.png', function (error, response, body) {
    if (!error && response.statusCode == 200) {
        data = Buffer.from(body).toString('base64');
    }
});

**Comment by Miuzarte** [comment]
beta5我记得就能走代理了

**Comment by Miuzarte** [comment]
> beta5我记得就能走代理了

怪了  我也找不着了

**Comment by Miuzarte** [comment]
![IMG_20210902_081411.jpg](https://user-images.githubusercontent.com/66856838/131761650-c601cb1d-c23c-4a37-b699-f775a4153877.jpg)

**Comment by Tsuk1ko** [comment]
是的，早在 v0.9.32 就可以在 go-cqhttp 里配置代理了
