### ISSUE TITLE
setu发不出来

### ISSUE THREAD

**Issue by DongGua-Jun** [Tsuk1ko/cq-picsearcher-bot#253]
1. Bug 描述
   [有挂梯子，但梯子挂不挂都发不出]
   通过npm run test 看log，发现会通过443端口连到一个随机ip，但是提示连接超时
   以及报错:找不到MIME FOR BUFFER

2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
<img src = 'https://s3.bmp.ovh/imgs/2021/11/927a58e91a4036ce.png' />

    // setu 相关功能，部分配置的详细说明请查看“wiki-附加功能-setu”以了解更多
    "setu": {
      // 是否启用
      "enable": true,
      // APIKEY（已弃用，不再需要）
      "apikey": "",
      // 反和谐方式（0：关闭，1：轻微修改，2：旋转）
      "antiShielding": 1,
      // 是否允许私聊使用
      "allowPM": true,
      // P站图本地反代服务主机，可以手动指定，一般不需要动，详见 wiki
      "pximgServerHost": "127.0.0.1",
      // P站图本地反代服务端口，可以手动指定，0 为自动分配，详见 wiki
      "pximgServerPort": 0,
      // 发送时使用的P站本地反代服务地址，一般不需要，详见 wiki
      "usePximgAddr": "",
      // 发送时使用的P站在线反代服务地址，支持占位符 {{pid}} {{p}} {{uid}} {{ext}} {{path}}，详见 wiki（使用时上面三个配置将不再起效）
      "pximgProxy": "",
      // 镜像地址，发送地址时追加的在线反向代理的地址，设置为空数组则不追加，支持占位符同上
      "sendPximgProxys": ["https://i.pixiv.cat/"],
      // 对镜像地址进行短链接处理，可选值: ["oy.mk", "yww.uy"]，留空 "" 则不处理。
      "shortenPximgProxy": "",
      // 是否发送 master1200 大小的图片，以节省流量或加快发送速度，关闭时将发送原图
      "size1200": false,
      // 发送后这么多秒自动撤回（0 则不撤回，-1 为发送闪照）
      "deleteTime": 60,
      // 群内使用冷却时间（秒），每名用户独立，0 则无冷却，私聊无 cd
      "cd": 600,
      // 每名用户每日次数限制
      "limit": 30,
      // 群组白名单
      "whiteGroup": [],
      // 仅允许白名单群使用（与上面的私聊使用是独立的）
      "whiteOnly": true,
      // 白名单群组的群内使用冷却时间（秒），每名用户独立，0 则无冷却
      "whiteCd": 0,
      // 白名单群组内发送后这么多秒自动撤回（0 则不撤回，-1 为发送闪照）
      "whiteDeleteTime": 0,
      // r18 是否只发送地址不发送图片（如果开启，建议设置 `sendPximgProxys`）
      "r18OnlyUrl": {
        "private": false, // 私聊
        "group": false, // 群聊
        "temp": false // 群临时会话
      },
      // r18 图片只通过私聊发送（私聊不会被和谐，因此不会进行反和谐）
      "r18OnlyPrivate": true,
      // 允许临时会话发送 r18 结果，用法同 `bot.pmSearchResultTemp`
      "r18OnlyPrivateAllowTemp": false,
      // 只允许在白名单群组中发送 r18 setu
      "r18OnlyInWhite": true
3. 运行环境
   - 系统Windows Server 2012 R2 DataCenter 64bitCN
   - node.js 版本14.15.4
   - go-cqhttp v1.0.0-beta7-fix2
   - cq-picsearcher-bot 版本2.30.2

**Comment by Tsuk1ko** [comment]
挂梯子确定在 config 里配了 `bot.proxy` 吗

**Comment by Miuzarte** [comment]
> 挂梯子确定在 config 里配了 `bot.proxy` 吗

[issuecomment](https://github.com/Ninzore/Wecab/issues/59#issuecomment-962606049)
隔壁说pixiv.cat改成.re
我倒是还没试过

**Comment by Tsuk1ko** [comment]
> > 挂梯子确定在 config 里配了 `bot.proxy` 吗
> 
> [issuecomment](https://github.com/Ninzore/Wecab/issues/59#issuecomment-962606049)
> 隔壁说pixiv.cat改成.re
> 我倒是还没试过

这个情况没用在线反代，走的本地反代，本地反代是会用配置里的代理的

**Comment by DongGua-Jun** [comment]
// 大部分请求所使用的代理，支持 http(s):// 和 socks://
    "proxy": "https://ssrss.de/s/【数据删除】",
格式应该是这个吧？

bot.proxy填入上述内容后，机器人提示涩图服务器爆炸了
报错如下，
![image](https://user-images.githubusercontent.com/75875483/140722038-9ecb5b8d-198a-457d-860e-ff6e4a24f3b1.png)
![image](https://user-images.githubusercontent.com/75875483/140722114-e367686a-7bbf-48cb-9846-dd371ad15da5.png)
![image](https://user-images.githubusercontent.com/75875483/140722142-e9f30f11-2119-4c1d-bfde-59a05a1277ea.png)
![image](https://user-images.githubusercontent.com/75875483/140722193-04839f54-237a-4030-bc9e-94dcbbf9b144.png)

PS. pixiv.cat改成.re好像没用
![image](https://user-images.githubusercontent.com/75875483/140722441-8b0a10f2-c5e7-4a54-8e97-ff4045c12cb7.png)
【这张截图的情况没有bot.proxy一行为空】

**Comment by Miuzarte** [comment]
> // 大部分请求所使用的代理，支持 http(s):// 和 socks://
>     "proxy": "https://ssrss.de/s/【数据删除】",
> 格式应该是这个吧？
> 
> bot.proxy填入上述内容后，机器人提示涩图服务器爆炸了
> 报错如下，
> ![image](https://user-images.githubusercontent.com/75875483/140722038-9ecb5b8d-198a-457d-860e-ff6e4a24f3b1.png)
> ![image](https://user-images.githubusercontent.com/75875483/140722114-e367686a-7bbf-48cb-9846-dd371ad15da5.png)
> ![image](https://user-images.githubusercontent.com/75875483/140722142-e9f30f11-2119-4c1d-bfde-59a05a1277ea.png)
> ![image](https://user-images.githubusercontent.com/75875483/140722193-04839f54-237a-4030-bc9e-94dcbbf9b144.png)
> 
> PS. pixiv.cat改成.re好像没用
> ![image](https://user-images.githubusercontent.com/75875483/140722441-8b0a10f2-c5e7-4a54-8e97-ff4045c12cb7.png)
> 【这张截图的情况没有bot.proxy一行为空】
> 
> 

你这怕不是获取配置文件的地址。。。

**Comment by DongGua-Jun** [comment]
> > // 大部分请求所使用的代理，支持 http(s):// 和 socks://
> > "proxy": "[https://ssrss.de/s/【数据删除】](https://ssrss.de/s/%E3%80%90%E6%95%B0%E6%8D%AE%E5%88%A0%E9%99%A4%E3%80%91)",
> > 格式应该是这个吧？
> > bot.proxy填入上述内容后，机器人提示涩图服务器爆炸了
> > 报错如下，
> > ![image](https://user-images.githubusercontent.com/75875483/140722038-9ecb5b8d-198a-457d-860e-ff6e4a24f3b1.png)
> > ![image](https://user-images.githubusercontent.com/75875483/140722114-e367686a-7bbf-48cb-9846-dd371ad15da5.png)
> > ![image](https://user-images.githubusercontent.com/75875483/140722142-e9f30f11-2119-4c1d-bfde-59a05a1277ea.png)
> > ![image](https://user-images.githubusercontent.com/75875483/140722193-04839f54-237a-4030-bc9e-94dcbbf9b144.png)
> > PS. pixiv.cat改成.re好像没用
> > ![image](https://user-images.githubusercontent.com/75875483/140722441-8b0a10f2-c5e7-4a54-8e97-ff4045c12cb7.png)
> > 【这张截图的情况没有bot.proxy一行为空】
> 
> 你这怕不是获取配置文件的地址。。。

坏耶，带佬给个sample看看吧（

**Comment by Miuzarte** [comment]
> > > // 大部分请求所使用的代理，支持 http(s):// 和 socks://
> > > "proxy": "[https://ssrss.de/s/【数据删除】](https://ssrss.de/s/%E3%80%90%E6%95%B0%E6%8D%AE%E5%88%A0%E9%99%A4%E3%80%91)",
> > > 格式应该是这个吧？
> > > bot.proxy填入上述内容后，机器人提示涩图服务器爆炸了
> > > 报错如下，
> > > ![image](https://user-images.githubusercontent.com/75875483/140722038-9ecb5b8d-198a-457d-860e-ff6e4a24f3b1.png)
> > > ![image](https://user-images.githubusercontent.com/75875483/140722114-e367686a-7bbf-48cb-9846-dd371ad15da5.png)
> > > ![image](https://user-images.githubusercontent.com/75875483/140722142-e9f30f11-2119-4c1d-bfde-59a05a1277ea.png)
> > > ![image](https://user-images.githubusercontent.com/75875483/140722193-04839f54-237a-4030-bc9e-94dcbbf9b144.png)
> > > PS. pixiv.cat改成.re好像没用
> > > ![image](https://user-images.githubusercontent.com/75875483/140722441-8b0a10f2-c5e7-4a54-8e97-ff4045c12cb7.png)
> > > 【这张截图的情况没有bot.proxy一行为空】
> > 
> > 你这怕不是获取配置文件的地址。。。
> 
> 坏耶，带佬给个sample看看吧（

Windows上开一个v2ray，这里填http://127.0.0.1:[v2ray右下角显示的端口]/

比如我挂了个clash，它的本地http端口是7890
```
    // 大部分请求所使用的代理，支持 http(s):// 和 socks://
    "proxy": "http://127.0.0.1:7890",
```

**Comment by Tsuk1ko** [comment]
你这个改的只是显示的原图链接

还有兄啊你这个 proxy 不太对劲，你确定你理解了这个是怎么用的么

**Comment by Miuzarte** [comment]
> > > // 大部分请求所使用的代理，支持 http(s):// 和 socks://
> > > "proxy": "[https://ssrss.de/s/【数据删除】](https://ssrss.de/s/%E3%80%90%E6%95%B0%E6%8D%AE%E5%88%A0%E9%99%A4%E3%80%91)",
> > > 格式应该是这个吧？
> > > bot.proxy填入上述内容后，机器人提示涩图服务器爆炸了
> > > 报错如下，
> > > ![image](https://user-images.githubusercontent.com/75875483/140722038-9ecb5b8d-198a-457d-860e-ff6e4a24f3b1.png)
> > > ![image](https://user-images.githubusercontent.com/75875483/140722114-e367686a-7bbf-48cb-9846-dd371ad15da5.png)
> > > ![image](https://user-images.githubusercontent.com/75875483/140722142-e9f30f11-2119-4c1d-bfde-59a05a1277ea.png)
> > > ![image](https://user-images.githubusercontent.com/75875483/140722193-04839f54-237a-4030-bc9e-94dcbbf9b144.png)
> > > PS. pixiv.cat改成.re好像没用
> > > ![image](https://user-images.githubusercontent.com/75875483/140722441-8b0a10f2-c5e7-4a54-8e97-ff4045c12cb7.png)
> > > 【这张截图的情况没有bot.proxy一行为空】
> > 
> > 你这怕不是获取配置文件的地址。。。
> 
> 坏耶，带佬给个sample看看吧（

具体用ss/ssr/v2r取决于你的梯子

**Comment by DongGua-Jun** [comment]
> 你这个改的只是显示的原图链接
> 
> 还有兄啊你这个 proxy 不太对劲，你确定你理解了这个是怎么用的么

坏耶，我又完全会了（
![image](https://user-images.githubusercontent.com/75875483/140724340-8d058e58-69bd-44b3-a947-489aad2c0cd2.png)

**Comment by DongGua-Jun** [comment]
> > > > // 大部分请求所使用的代理，支持 http(s):// 和 socks://
> > > > "proxy": "[https://ssrss.de/s/【数据删除】](https://ssrss.de/s/%E3%80%90%E6%95%B0%E6%8D%AE%E5%88%A0%E9%99%A4%E3%80%91)",
> > > > 格式应该是这个吧？
> > > > bot.proxy填入上述内容后，机器人提示涩图服务器爆炸了
> > > > 报错如下，
> > > > ![image](https://user-images.githubusercontent.com/75875483/140722038-9ecb5b8d-198a-457d-860e-ff6e4a24f3b1.png)
> > > > ![image](https://user-images.githubusercontent.com/75875483/140722114-e367686a-7bbf-48cb-9846-dd371ad15da5.png)
> > > > ![image](https://user-images.githubusercontent.com/75875483/140722142-e9f30f11-2119-4c1d-bfde-59a05a1277ea.png)
> > > > ![image](https://user-images.githubusercontent.com/75875483/140722193-04839f54-237a-4030-bc9e-94dcbbf9b144.png)
> > > > PS. pixiv.cat改成.re好像没用
> > > > ![image](https://user-images.githubusercontent.com/75875483/140722441-8b0a10f2-c5e7-4a54-8e97-ff4045c12cb7.png)
> > > > 【这张截图的情况没有bot.proxy一行为空】
> > > 
> > > 
> > > 你这怕不是获取配置文件的地址。。。
> > 
> > 
> > 坏耶，带佬给个sample看看吧（
> 
> 具体用ss/ssr/v2r取决于你的梯子

兄啊，你是这个👍
