### ISSUE TITLE
为更多不同的群和人划分不同的配置文件

### ISSUE THREAD

**Issue by citydirector** [Tsuk1ko/cq-picsearcher-bot#254]
方案一是在config.json配置文件中以QQ号为名称，参数为数组的方式配置多个不同人/qq群的相关配置，主要包括setu模块的相关配置，比如“setu冷却时间”、“是否允许使用setu功能”等等；
方案二是把相关配置独立出来，单独建一个文件夹存放“<QQ号>.json”文件，轮询文件夹内的配置文件并存入数据库，实现不同人/qq群使用时读取对应配置文件；
最后无论是哪种方案，针对没有被配置的QQ号使用一个默认配置文件或者“无响应”。

**Comment by Miuzarte** [comment]
这是拿去卖钱分了好几个vip等级么要分这么细（

**Comment by citydirector** [comment]
> 这是拿去卖钱分了好几个vip等级么要分这么细（

希望你只是开个玩笑（

想法的需求来自于多个QQ群

**Comment by Tsuk1ko** [comment]
对于目前的架构这样的改动代价太大了，暂不考虑

**Comment by Miuzarte** [comment]
> > 这是拿去卖钱分了好几个vip等级么要分这么细（
> 
> 希望这只是开个玩笑。
> 
> 想法的需求来自于多个QQ群的管理员，部分群有不同需求；比如某些群有未成年，管理员更希望屏蔽r18的关键词，以及某些人数较多的活跃的群容易刷屏，所以需要较长的冷却cd等

这种事见过太多了，冒犯到了的话很抱歉

**Comment by citydirector** [comment]
> 对于目前的架构这样的改动代价太大了，暂不考虑

好吧，确实有点遗憾 :-D
