### ISSUE TITLE
ascii2d与nhentai无法搜索

### ISSUE THREAD

**Issue by DaBoSAMA** [Tsuk1ko/cq-picsearcher-bot#264]
如题，本人使用的是无代理阿里云服务器，在搜图的时候无法使用ascii2d与nhentai搜索，使用ascii2d搜索时会秒回复“ascii2d 搜索失败
limit over”，error.log报错如下：
```
PM [error] ascii2d
Error: Request failed with status code 404
    at createError (/root/cq-picsearcher-bot-master/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/cq-picsearcher-bot-master/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/root/cq-picsearcher-bot-master/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
{
  "message": "Request failed with status code 404",
  "config": {}
}

```
使用nhentai会回复“貌似没有在 nhentai 找到对应的本子 _(:3」∠)_”，error.log报错如下：
```
PM [error] nhentai
Error: connect ETIMEDOUT 202.160.130.7:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
{ 
  "message": "connect ETIMEDOUT 202.160.130.7:443",
  "code": "ETIMEDOUT",
  "config": {}
}
```
请问此问题该怎么解决(Ｔ▽Ｔ)

**Comment by Tsuk1ko** [comment]
代理，请

配置在 `bot.proxy`

**Comment by Miuzarte** [comment]
a2d都被墙了么（

**Comment by DaBoSAMA** [comment]
> a2d都被墙了么（

正是因为a2d没被墙所以我对出现404很疑惑

**Comment by Tsuk1ko** [comment]
这就不太清楚了

**Comment by DaBoSAMA** [comment]
> 这就不太清楚了，反正 nhentai 肯定是墙了（

那我猜修改代理应该也没有用了，而且我朋友也在同样的阿里云服务器上部署的无代理也可以使用a2d，而我部署的从来都不能用（难道是我糊里糊涂整的index有问题？我现在也不能在线更新）

**Comment by Miuzarte** [comment]
> > 这就不太清楚了，反正 nhentai 肯定是墙了（
> 
> 那我猜修改代理应该也没有用了，而且我朋友也在同样的阿里云服务器上部署的无代理也可以使用a2d，而我部署的从来都不能用（难道是我糊里糊涂整的index有问题？我现在也不能在线更新）

你这阿里云北京的还是上海的

**Comment by DaBoSAMA** [comment]
> > > 这就不太清楚了，反正 nhentai 肯定是墙了（
> > 
> > 
> > 那我猜修改代理应该也没有用了，而且我朋友也在同样的阿里云服务器上部署的无代理也可以使用a2d，而我部署的从来都不能用（难道是我糊里糊涂整的index有问题？我现在也不能在线更新）
> 
> 你这阿里云北京的还是上海的

北京的

**Comment by Miuzarte** [comment]
> > > > 这就不太清楚了，反正 nhentai 肯定是墙了（
> > > 
> > > 
> > > 那我猜修改代理应该也没有用了，而且我朋友也在同样的阿里云服务器上部署的无代理也可以使用a2d，而我部署的从来都不能用（难道是我糊里糊涂整的index有问题？我现在也不能在线更新）
> > 
> > 你这阿里云北京的还是上海的
> 
> 北京的

那估计地区原因了，上海的是没墙

**Comment by DaBoSAMA** [comment]
> > > > > 这就不太清楚了，反正 nhentai 肯定是墙了（
> > > > 
> > > > 
> > > > 那我猜修改代理应该也没有用了，而且我朋友也在同样的阿里云服务器上部署的无代理也可以使用a2d，而我部署的从来都不能用（难道是我糊里糊涂整的index有问题？我现在也不能在线更新）
> > > 
> > > 
> > > 你这阿里云北京的还是上海的
> > 
> > 
> > 北京的
> 
> 那估计地区原因了，上海的是没墙

尝试curl了a2d，返回limit over，估计是阿里云ban掉了，寄
