### ISSUE TITLE
搜索本子感觉不是很灵敏

### ISSUE THREAD

**Issue by Annabel0530** [Tsuk1ko/cq-picsearcher-bot#268]
搜出来的本子都回复了“貌似没有在 nhentai 找到对应的本子”
但是自己去nhentai搜索却是可以搜出来的

**Comment by Tsuk1ko** [comment]
麻烦提供一下本子名

**Comment by Annabel0530** [comment]
[Croriin]  教えて!異世界性文化  (異世快楽天 Vol.2) 中文翻譯
![6{FQ8LIL}{3~QXRZNQZ6L2J](https://user-images.githubusercontent.com/40524485/144964890-9f284d01-d21c-4242-8839-af6ebc6cc839.png)
![1P2{~`YP1SA7VJC%IIY1RWN](https://user-images.githubusercontent.com/40524485/144965031-fb26d6ab-536c-4070-9529-e2d8ad430005.png)

不止这本 基本搜过的都是这样 印象中没有哪本给出链接的（可能是我搜的本子的问题

**Comment by Tsuk1ko** [comment]
巧了，今天刚搜过这本，而且是正常的……

![image](https://user-images.githubusercontent.com/24877906/144965702-6884af0c-cbe1-4ea2-b53f-9326cbd24007.png)

你用的是最新版机器人吗

**Comment by Annabel0530** [comment]
已经好几个版本都是这种情况了 我现在是2.30.3  之前看更新内容不是必要就没更新  我现在更新试试

**Comment by Tsuk1ko** [comment]
那确实是最新版的，你看看错误日志，是不是网络问题导致的，是的话国内建议配置代理

**Comment by Annabel0530** [comment]
这样 了解了 谢谢🌹
