### ISSUE TITLE
从2.30.3更新 v2.31.0后 启动失败

### ISSUE THREAD

**Issue by 0769559** [Tsuk1ko/cq-picsearcher-bot#278]
更新途中就出了问题 之后问题就如下文显示

3. 运行环境
   - 系统，是 win 还是 linux，系统版本是什么    Debian 10
   - node.js 版本                                                v14.16.1
   - go-cqhttp 版本                                  v1.0.0-beta7-fix2
   - cq-picsearcher-bot 版本2.30.3正常  v2.31.0就出现图里的问题了`package.json里显示的2.31.0

![image](https://user-images.githubusercontent.com/22361624/146567925-cf17a52d-99d3-48da-8a06-dba425a41c9b.png)

/root/cq-picsearcher-bot/logs/error.log last 15 lines:
0|cqps     | - /root/cq-picsearcher-bot/src/utils/image.js
0|cqps     | - /root/cq-picsearcher-bot/src/saucenao.js
0|cqps     | - /root/cq-picsearcher-bot/main.js
0|cqps     | - /root/cq-picsearcher-bot/index.js
0|cqps     |     at Object.<anonymous> (/root/cq-picsearcher-bot/src/utils/cache.js:1) {
0|cqps     |   code: 'MODULE_NOT_FOUND',
0|cqps     |   requireStack: [
0|cqps     |     '/root/cq-picsearcher-bot/src/utils/cache.js',
0|cqps     |     '/root/cq-picsearcher-bot/src/CQcode.js',
0|cqps     |     '/root/cq-picsearcher-bot/src/utils/image.js',
0|cqps     |     '/root/cq-picsearcher-bot/src/saucenao.js',
0|cqps     |     '/root/cq-picsearcher-bot/main.js',
0|cqps     |     '/root/cq-picsearcher-bot/index.js'
0|cqps     |   ]
0|cqps     | }

0|cqps  | /root/cq-picsearcher-bot/src/utils/cache.js:1
0|cqps  | Error: Cannot find module 'md5'
0|cqps  | Require stack:
0|cqps  | - /root/cq-picsearcher-bot/src/utils/cache.js
0|cqps  | - /root/cq-picsearcher-bot/src/CQcode.js
0|cqps  | - /root/cq-picsearcher-bot/src/utils/image.js
0|cqps  | - /root/cq-picsearcher-bot/src/saucenao.js
0|cqps  | - /root/cq-picsearcher-bot/main.js
0|cqps  | - /root/cq-picsearcher-bot/index.js
0|cqps  |     at Object.<anonymous> (/root/cq-picsearcher-bot/src/utils/cache.js:1) {
0|cqps  |   code: 'MODULE_NOT_FOUND',
0|cqps  |   requireStack: [
0|cqps  |     '/root/cq-picsearcher-bot/src/utils/cache.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/CQcode.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/utils/image.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/saucenao.js',
0|cqps  |     '/root/cq-picsearcher-bot/main.js',
0|cqps  |     '/root/cq-picsearcher-bot/index.js'
0|cqps  |   ]
0|cqps  | }
0|cqps  | /root/cq-picsearcher-bot/src/utils/cache.js:1
0|cqps  | Error: Cannot find module 'md5'
0|cqps  | Require stack:
0|cqps  | - /root/cq-picsearcher-bot/src/utils/cache.js
0|cqps  | - /root/cq-picsearcher-bot/src/CQcode.js
0|cqps  | - /root/cq-picsearcher-bot/src/utils/image.js
0|cqps  | - /root/cq-picsearcher-bot/src/saucenao.js
0|cqps  | - /root/cq-picsearcher-bot/main.js
0|cqps  | - /root/cq-picsearcher-bot/index.js
0|cqps  |     at Object.<anonymous> (/root/cq-picsearcher-bot/src/utils/cache.js:1) {
0|cqps  |   code: 'MODULE_NOT_FOUND',
0|cqps  |   requireStack: [
0|cqps  |     '/root/cq-picsearcher-bot/src/utils/cache.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/CQcode.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/utils/image.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/saucenao.js',
0|cqps  |     '/root/cq-picsearcher-bot/main.js',
0|cqps  |     '/root/cq-picsearcher-bot/index.js'
0|cqps  |   ]
0|cqps  | }
0|cqps  | /root/cq-picsearcher-bot/src/utils/cache.js:1
0|cqps  | Error: Cannot find module 'md5'
0|cqps  | Require stack:
0|cqps  | - /root/cq-picsearcher-bot/src/utils/cache.js
0|cqps  | - /root/cq-picsearcher-bot/src/CQcode.js
0|cqps  | - /root/cq-picsearcher-bot/src/utils/image.js
0|cqps  | - /root/cq-picsearcher-bot/src/saucenao.js
0|cqps  | - /root/cq-picsearcher-bot/main.js
0|cqps  | - /root/cq-picsearcher-bot/index.js
0|cqps  |     at Object.<anonymous> (/root/cq-picsearcher-bot/src/utils/cache.js:1) {
0|cqps  |   code: 'MODULE_NOT_FOUND',
0|cqps  |   requireStack: [
0|cqps  |     '/root/cq-picsearcher-bot/src/utils/cache.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/CQcode.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/utils/image.js',
0|cqps  |     '/root/cq-picsearcher-bot/src/saucenao.js',
0|cqps  |     '/root/cq-picsearcher-bot/main.js',
0|cqps  |     '/root/cq-picsearcher-bot/index.js'
0|cqps  |   ]
0|cqps  | }

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/146569818-fcd21a9c-7966-474a-84ea-c4d28f10f350.png)

**Comment by Tsuk1ko** [comment]
node 版本过低了，建议至少用 node 14

**Comment by 0769559** [comment]
确实是node 版本过低了 更新后成功安装依赖 谢谢
