### ISSUE TITLE
BUG：重复推送B站旧动态

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#281]
#280 
1. Bug 描述
   - 会重复推送旧动态
2. 截图、日志、配置
   - 放最后
3. 运行环境
   - Ubuntu 21.04 x86_64
   - node v14.18.1
   - go-cqhttp v1.0.0-beta8-fix2
   - cq-picsearcher-bot v2.31.1
#
一条为2021-12-28 11:57发布，一条为2021-12-31 15:30，都发布于更新2.31.1前
昨天正好碰上更新就立马更了，当天晚上开始重复推送旧动态
日志没东西
   - ![C~MK_BC2LU){XO Y $OI` L](https://user-images.githubusercontent.com/66856838/147879970-7d67bdc2-b3aa-484f-a642-4bb78e1e8418.png)

**Comment by Tsuk1ko** [comment]
有点麻，感觉是b站api反复横跳了
