### ISSUE TITLE
指令更新能否用cnpm或者走代理更新

### ISSUE THREAD

**Issue by xiaobaozi233** [Tsuk1ko/cq-picsearcher-bot#284]
希望指令更新能用cnpm或者走代理更新，国内服务器伤不起..

**Comment by Tsuk1ko** [comment]
按 wiki [部署流程](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%83%A8%E7%BD%B2%E6%B5%81%E7%A8%8B#3-%E9%83%A8%E7%BD%B2%E6%9C%AC%E9%A1%B9%E7%9B%AE) 里面设置淘宝镜像就相当于 cnpm 了

**Comment by xiaobaozi233** [comment]
我改改试试
