### ISSUE TITLE
建议近期不要使用 bot.pmSearchResultTemp 功能

### ISSUE THREAD

**Issue by MejiroRina** [Tsuk1ko/cq-picsearcher-bot#285]
刚刚无聊使用了一下这个功能，瞬间被tx风控下线
![Snipaste_2022-02-04_16-42-08](https://user-images.githubusercontent.com/70424266/152498692-474d3370-7e29-4ac5-a354-65069f47145a.png)

**Comment by Miuzarte** [comment]
看我的上线到冻结不够两分钟
![Screenshot_20220202-190050_MT管理器.png](https://user-images.githubusercontent.com/66856838/152503877-7f19fe6c-ce00-4209-b9fd-9d19be97e8a0.png)

**Comment by Tsuk1ko** [comment]
看起来是有这么回事，我一会发个版本加个注释提示吧

https://github.com/Mrs4s/go-cqhttp/issues/1338

**Comment by MejiroTeio** [comment]
> 看我的上线到冻结不够两分钟 ![Screenshot_20220202-190050_MT管理器.png](https://user-images.githubusercontent.com/66856838/152503877-7f19fe6c-ce00-4209-b9fd-9d19be97e8a0.png)

我是开了这个功能之后，让群友测试一下，群友发了消息之后我成功把消息临时私聊发出去了，然后我就瞬间被冻结账号
