### ISSUE TITLE
频道内容撤回异常

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#290]
1. Bug 描述
   - 是否稳定复现：是，要求一张色图就行，不会撤回，gocq内会有报错，cqps自己的log没变化
   - 期望的正常行为是怎么样的：到点就撤回
   - 补充：色图，涩图这俩词频道直接屏蔽了，我用的关键字是涩涩，供参考
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
   <img width="909" alt="image" src="https://user-images.githubusercontent.com/89308692/153718191-f6971e7c-18de-4942-a50c-8f79dafe9a8a.png">
   
   - 可能与 bug 有关的配置内容，如果不确定则不必提供：管理员tinyID那个不知道是啥没填
   - config.yml(gocq，免得拒传改成txt了）
[config.txt](https://github.com/Tsuk1ko/cq-picsearcher-bot/files/8053958/config.txt)

3. 运行环境
   - 系统，是 win：win10
   - node.js 版本:好问，记不清，16.x罢，看上去没啥关系
   - go-cqhttp 版本：1.0beta8fix2 更新：1.0rc1问题依旧
   - cq-picsearcher-bot 版本（查看 `package.json` 中的 `version` 字段，或向机器人发送 `--version`） 2.33.0

**Comment by Tsuk1ko** [comment]
应该是 go-cqhttp 目前尚未支持频道消息的撤回
