### ISSUE TITLE
频道的R18色图禁用选项

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#291]
请说明：

1. 加什么功能：如题
2. 理由
#290 & 既然频道连色图两字都不能发，AI审查传闻也是很厉害，能调整比较保险

**Comment by Tsuk1ko** [comment]
增加了配置项 `bot.setu.r18AllowInGuild`，默认 `false`

**Comment by A2Sumie** [comment]
> 增加了配置项 `bot.setu.r18AllowInGuild`，默认 `false`

更新了，没起效

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/153793059-d13c9874-61d3-4dac-b3cb-2d2e485ac1a4.png)
测试了没有问题
