### ISSUE TITLE
[BUG]--get-url没法用了

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#292]
![5e6e1113f5ece218.png](https://user-images.githubusercontent.com/66856838/154621655-5435587a-fb12-4d73-bee0-55b5e3fbf994.png)

**Comment by Miuzarte** [comment]
难不成是私聊没法用这个功能

**Comment by Tsuk1ko** [comment]
不是，这个确实是解析命令的一个 bug
