### ISSUE TITLE
ascii2d 搜索失败 write EPROTO 140578009024384:error:1416D044:SSL routines:tls_process_key_exchange:internal error:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2337:

### ISSUE THREAD

**Issue by Bearlele** [Tsuk1ko/cq-picsearcher-bot#297]
运行环境：Linux Debian 10 
node.js版本 v14.19.0
go-cqhttp 版本 v1.0.0-rc1
cq-picsearcher-bot 版本 2.33.5

ascii2d 搜索失败
write EPROTO 140578009024384:error:1416D044:SSL routines:tls_process_key_exchange:internal error:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2337:

试过重新部署cq-picsearcher-bot

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#ascii2d

**Comment by Bearlele** [comment]
谢谢 我一直在找常见问题但是没找着qwq

**Comment by Bearlele** [comment]
请问bot.cfTLSVersion这个配置在哪...

**Comment by Tsuk1ko** [comment]
就是配置文件 config.jsonc 里面，bot 里面有个 cfTLSVersion 项

**Comment by Bearlele** [comment]
找着了，原来是我配置太久没有这个选项

**Comment by Tsuk1ko** [comment]
可以启用 autoUpdateConfig
