### ISSUE TITLE
setu功能只发图片不发链接

### ISSUE THREAD

**Issue by Bearlele** [Tsuk1ko/cq-picsearcher-bot#302]
setu功能直接发图片 取消发链接
群友没有梯子qwq感觉有点多余

**Comment by Miuzarte** [comment]
![Screenshot_20220308-164111_1DM+.png](https://user-images.githubusercontent.com/66856838/157199684-e61744a8-1721-4da0-a5e7-bfdd5bbf5d29.png)

**Comment by Tsuk1ko** [comment]
默认是会发反代原图链接的，不用梯子，不想看链接也行，回头加个设置

**Comment by Bearlele** [comment]
回头加个设置叭 麻烦啦
