### ISSUE TITLE
可否添加一个开关

### ISSUE THREAD

**Issue by Annabel0530** [Tsuk1ko/cq-picsearcher-bot#303]
如果BOT私聊收到的消息不是指令或图片和其它相关的东西，BOT就不回复 “必须要发送图片……”
因为个人需要  开了几个BOT是同一个号 每次使用其它BOT的功能都会触发回复

**Comment by Tsuk1ko** [comment]
把配置 `bot.replys.default` 设置为空字符串即可

**Comment by Annabel0530** [comment]
原来这样就行  谢谢解答
