### ISSUE TITLE
saucenao现在似乎需要充值才能搜索图片

### ISSUE THREAD

**Issue by Lixuhuilll** [Tsuk1ko/cq-picsearcher-bot#308]
saucenao现在似乎需要充值才能搜索图片。
希望加入saucenao的替代。

**Comment by Tsuk1ko** [comment]
并没有？我用的很正常

你需要创建一个账户获取 apikey，含有一定免费额度

**Comment by Lixuhuilll** [comment]
> 并没有？我用的很正常
> 
> 你需要创建一个账户获取 apikey，含有一定免费额度
你看看，信息搜索需要充值
![image](https://user-images.githubusercontent.com/88485037/167997080-a76f0f54-d53e-44fa-8f6f-64684d03eb57.png)
