### ISSUE TITLE
未知的动态类型 type=4200

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#314]
![image](https://user-images.githubusercontent.com/66856838/169648541-1017b5cb-0183-4a9f-a519-cc5941659ce9.png)
没有日志
![image](https://user-images.githubusercontent.com/66856838/169648632-484eb04e-cb6e-4a1e-a634-23e5a6a1e6a6.png)

**Comment by Tsuk1ko** [comment]
下面这个动态的链接发一下

**Comment by Miuzarte** [comment]
> 下面这个动态的链接发一下

https://t.bilibili.com/609984479584464679

**Comment by Tsuk1ko** [comment]
支持了
