### ISSUE TITLE
又有新的短链了

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#316]
https://b23.tv/CJYyvCC
https://t.bilibili.com/665298921052962821
![image](https://user-images.githubusercontent.com/66856838/170827623-0850fd98-5527-446f-801b-17479a7e0426.png)

**Comment by Tsuk1ko** [comment]
知道原因了，我请求短链的时候用的是 http，现在B站的短链会把 http 重定向到短链接的 https，而不是直接重定向到原链接，导致没获取到原链接，所有的短链都会解析不出
