### ISSUE TITLE
似乎 setu.limit 以及 setu.cd 对 bot.admin 也生效了

### ISSUE THREAD

**Issue by longmeidao** [Tsuk1ko/cq-picsearcher-bot#318]
不是搜图功能的 `bot.searchLimit` 而是 setu 功能的 `setu.limit` 和 `setu.cd`.

**Comment by Tsuk1ko** [comment]
确实，不过考虑到 setu 的特殊性，我的想法是只对 `bot.admin` 的私聊不做限制，在群里依然需要遵守通用及黑白名单的设置

**Comment by longmeidao** [comment]
私聊不做限制吗？似乎私聊也出现了限制的情况欸。

**Comment by Tsuk1ko** [comment]
已经在最新 commit 里取消了私聊限制，更新即可
