### ISSUE TITLE
希望私聊的时候a2d搜图结果也能合并转发

### ISSUE THREAD

**Issue by SEAFHMC** [Tsuk1ko/cq-picsearcher-bot#326]
现在go-cqhttp的rc2版本支持私聊发送合并转发消息了，所以希望私聊的时候a2d搜图结果也能合并转发。

**Comment by Tsuk1ko** [comment]
悲报：go-cqhttp 的私聊合并转发存在许多 bug，这个功能会先加上，但不建议启用

已经向 go-cqhttp 提了 issue，等他们修复后再使用

**Comment by Tsuk1ko** [comment]
go-cqhttp 已在 dev 版本修复

https://github.com/Mrs4s/go-cqhttp/actions/runs/2560822635
