### ISSUE TITLE
saucenao 搜图结果过滤 NSFW

### ISSUE THREAD

**Issue by NekoAria** [Tsuk1ko/cq-picsearcher-bot#329]
1. saucenao 实际上有个 NSFW 过滤功能，只需要在请求参数里增加一个参数 `hide` ，然后在返回的结果里有个 `hidden` 为判断结果。具体可以看[官网](https://saucenao.com/user.php?page=search-api)。
2. 我自己维护并使用的 nonebot 搜图插件收到一个关于这个的 [issue](https://github.com/NekoAria/YetAnotherPicSearch/issues/9) ，才注意到有这么个参数。

**Comment by Tsuk1ko** [comment]
这个好，感谢告知
