### ISSUE TITLE
某些情况下，缓存功能出错

### ISSUE THREAD

**Issue by G41mywaifu** [Tsuk1ko/cq-picsearcher-bot#334]
环境为win 版本为2.34.8  
私聊时，先发一张SauceNAO找不到的图，在较长时间后搜索其他图，会把上一次的搜图缓存一起发送。  
![图片](https://user-images.githubusercontent.com/81564864/177023666-e69e1105-2a60-415f-87c8-383db7e63989.png)
![图片](https://user-images.githubusercontent.com/81564864/177023674-fd080f02-be01-4ab6-ae5a-eff27e0f1781.png)

**Comment by Tsuk1ko** [comment]
未能复现

**Comment by G41mywaifu** [comment]
我现在也没法复现了，但确实偶尔不止一次出现这种情况

**Comment by Miuzarte** [comment]
你看gocq的日志，应该会发现原因是再次接受到了上一张图，似乎是gocq的bug
很久以前就有了[go-cqhttp/issues/1049](https://github.com/Mrs4s/go-cqhttp/issues/1049)

**Comment by Tsuk1ko** [comment]
更新下 go-cqhttp 版本？

**Comment by G41mywaifu** [comment]
好  我试一下
