### ISSUE TITLE
能否多加个本子搜图的途径

### ISSUE THREAD

**Issue by 0769559** [Tsuk1ko/cq-picsearcher-bot#337]
1、不知道能不能多加个搜图的途径https://soutubot.moe/
2、基于特征点匹配的的局部图像搜索工具
https://github.com/lolishinshi/imsearch

不知道这难不难实现 单纯提个建议

**Comment by Tsuk1ko** [comment]
很遗憾，没办法集成这个工具

1. 网站使用严格的 cf 5秒盾，要弄的话得上无头浏览器，个人认为不值得
2. 开源项目为搜索算法，需要索引才能运作，并不是直接拿来部署就能用的

**Comment by ShellyMon** [comment]
使用flaresolverr可以过cf 5秒盾，请求拿到cookic就可以访问

**Comment by ShellyMon** [comment]
@Tsuk1ko 目前已经实现了
