### ISSUE TITLE
图片上传失败：image type error: application/octet-stream

### ISSUE THREAD

**Issue by ZZCBYH** [Tsuk1ko/cq-picsearcher-bot#342]
系统版本 :Windows Server 2019 Datacenter
node.js 版本:node-v16.16.0-win-x64
go-cqhttp 版本:v1.0.0-rc3
cq-picsearcher-bot 版本:2.37.2

目前稳定复现，重新部署和重启环境都无效。

go-cqhttp的日志如下:

![image](https://user-images.githubusercontent.com/56617932/179891159-c935c35f-af2c-42ec-94a1-049e28d5dd6d.png)

与机器人的聊天记录如下：
![image](https://user-images.githubusercontent.com/56617932/179891279-7d1a76a2-2464-45c7-a822-8a12f6c017fe.png)

**Comment by ZZCBYH** [comment]
cq-picsearcher-bot 版本:2.37.2

**Comment by ZZCBYH** [comment]
通过设置 "pximgProxy": "https://i.pixiv.re/" 解决了。

**Comment by jxtyq69** [comment]
感谢指点！

关联go-cqhttp这个issues: https://github.com/Mrs4s/go-cqhttp/issues/1660

**Comment by Tsuk1ko** [comment]
项目内发送图片是使用的 file 字段，这个没有问题
