### ISSUE TITLE
搜图模式的正则无法匹配斜杠，语言库的正常

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#344]
![image](https://user-images.githubusercontent.com/66856838/180125771-c4c31ffd-c5c9-4070-bd31-6f8cdb24ffbe.png)
![image](https://user-images.githubusercontent.com/66856838/180125899-faa48b2a-3c1d-4136-ac98-df66b87cc067.png)
![image](https://user-images.githubusercontent.com/66856838/180125860-59a4eab7-b4e5-4d10-a4fd-877eee4c3f22.png)
![image](https://user-images.githubusercontent.com/66856838/180125992-f9b96059-5e3b-4d9e-9584-48aaf648465b.png)
没有报错
![image](https://user-images.githubusercontent.com/66856838/180126017-50f8a037-51e1-482a-a45d-c09857a69204.png)

**Comment by Tsuk1ko** [comment]
因为你自己写了一个不带斜杠的匹配

![image](https://user-images.githubusercontent.com/24877906/180126744-312de003-9574-4429-b7bc-08dcadba643a.png)

另外，这是字符串形式的正则表达式，斜杠可以不用转义

另另外，json 中如果你要输反斜杠应当 `\\`，你这里写的 `\/` parse 之后仍然是 `/`，虽然结果上由于上一条所述所以并没有产生错误

**Comment by Miuzarte** [comment]
> 因为你自己写了一个不带斜杠的匹配
> 
> ![image](https://user-images.githubusercontent.com/24877906/180126744-312de003-9574-4429-b7bc-08dcadba643a.png)

就是写了个不带斜杠的匹配才有
![image](https://user-images.githubusercontent.com/66856838/180125992-f9b96059-5e3b-4d9e-9584-48aaf648465b.png)

**Comment by Tsuk1ko** [comment]
哦看错了，我看看

**Comment by Tsuk1ko** [comment]
想起来了，以前为了兼容其他机器人，指令会忽略 `/` 或 `<` 开头，我出个配置自定义好了
