### ISSUE TITLE
[BUG] 回复失效图片带上@和--get-url的时候机器人会重新连接

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#348]
```
2022/8/8 18:57:31 配置已重载
2022/8/8 18:57:31 收到私聊消息 qq=主人qq
--reload
2022/8/8 18:58:08 收到群组消息 group=group qq=主人qq
[CQ:reply,id=-1827545864][CQ:at,qq=主人qq] [CQ:at,qq=BOTqq] --get-url
2022/8/8 18:58:13 连接中[/api]#1
2022/8/8 18:58:13 连接成功[/api]#1
```
![YEAN$H8E6H${_393ET7FY97](https://user-images.githubusercontent.com/66856838/183403570-ba26e8a5-cd9f-4840-a7df-3360e91505e2.png)

**Comment by Miuzarte** [comment]
很怪  只有这个群会导致重启，别的不会
![image](https://user-images.githubusercontent.com/66856838/183403993-c1113394-72de-47f6-a0c6-290da3ff67e9.png)

**Comment by Miuzarte** [comment]
确实是跟图裂了有关，这个群重发再回复就好了

**Comment by Tsuk1ko** [comment]
有错误日志么

**Comment by Tsuk1ko** [comment]
暂时看不出是哪里导致的崩溃，等我遇到一个裂图再说吧（

顺带问下回复搜图会不会触发重启

**Comment by Miuzarte** [comment]
> 暂时看不出是哪里导致的崩溃，等我遇到一个裂图再说吧（
> 
> 顺带问下回复搜图会不会触发重启

试了purge a2d 只带@

都会
