### ISSUE TITLE
对搜图结果引入定时撤回和无预览+有预览的两次发送

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#355]
对搜图结果引入可选的定时撤回功能
同时返回一个有预览图和无预览图的聊天记录

Sau有相似度和NSFW标定，那没什么要管的。就算搜出来NSFW，精度够高那让搜的自己点就是
Ascii2d比较混沌，那么同时返回一个没有预览图和有预览图的聊天记录，有预览图的100（可选）秒后撤回，缓存同理

如果发两次比较麻烦的话

有Ascii2d结果（或者所有聊天记录形）的定时撤回，缓存结果也是定时撤回，部署人和使用人设法沟通一下更改

理由：封号大量发生中
但是再引入一个色值检查啥的那显然太麻烦了

**Comment by Tsuk1ko** [comment]
感觉有点麻烦……

不如就直接一刀切 `bot.hideImg` 设置成 `false`

**Comment by Miuzarte** [comment]
用合并转发发送结果就没事了，我就没封过（

**Comment by A2Sumie** [comment]
> 感觉有点麻烦……
> 
> 不如就直接一刀切 `bot.hideImg` 设置成 `true`

有人问我为啥没预览了才来发请求的，虽然也不是不行吧

**Comment by Tsuk1ko** [comment]
可以对预览图启用反和谐 `bot.antiShielding`，旋转+轻微修改

旋转的小图应该很难被认定为色图

**Comment by A2Sumie** [comment]
> 可以对预览图启用反和谐 `bot.antiShielding`，旋转+轻微修改
> 
> 旋转的小图应该很难被认定为色图

我bot早上刚放出来，更新的设置尽量都开了，那我再观察吧

**Comment by Miuzarte** [comment]
另外听说撤回是有更严格的二次审查的

**Comment by A2Sumie** [comment]
> 用合并转发发送结果就没事了，我就没封过（

开着，都是和搜图的一起封，最近几次了吧（
不过搜图防和谐刚加进来其实可以观察下

> 另外听说撤回是有更严格的二次审查的

我不知道，感觉上，没因为setu那块被封，我定时撤回是打开的

**Comment by Tsuk1ko** [comment]
（感觉一般都是因为 setu 被封

但是为了给群友持续提供 setu 我两个小号 ban 了一个就开另一个
