### ISSUE TITLE
[BUG] B站直播推送的链接带有奇怪的后缀(参数?)

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#358]
![image](https://user-images.githubusercontent.com/66856838/189344991-7c22d200-1230-4cc6-9fc5-dc5dfe2c48b1.png)
![image](https://user-images.githubusercontent.com/66856838/189345016-68e6d173-a9fe-4fe7-9dec-2374dcbc4ba4.png)

**Comment by Tsuk1ko** [comment]
这个参数也就是起追踪作用，不影响，不能访问可能是你的问题（

下个版本我过滤下

**Comment by Miuzarte** [comment]
> 

还真是，现在又能访问了
