### ISSUE TITLE
干员标签识别添加形近字替换

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#359]
![Screenshot_20220910-110055_QQ.png](https://user-images.githubusercontent.com/66856838/189466276-0556ce35-b449-4695-89d6-73a8829528c6.png)
![2ff44e47ebf68be8.png](https://user-images.githubusercontent.com/66856838/189466270-485c8d35-ca87-40ca-987b-8812de3caead.png)

**Comment by Tsuk1ko** [comment]
有没有原图，我做点测试

**Comment by Miuzarte** [comment]
> 有没有原图，我做点测试

![Screenshot_20220910-105807_明日方舟.png](https://user-images.githubusercontent.com/66856838/189468272-367ad13e-4ea8-4ff3-a1f7-6ab135953a26.png)
