### ISSUE TITLE
ascii2d 搜索失败

### ISSUE THREAD

**Issue by Bearlele** [Tsuk1ko/cq-picsearcher-bot#368]
0|cqps     | 10/22/2022, 9:10:33 AM [error] ascii2d
0|cqps     | Error
0|cqps     |     at /xxxx/cq-picsearcher-bot/src/ascii2d.js:31:15
0|cqps     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|cqps     |     at async retryAsync (/xxxx/cq-picsearcher-bot/src/utils/retry.js:11:14)
0|cqps     |     at async doSearch (/xxxx/cq-picsearcher-bot/src/ascii2d.js:25:37)
0|cqps     |     at async searchImg (/xxxx/cq-picsearcher-bot/main.js:574:54)

系统版本 Debian11
node版本 v16.17.1
cq-picsearcher-bot版本 2.39.6
已按照wiki的方法修改过无效，搜图的时候100%复现，麻烦帮忙看看是怎么回事qwq

**Comment by Shiyue00** [comment]
我和你一样的情况，从第一次部署好之后就是这个样子。。

**Comment by Bearlele** [comment]
更新后错误变了
0|cqps  | [error] ascii2d url: https://ascii2d.net/
0|cqps  | ¶þ´ÎÔª»­Ïñ???Ë÷
0|cqps  | Ä¿´Î
0|cqps  | ?Ã÷
0|cqps  | ×î½ü¤Î?Ë÷
0|cqps  | ¥é¥ó¥­¥ó¥°
0|cqps  | ¥Ä?¥ë
0|cqps  | Chrome??
0|cqps  | Firefox??
0|cqps  | Edge??
0|cqps  | ??ÏÈ
0|cqps  | ¤·¤¿¤é¤Ð?Ê¾°å
0|cqps  | twitter
0|cqps  | [email?protected]
0|cqps  | ¶þ´ÎÔª»­Ïñ???Ë÷
0|cqps  | ¥¤¥ó¥¿?¥Í¥Ã¥È¤Ë»­Ïñ¤¬¤¢¤ë?ºÏ
0|cqps  | ?Ë÷
0|cqps  | »­Ïñ¥Õ¥¡¥¤¥ë¤ò³Ö¤Ã¤Æ¤¤¤ë?ºÏ
0|cqps  | ?Ë÷
0|cqps  | (function(){var js = "window['__CF$cv$params']={r:'773e1b522c5a4c6b',m:'e2jHnpnDA5_hGCXQIrgAHg9zunXnp509dYquEFImsFw-1670089429-0-AQai4C1pMeSIS/xrrh5il/9zoCCaUmGoT63emwt/YkhYPzSuUQUwJZ4FNyTTdB/tFUWuqPtdFlVP0KnxkpMVn6RNWwFqv+hAE05fYPrCgr2+ecc5K9bcASvkiQLMw+81bQ==',s:[0x8c6a7947c8,0xa85a9b2fa8],u:'/cdn-cgi/challenge-platform/h/g'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();
0|cqps  | 12/3/2022, 5:43:49 PM [error] ascii2d
0|cqps  | Error
0|cqps  |     at /root/cq-picsearcher-bot/src/ascii2d.js:33:15
0|cqps  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|cqps  |     at async retryAsync (/root/cq-picsearcher-bot/src/utils/retry.js:11:14)
0|cqps  |     at async doSearch (/root/cq-picsearcher-bot/src/ascii2d.js:25:37)
0|cqps  |     at async searchImg (/root/cq-picsearcher-bot/main.js:580:54)

**Comment by Tsuk1ko** [comment]
新版本已经提供了使用 Puppeteer 绕过 cf challenge 的方法，详见 [wiki](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E#%E4%BD%BF%E7%94%A8-puppeteer-%E7%BB%95%E8%BF%87-cf-js-challenge)

新版本变动较大，更新方法见 [CHANGELOG](https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/master/CHANGELOG.md#12-11-v300)
