### ISSUE TITLE
bilibili合集推送出现问题

### ISSUE THREAD

**Issue by Darkatse** [Tsuk1ko/cq-picsearcher-bot#373]
1. Bug 描述
   - 是否稳定复现，是的话说明步骤
   稳定复现，订阅[该合集](https://space.bilibili.com/1773346/channel/seriesdetail?sid=449853)内容时无法正常处理
   - 期望的正常行为是怎么样的
   期望合集订阅和推送正常进行
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
配置文件：
```
      "push": {
        "1773346": [ //莴苣
          {
            "gid": xxxxxx,
            "seasons": [
              449853,
              449849
            ]
          }
        ]
      },
```
问题日志：
```
0|cqps  | 11/13/2022, 2:38:39 AM [error] bilibili get user season new videos info 1773346:449853
0|cqps  | TypeError: Cannot destructure property 'aids' of 'data.data' as it is undefined.
0|cqps  |     at getUserSeasonNewVideosInfo (/xxxx/cq-picsearcher-bot/src/plugin/bilibili/season.js:18:13)
0|cqps  |     at runMicrotasks (<anonymous>)
0|cqps  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|cqps  |     at async /xxxx/cq-picsearcher-bot/src/plugin/bilibili/push.js:147:25
0|cqps  |     at async Promise.all (index 0)
0|cqps  |     at async checkSeason (/xxxx/cq-picsearcher-bot/src/plugin/bilibili/push.js:145:3)
0|cqps  |     at async Promise.all (index 2)
0|cqps  |     at async Timeout.checkPush [as _onTimeout] (/xxxx/cq-picsearcher-bot/src/plugin/bilibili/push.js:65:5)
```

反查代码发现请求的api是  
https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/1dba3b8631efc43912d29eec5bb6582d805d8451/src/plugin/bilibili/season.js#L14-L17
填入uid:sid后发现[对应的页面](https://api.bilibili.com/x/polymer/space/seasons_archives_list?mid=1773346&season_id=449853&sort_reverse=false&page_num=1&page_size=30)是404  
```
{"code":-404,"message":"啥都木有","ttl":1}
```
4. 运行环境
   - 系统，linux Ubuntu 20.04
   - node.js 版本 v16.14.0
   - go-cqhttp 版本 1.0.0-rc3
   - cq-picsearcher-bot 版本 2.40.2

**Comment by Tsuk1ko** [comment]
噢，因为这种属于视频列表，不是合集，是两种东西

稍后我增加订阅视频列表的功能

**Comment by Tsuk1ko** [comment]
已经支持推送视频列表更新，配置及区分合集和列表的方法见 wiki

https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E6%8E%A8%E9%80%81

**Comment by Darkatse** [comment]
非常感谢！
