### ISSUE TITLE
多个chatgpt配置

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#387]
请说明：

1. 加什么功能
几个chatgpt配置，不同的触发词触发不同的配置
2. 理由
GPT3非常脱线还要钱，CODEX模型暂时不要钱还多少有点生产性，但可能的话还是想都用着吧

**Comment by Tsuk1ko** [comment]
功能实装了，详情见 wiki

https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#%E9%80%89%E9%A1%B9%E8%A6%86%E7%9B%96
