### ISSUE TITLE
使用ascii2d搜图时出现错误

### ISSUE THREAD

**Issue by tkosf** [Tsuk1ko/cq-picsearcher-bot#388]
ascii2d 搜索失败
write EPROTO C017960FBE7F0000:error:0A0C0103:SSL routines:tls_process_key_exchange:internal error:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2262:

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#ascii2d
