### ISSUE TITLE
搜图模式下没有收到图片的提示

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#393]
请说明：

1. 加什么功能 搜图模式中，距离开始指定时间后没有收到图片时，发送一个自定义回复
2. 理由 群友总能找到些被TX标记并吞掉的色图，等CD走完不如中间提示下让他们可以打个码直接再发

**Comment by Miuzarte** [comment]
我有点好奇你的超时时间设置的是多少
![image](https://user-images.githubusercontent.com/66856838/220857442-92f7abc2-5ef8-4cc7-805e-421960ef0580.png)

**Comment by Tsuk1ko** [comment]
我之前是有准备弄一个即时反馈的选项，开了之后搜图只要收到图就给你回复一下表示收到了，最近太忙给忘了

**Comment by A2Sumie** [comment]
> 我有点好奇你的超时时间设置的是多少 ![image](https://user-images.githubusercontent.com/66856838/220857442-92f7abc2-5ef8-4cc7-805e-421960ef0580.png)

90，我知道可以调短一点虽然
群友难伺候（唉
