### ISSUE TITLE
本子搜索提示nHentai搜索不到内容

### ISSUE THREAD

**Issue by tkosf** [Tsuk1ko/cq-picsearcher-bot#396]
今天尝试了下更新并把bot.getDoujinDetailFromNhentai功能打开了，试了下，发现在saucenao能正确搜索到对应本子但却会提示nh找不到对应内容，实际上nh也是能搜到的，尝试了使用主站和镜像站都是一个结果
位置文件如下
![XW8VF5)2K15XE93(X%6UERD](https://user-images.githubusercontent.com/63329502/222928566-f98ec63a-ef04-4981-af9d-83bc2ad704c3.png)
以及实际情况
![58A7E4669A9FAF96E5A2D8C483596A3F](https://user-images.githubusercontent.com/63329502/222928609-6387a816-132f-4da2-8fca-3a6678ceeb22.jpg)
![6471B04697E3150968A9C8E8AB73A5B1](https://user-images.githubusercontent.com/63329502/222928613-3ec5e606-18cb-4ba9-bf6f-af630b9df7d4.jpg)

**Comment by Tsuk1ko** [comment]
主站暂时别想了，有五秒盾现在还没找到破解方法，目前无法到主站搜

因为是比较新的本子，镜像站还没有，搜不到

https://nhentai.xxx/search/?q=%E5%8B%9D%E6%89%8B%E3%81%AB%E7%AB%A5%E8%B2%9E%E3%81%A8%E5%8B%98%E9%81%95%E3%81%84%E3%81%97%E3%81%A6%E3%81%8F%E3%82%8B%E3%82%B3%E3%83%86%E3%82%B3%E3%83%86%E3%81%AE%E3%83%84%E3%83%B3%E3%83%87%E3%83%AC%E9%87%91%E9%AB%AA%E3%83%84%E3%82%A4%E3%83%B3%E3%83%86%E3%83%BC%E3%83%AB
