### ISSUE TITLE
功能请求 rate check期内撤回重复的带B站链接信息 或 撤回指定用户发送的带B站链接信息

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#398]
1. 加什么功能 如题
2. 理由 有人丢了个带解析的bot进群，也不是很方便直接移出去，那台还没有ratecheck，现在谁发个什么就至少被解析三次

**Comment by Tsuk1ko** [comment]
这个太复杂了不想做，加个黑白群名单倒可以

**Comment by A2Sumie** [comment]
> 这个太复杂了不想做，加个黑白群名单倒可以

也行（）
