### ISSUE TITLE
功能请求 b站解析在解析中标出发送人

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#399]
请说明：

1. 加什么功能 如题 解析b站时在开头或者文末记录下动态是谁发的 “XXX(1234111111)分享了：...”这样
2. 理由 最近qq风控加强，经常只有手表协议能用但手表协议不接收撤回信息所以跟随撤回没用了

**Comment by Tsuk1ko** [comment]
az，查内鬼是吧

之前试过 gocq dev 可以用其他协议登录了来着，aPad 协议用短信验证能登

**Comment by A2Sumie** [comment]
> az，查内鬼是吧
> 
> 之前试过 gocq dev 可以用其他协议登录了来着，aPad 协议用短信验证能登

倒也没有内鬼，有内鬼我直接退群了（）
短信登陆是啥（？

**Comment by A2Sumie** [comment]
> az，查内鬼是吧
> 
> 之前试过 gocq dev 可以用其他协议登录了来着，aPad 协议用短信验证能登

懂了，删device.json触发设备锁吗，活咯，thx

**Comment by Tsuk1ko** [comment]
> > az，查内鬼是吧
> > 之前试过 gocq dev 可以用其他协议登录了来着，aPad 协议用短信验证能登
> 
> 懂了，删device.json触发设备锁吗，活咯，thx

sdy，登录失败之后设备信息就被拉黑了，必删
