### ISSUE TITLE
chatgpt调试

### ISSUE THREAD

**Issue by bitterndumpling** [Tsuk1ko/cq-picsearcher-bot#400]
export default async context => {
  if (context.group_id) {
    if (blackGroup.has(context.group_id)) return false;
    if (whiteGroup.size && !whiteGroup.has(context.group_id)) return false;
  }

 //这里的context.message是带有CQ格式的，直接用配置文件中的正则匹配一定会失败
  const { match, config } = getMatchAndConfig(context.message);

  if (!match) return false;
  if (!config.apiKey) {
    global.replyMsg(context, '未配置 APIKey', false, true);
    return false;
  }

//应该先替换掉CQ格式吧
  const prompt = match[1]?.replace(/\[CQ:[^\]]+\]/g, '').trim();
  if (!prompt) return false;

**Comment by Tsuk1ko** [comment]
为啥会失败，你是 at 机器人了吗，这个功能是不需要 at 的，只要匹配正则就触发

如果你希望 at 才触发，应在正则配置中直接考虑这点
