### ISSUE TITLE
带上下文的GPT

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#405]
1. 加什么功能 就如题，私聊能用就行（？
2. 理由 GPT-4 API开放测试了（（（

顺便GPT-4如果给资格了直接把模型名改一下就能用了很快乐

**Comment by Tsuk1ko** [comment]
先咕到我 gpt-4 下来再说（

**Comment by A2Sumie** [comment]
> 先咕到我 gpt-4 下来再说（

不知道现在能不能开新号不过我有个还没注册过OpenAI的日本手机以及日本家庭网络可以用（）

**Comment by Tsuk1ko** [comment]
现在新注册必须验证信用卡了，没得白嫖了

**Comment by A2Sumie** [comment]
> 现在新注册必须验证信用卡了，没得白嫖了
> 
> 然后我的号已经过试用了（寄了

我的也绑了，悲，学生应该拿不到第二张

**Comment by A2Sumie** [comment]
> 现在新注册必须验证信用卡了，没得白嫖了
> 
> 然后我的号已经过试用了（寄了

我私你一个key（？用了这么久了你先用好了（

**Comment by Tsuk1ko** [comment]
不用，我已经跟朋友借了（

**Comment by jx9468** [comment]
> 先咕到我gpt-4下来再说（

GPT4要开放了，不能咕了😆而且GPT4的图片输入不知道是否可以支持~👀

**Comment by Tsuk1ko** [comment]
最近没什么兴趣玩 chatgpt 👀

不如直接找别人写好的 onebot 协议的

**Comment by jx9468** [comment]
> 最近没什么兴趣玩chatgpt👀
> 
> 不如直接找别人写好的onebot协议的

nonebot倒是有不少，但是太臃肿了🤣什么功能都往里塞

**Comment by A2Sumie** [comment]
提问的觉得可以咕（）上下文就那样了（）
能塞前置消息其实就OK了（）
或者就还是搞个对API接口的任意消息发送？需要乱七八糟的自己写请求
