### ISSUE TITLE
GPT：用户自定义的override

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#414]
请说明：

1. 加什么功能 允许用户在聊天中自己override，用户没发的参数用一个缺省模版由bot补上。
2. 理由 四舍五入就是有上下文了

**Comment by Tsuk1ko** [comment]
没懂

**Comment by A2Sumie** [comment]
> 没懂

用户可以自己决定发出去的messages等会是什么样子，这样可以把各种role之类的包进去

**Comment by Tsuk1ko** [comment]
算了吧，我不太想搞这么复杂，用起来又不方便也不是很实用
