### ISSUE TITLE
Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by SkyYeXianer** [Tsuk1ko/cq-picsearcher-bot#418]
是代理的问题吗？我正常填写了clash的代理地址
![image](https://user-images.githubusercontent.com/109300803/236966890-4b516c67-1782-42fc-baaf-6561e96b5ac3.png)
但是报错了
![image](https://user-images.githubusercontent.com/109300803/236966773-97614784-ffbf-4a72-8fad-972a1705ed7c.png)
不清楚这个问题的源头

**Comment by Tsuk1ko** [comment]
用的是什么功能？

**Comment by SkyYeXianer** [comment]
> 用的是什么功能？

我的，我的。是梯子的问题，改节点好了。
