### ISSUE TITLE
[feature request]语言库支持多个reply

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#419]
可以在语言库的reply中填入多个回复项，同时可以设置某个回复项的权重（不填则均分概率）
然后就可以手动实现某些功能：
![7161e96896caa7a9.png](https://user-images.githubusercontent.com/66856838/236987562-2c609f5d-0de3-48ec-b19e-7ef1a82c02ee.png)
![3685decbb9bcc892.png](https://user-images.githubusercontent.com/66856838/236987592-1268fadb-da9b-4433-8431-217715f366f4.png)

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#%E5%A4%9A%E4%B8%AA%E5%9B%9E%E5%A4%8D%E9%A1%B9

**Comment by Miuzarte** [comment]
> https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#%E5%A4%9A%E4%B8%AA%E5%9B%9E%E5%A4%8D%E9%A1%B9

好像超过十个内容的话只会回复第二个。。。？

**Comment by Tsuk1ko** [comment]
草，随机逻辑写错了

**Comment by Tsuk1ko** [comment]
修复了，拉下最新代码

**Comment by Miuzarte** [comment]
> 修复了，拉下最新代码

没问题了
