### ISSUE TITLE
vits功能无法使用

### ISSUE THREAD

**Issue by NoneFei** [Tsuk1ko/cq-picsearcher-bot#423]
1. Bug 描述
vits功能不正常，list有问题，default voice id也获取有问题。
<img width="445" alt="image" src="https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/20320839/3c7ebe12-d7c6-48c0-ba82-bfcf0bcaa785">

2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
<img width="1401" alt="image" src="https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/20320839/73c4c609-f4fd-4fac-8ea1-98968380a27f">
我是windows下直接部署的vits-simple-api，发现程序获取的voiceMap不太正常。请问是我的node版本太低导致的吗？
3. 运行环境
   - windows server 2016
   - node.js v14.17.0
   - go-cqhttp v1.0.1
   - cq-picsearcher-bot 3.10.0

**Comment by Tsuk1ko** [comment]
pull 下最新代码看看是否解决

**Comment by NoneFei** [comment]
最新代码测试id 0-3都使用正常，id4的上海话不正常，感觉应该是vits-simple-api的bug吧……
<img width="1680" alt="image" src="https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/20320839/7180674b-21c9-4c2b-8f20-0f421ca0e3af">

**Comment by Tsuk1ko** [comment]
没用过上海话模型不太清楚了……显示指定 lang=sh 行不行

**Comment by NoneFei** [comment]
指定lang=sh可以了……

**Comment by Tsuk1ko** [comment]
估计 vits 里面语言自动检测只有常用的那几种，我加个逻辑如果只有一种语言就直接加上参数好了
