### ISSUE TITLE
B站动态浏览器能访问但是机器人访问不到

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#424]
开了debug也没有日志
https://t.bilibili.com/794507398833242146
![image](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/66856838/f7a72e42-03ee-4ac6-a56d-55afce36ba35)
![image](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/66856838/33af3395-bd67-4a89-886c-e4e81edde4ce)

**Comment by Tsuk1ko** [comment]
获取动态的 API 老好像加鉴权了……不带 cookie 返回空内容，得换新接口

```
https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=794507398833242146
```
