### ISSUE TITLE
VITS 模型只有一种语言时自动添加语言参数

### ISSUE THREAD

**Issue by Tsuk1ko** [Tsuk1ko/cq-picsearcher-bot#425]
最新代码测试id 0-3都使用正常，id4的上海话不正常，感觉应该是vits-simple-api的bug吧……
<img width="1680" alt="image" src="https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/20320839/7180674b-21c9-4c2b-8f20-0f421ca0e3af">

_最初由 @NoneFei 在 https://github.com/Tsuk1ko/cq-picsearcher-bot/issues/423#issuecomment-1545042681 发布_

**Comment by Tsuk1ko** [comment]
@NoneFei 可以试试最新代码，应该不加 lang=sh 也可以了

**Comment by NoneFei** [comment]
可以啦！
