### ISSUE TITLE
希望能加入newbing的功能

### ISSUE THREAD

**Issue by Ayanami404** [Tsuk1ko/cq-picsearcher-bot#426]
1. 希望能加入newbing的功能
2. 理由是因为目前newbing已经全面开放测试了，对于chatgpt的一些问题解决有点不太行，newbing对于信息搜索的功能更强大
3. 希望能和目前使用chatgpt一样使用对应的关键词触发对应的选择

**Comment by huankong233** [comment]
> 可以试试用我这个来驱动:https://github.com/huankong233/edgeGpt_backEnd
> 
> : )

可以直接抄https://github.com/huankong233/kkbot/blob/master/plugins/bing/index.js
