### ISSUE TITLE
功能请求：admin群

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#427]
请说明：

1. 加什么功能 定义一个admin群，这个群内admin账户可以发送管理指令。上线信息和对管理指令的回应无论admin在哪里发的，私聊和这个群里都同时回应一遍。
2. 理由 go-cqhttp最近太寄了，现在应急回滚的平板协议私聊没法用。

**Comment by Tsuk1ko** [comment]
我感觉直接让管理指令在群里也能响应算了，上线信息寄了就寄了
