### ISSUE TITLE
搜图时获取的图片url可能会出现问题

### ISSUE THREAD

**Issue by huankong233** [Tsuk1ko/cq-picsearcher-bot#428]
在使用最新的`go-cqhttp`时，bot端接收到新版`electronQQ`发送的图片时，会出现无法下载返回400报错的问题。

[详见](https://github.com/Mrs4s/go-cqhttp/issues/1795#issuecomment-1599845810)

**Comment by Tsuk1ko** [comment]
config.jsonc 里开 `bot.debug`，发`[图片]--get-url`，然后提供一下日志里收到消息和发出消息的内容

**Comment by Tsuk1ko** [comment]
![image](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/24877906/ec078307-0dda-47a2-bd02-868a51378b5d)

这个是因为 cq 码的转义，是正常的，实际获取的时候会进行反转义

新QQ的链接我以前也做过处理了56594b67c16faa64ad32f5bbcb66d73d01476dd1 ，得看看你这个是什么问题

**Comment by huankong233** [comment]
🤔原来如此
