### ISSUE TITLE
非本地部署go-cqhttp时B站推送图片连接错误

### ISSUE THREAD

**Issue by YipSzeho** [Tsuk1ko/cq-picsearcher-bot#435]
go-cqhttp和cq-picsearcher-bot部署在两台机器，B站推送消息的图片CQ码为部署cqps的本地文件夹，无法正常显示
![00293a778736cb573a8e8ca14b7105fe](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/58989046/9483d9c8-d2df-4631-958d-edee64aabfb1)

**Comment by Tsuk1ko** [comment]
配置不要启用 `bot.bilibili.dynamicImgPreDl`
