### ISSUE TITLE
QQNT转发的小程序无法直接解析

### ISSUE THREAD

**Issue by huankong233** [Tsuk1ko/cq-picsearcher-bot#437]
~~~ CQ-code
[CQ:json,data={"ver":"1.0.0.19"&#44;"prompt":"&#91;QQ小程序&#93;哦哈哟学妹"&#44;"config":{"type":"normal"&#44;"width":0&#44;"height":0&#44;"forward":1&#44;"autoSize":0&#44;"ctime":1693033690&#44;"token":"e15215ec6920446b61bbb48310b4d173"}&#44;"app":"com.tencent.miniapp_01"&#44;"view":"view_8C8E89B49BE609866298ADDFF2DBABA4"&#44;"meta":{"detail_1":{"appid":"1109937557"&#44;"appType":0&#44;"title":"哔哩哔哩"&#44;"desc":"哦哈哟学妹
"&#44;"icon":"https://miniapp.gtimg.cn/public/appicon/51f90239b78a2e4994c11215f4c4ba15_200.jpg"&#44;"preview":"https://i2.hdslb.com/bfs/archive/a0b01179042ed50818aede09f5c6628103cf7fa5.jpg@500w_400h_1e_1c"&#44;"url":"m.q.qq.com/a/s/401ba08541413eb33f3f633e7a6e60fe"&#44;"scene":0&#44;"host":{"uin":2564076459&#44;"nick":"幻空"}&#44;"shareTemplateId":"8C8E89B49BE609866298ADDFF2DBABA4"&#44;"shareTemplateData":{}&#44;"showLittleTail":""&#44;"gamePoints":""&#44;"gamePointsUrl":""}}&#44;"miniappShareOrigin":3&#44;"miniappOpenRefer":"10002"}]
~~~

这是QQNT转发出来的小程序的数据
url是 `m.q.qq.com/a/s/401ba08541413eb33f3f633e7a6e60fe`
![image](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/49610758/8a537714-c2fa-46b9-b2a6-dc749744b346)
手机浏览器进入会拉起手机qq
我手机上抓包得到了一些被压缩过的数据，看不太懂

**Comment by Tsuk1ko** [comment]
m.q.qq.com 的解析不了，目前 go-cq 不支持获取 qq 页面登录态，没法直接拿到原链接

![image](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/24877906/5a97211f-2e13-45fb-8c13-1e701ac987e3)

![image](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/24877906/eb2fb99b-ba30-4e33-bd18-9c8e16bc4134)

**Comment by huankong233** [comment]
> m.q.qq.com 的解析不了，目前 go-cq 不支持获取 qq 页面登录态，没法直接拿到原链接
> 
> ![image](https://user-images.githubusercontent.com/24877906/263450139-5a97211f-2e13-45fb-8c13-1e701ac987e3.png)
> 
> ![image](https://user-images.githubusercontent.com/24877906/263450161-eb2fb99b-ba30-4e33-bd18-9c8e16bc4134.png)

这个登陆态是用来干啥的，我研究一下🤔，谢谢回复

**Comment by Tsuk1ko** [comment]
不对，想了下好像有登录态也不行（

这玩意是直接靠 schema 开的，应该是手Q nt 有某种接口可以用这个链接换到小程序信息，web 层面解决不了了

**Comment by huankong233** [comment]
> 不对，想了下好像有登录态也不行（
> 
> 这玩意是直接靠 schema 开的，应该是手Q nt 有某种接口可以用这个链接换到小程序信息，web 层面解决不了了
> 
> ![image](https://user-images.githubusercontent.com/24877906/263451099-255a8ecb-445b-49ed-8d03-dd6854068bc3.png)

所以我抓包也没抓到有用的东西 😭
