### ISSUE TITLE
原图模式（对应搜图模式）

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#443]
请说明：

1. 加什么功能 如题。类似于现在发送searchModeON可以打开搜图模式一样，希望有个用关键字触发图片应答的功能
2. 理由 不要脸的来要四叶草相关了
四叶草下如果回复一个图片然后at bot的话，只会有默认回复。表情转原图也是不可用的状态。但是搜图模式下表情是可以正常被搜索的。
既然现在开发者还不方便部署四叶草的话，希望能加一个原图模式。
姑且作为参照，四叶草是1.0.5 dev d28c6dc,CQ码模式开（关了看上去也一样）

**Comment by Tsuk1ko** [comment]
现在可以在进入搜图模式后发送`原图`两个字进入原图模式，同理私聊也可以发送`原图`两个字进入临时原图模式
