### ISSUE TITLE
请问现在soutubot.moe还有cf 5秒盾吗

### ISSUE THREAD

**Issue by 0769559** [Tsuk1ko/cq-picsearcher-bot#449]
功能需求：搜本子添加soutubot.moe

最近正常浏览这网站好像没有碰见cf 5秒盾了 不知道能不能添加上呢？

**Comment by Tsuk1ko** [comment]
有空我试一下

**Comment by Tsuk1ko** [comment]
发现还是有五秒盾，估计只是严格程度下调了一点

<img width="845" alt="image" src="https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/24877906/9fda4e04-11cc-4fd0-9b15-9fbe6eb1b9be">

**Comment by 0769559** [comment]
可惜了，不过这个和之前的Ascii2d情况不一样吗 #283
