### ISSUE TITLE
求教docker compose部署遇到的问题

### ISSUE THREAD

**Issue by jx9468** [Tsuk1ko/cq-picsearcher-bot#452]
运行`docker-compose up -d`后无法连接go-cqhttp,进入docker容器，容器内的config.jsonc文件是0kb，不清楚原因，百度也找不到😥反向ws的nonebot是能连接上的🤕

`config.jsonc`文件配置
>   "cqws": {
>     "host": "host.docker.internal",
>     "port": 6700,
>     "enableAPI": true,
>     "enableEvent": true,
>     "accessToken": "",
>     "reconnection": true,
>     "reconnectionAttempts": 10,
>     "reconnectionDelay": 5000

文件目录
![1](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/78193384/f0601dad-a20f-404d-8e5c-2a3bcd93e449)
![2](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/78193384/71b0bb37-e83f-401c-80f5-26840aa8635a)

docker容器内config.jsonc为0kb，且尝试了在`volumes:`下面加入其他文件，都是到容器里就成了0kb

![3](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/78193384/24ef7d63-425b-46fb-93cf-ec7cf025830b)
go-cqhttp配置
使用`docker run -d --name cqhttp -p 6700:6700 -p 5700:5700 --network=host -v /root/data/docker_data/go-cqhttp:/data go-cqhttp-image`docker部署

![4](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/78193384/0733faea-1e56-45d5-80ea-ddf3469c4cfd)

**Comment by Tsuk1ko** [comment]
看看容器日志？

**Comment by jx9468** [comment]
> 查看集装箱日志？

![d3b0235ef822331b4a5b6ee6454518a](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/78193384/1b38b1dd-dbe3-47b1-b6c8-6620229bb623)
系统：Ubuntu 22

**Comment by Tsuk1ko** [comment]
看日志是成功连接了呀🤔

**Comment by jx9468** [comment]
> 看日志是成功连接了呀🤔

![aca5ff24ff5ae950be156273565c527](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/78193384/ae688395-d385-4f59-aa5c-b5378a3f6914)
一直连接中，指令也是没有反应的😭

**Comment by jx9468** [comment]
> 看日志是成功连接了呀🤔

![21eac7209de2665002b54510f02be22](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/78193384/84f33149-b69e-4d79-9813-8b0d87b5b0db)
尝试在宿主机运行zerobot是能够连接的，应该不是gocq的问题😥

**Comment by Tsuk1ko** [comment]
🧐那可能是 host 的问题，你试试找到网关 ip 直接设置 ip，不用那个域名

**Comment by jx9468** [comment]
改成 host 网络模式确实可以成功，就是不知道原先配置到底哪出的问题🤦‍♂️

**Comment by Tsuk1ko** [comment]
大概是这个没起作用

https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/f32e5bb590f29177ada5732c97c1943c47482bdc/docker-compose.yml#L7-L8

我也不知道为什么，我自己用 mac 和 linux 测过都 ok，不过网上也能搜到一些不起作用的案例

总之几种解决方案：

1. 直接用 host 模式，然后连 127.0.0.1
2. 获取 docker 的网关地址，例如 bash 进 docker 容器然后 `ip addr` 看 gateway，一般是 `172.xx.0.1` 这样的，然后连这个 ip
3. 把 go-cqhttp 容器也写到 docker-compose 配置里，配到同一个网络，然后就可以直接用 name 作为 host 连接，不过也需要配置 depends_on，甚至可能需要 [wait-for-it](https://github.com/vishnubob/wait-for-it)
