### ISSUE TITLE
希望添加LLOneBot支持

### ISSUE THREAD

**Issue by zxczaq001** [Tsuk1ko/cq-picsearcher-bot#455]
go-cqhttp断更后 在高版本协议就算签名 基本半个月就会触发风控 我的Q号三个月内多次触发导致不给解封了 
换号使用LLOneBot搜图兼容好像不太行 OpenShamrock在服务器要模拟安卓部署感觉比较麻烦

**Comment by Annabel0530** [comment]
我也有在用LLOneBot，目前是私聊搜图都会回复“该图片已过期，请尝试二次截图后发送”，群聊正常，但不确定是什么原因，其他方面没啥问题。

**Comment by Tsuk1ko** [comment]
> 我也有在用LLOneBot，目前是私聊搜图都会回复“该图片已过期，请尝试二次截图后发送”，群聊正常，但不确定是什么原因，其他方面没啥问题。

可以提供一下收到图片时的消息吗，包含图片cq码

**Comment by Tsuk1ko** [comment]
> go-cqhttp断更后 在高版本协议就算签名 基本半个月就会触发风控 我的Q号三个月内多次触发导致不给解封了 
> 
> 换号使用LLOneBot搜图兼容好像不太行 OpenShamrock在服务器要模拟安卓部署感觉比较麻烦

具体是哪些地方有兼容问题？

**Comment by Annabel0530** [comment]
[1.log](https://github.com/Tsuk1ko/cq-picsearcher-bot/files/14622364/1.log)
先是群聊搜索成功的，然后同一份图发私聊

**Comment by Tsuk1ko** [comment]
@Annabel0530 pull 下最新代码试试，应该修复了

**Comment by Annabel0530** [comment]
> @Annabel0530 pull 下最新代码试试，应该修复了

私聊可以了，目前还没遇到过其他兼容问题

**Comment by zxczaq001** [comment]
> > @Annabel0530 pull 下最新代码试试，应该修复了
> 
> 私聊可以了，目前还没遇到过其他兼容问题

嗯 私聊可以了  不过我以前群是@加图片的 现在@加图片好像没反应 顺便问问LLOneBot的log文件在哪

**Comment by Annabel0530** [comment]
> > > @Annabel0530 pull 下最新代码试试，应该修复了
> > 
> > 
> > 私聊可以了，目前还没遇到过其他兼容问题
> 
> 嗯 私聊可以了 不过我以前群是@加图片的 现在@加图片好像没反应 顺便问问LLOneBot的log文件在哪

@加图和指令开启我都正常的，你看看是不是被屏蔽了，日志要开启写入，插件那能找到地址，LiteLoaderQQNT-main\data\LLOneBot

**Comment by zxczaq001** [comment]
> > > > @Annabel0530 pull 下最新代码试试，应该修复了
> > > 
> > > 
> > > 私聊可以了，目前还没遇到过其他兼容问题
> > 
> > 
> > 嗯 私聊可以了 不过我以前群是@加图片的 现在@加图片好像没反应 顺便问问LLOneBot的log文件在哪
> 
> @加图和指令开启我都正常的，你看看是不是被屏蔽了，日志要开启写入，插件那能找到地址，LiteLoaderQQNT-main\data\LLOneBot

 constructMessage error:  TypeError: Cannot read properties of null (reading 'toString')
    at getGroupMember (/opt/LiteLoader/plugins/LLOneBot/main/main.cjs:1489:35)
    at OB11Constructor.message (/opt/LiteLoader/plugins/LLOneBot/main/main.cjs:6388:36) 
报这个

**Comment by zxczaq001** [comment]
@无效是LLOneBot问题 新版已修复

**Comment by Loukyuu1120** [comment]
我用llonebot，更新到最新版cqps，回复图片艾特不能触发搜图，之前可以

**Comment by Tsuk1ko** [comment]
@Loukyuu1120 发一下回复时llonebot的日志

**Comment by zxczaq001** [comment]
@Loukyuu1120 先尝试更新LLOneBot 之前艾特无效后某个版本开始又合并转发有问题 在群里艾特触发有问题 最新版已经修复

**Comment by Loukyuu1120** [comment]
> @Loukyuu1120 发一下回复时llonebot的日志

4/21/2024, 2:57:08 AM 阿罗娜(2324545622): ws 消息上报 ws://149.104.12.86:3333/ {"self_id":2324545622,"user_id":14444,"time":1713639428,"message_id":-2147437996,"real_id":-2147437996,"message_type":"group","sender":{"user_id":14444,"nickname":"Sakana","card":"","role":"owner"},"raw_message":"[CQ:image,file=A6CE93528E83C4F5B32DE76191AC0B57.jpg,url=https://gchat.qpic.cn/gchatpic_new/14444/534739674-2739392872-A6CE93528E83C4F5B32DE76191AC0B57/0?term=255&amp;is_origin=1,file_size=16630]","font":14,"sub_type":"normal","message":[{"data":{"file":"A6CE93528E83C4F5B32DE76191AC0B57.jpg","url":"https://gchat.qpic.cn/gchatpic_new/14444/534739674-2739392872-A6CE93528E83C4F5B32DE76191AC0B57/0?term=255&is_origin=1","file_size":"16630"},"type":"image"}],"message_format":"array","post_type":"message","group_id":534739674} 

4/21/2024, 2:57:08 AM 阿罗娜(2324545622): ws 消息上报  {"self_id":2324545622,"user_id":14444,"time":1713639428,"message_id":-2147437996,"real_id":-2147437996,"message_type":"group","sender":{"user_id":14444,"nickname":"Sakana","card":"","role":"owner"},"raw_message":"[CQ:image,file=A6CE93528E83C4F5B32DE76191AC0B57.jpg,url=https://gchat.qpic.cn/gchatpic_new/14444/534739674-2739392872-A6CE93528E83C4F5B32DE76191AC0B57/0?term=255&amp;is_origin=1,file_size=16630]","font":14,"sub_type":"normal","message":[{"data":{"file":"A6CE93528E83C4F5B32DE76191AC0B57.jpg","url":"https://gchat.qpic.cn/gchatpic_new/14444/534739674-2739392872-A6CE93528E83C4F5B32DE76191AC0B57/0?term=255&is_origin=1","file_size":"16630"},"type":"image"}],"message_format":"array","post_type":"message","group_id":534739674} 

4/21/2024, 2:57:16 AM 阿罗娜(2324545622): ws 消息上报 ws://149.104.12.86:3333/ {"self_id":2324545622,"user_id":14444,"time":1713639435,"message_id":-2147437995,"real_id":-2147437995,"message_type":"group","sender":{"user_id":14444,"nickname":"Sakana","card":"","role":"owner"},"raw_message":"[CQ:reply,id=-2147437996][CQ:at,qq=2324545622]","font":14,"sub_type":"normal","message":[{"data":{"id":"-2147437996"},"type":"reply"},{"data":{"qq":"2324545622"},"type":"at"}],"message_format":"array","post_type":"message","group_id":534739674} 

4/21/2024, 2:57:16 AM 阿罗娜(2324545622): ws 消息上报  {"self_id":2324545622,"user_id":14444,"time":1713639435,"message_id":-2147437995,"real_id":-2147437995,"message_type":"group","sender":{"user_id":14444,"nickname":"Sakana","card":"","role":"owner"},"raw_message":"[CQ:reply,id=-2147437996][CQ:at,qq=2324545622]","font":14,"sub_type":"normal","message":[{"data":{"id":"-2147437996"},"type":"reply"},{"data":{"qq":"2324545622"},"type":"at"}],"message_format":"array","post_type":"message","group_id":534739674} 

4/21/2024, 2:57:16 AM 阿罗娜(2324545622): 收到正向Websocket消息 {"action":"get_msg","params":{"message_id":-2147437996},"echo":{"reqid":"VVB2i8zzM"}} 

4/21/2024, 2:57:16 AM 阿罗娜(2324545622): ws 消息上报  {"status":"ok","retcode":0,"data":{"self_id":2324545622,"user_id":14444,"time":1713639428,"message_id":-2147437996,"real_id":-2147437996,"message_type":"group","sender":{"user_id":14444,"nickname":"Sakana","card":"","role":"owner"},"raw_message":"[CQ:image,file=A6CE93528E83C4F5B32DE76191AC0B57.jpg,url=https://gchat.qpic.cn/gchatpic_new/14444/534739674-2739392872-A6CE93528E83C4F5B32DE76191AC0B57/0?term=255&amp;is_origin=1,file_size=16630]","font":14,"sub_type":"normal","message":[{"data":{"file":"A6CE93528E83C4F5B32DE76191AC0B57.jpg","url":"https://gchat.qpic.cn/gchatpic_new/14444/534739674-2739392872-A6CE93528E83C4F5B32DE76191AC0B57/0?term=255&is_origin=1","file_size":"16630"},"type":"image"}],"message_format":"array","post_type":"message","group_id":534739674},"message":"","wording":"","echo":{"reqid":"VVB2i8zzM"}} 

4/21/2024, 2:57:16 AM 阿罗娜(2324545622): 收到正向Websocket消息 {"action":"send_group_msg","params":{"group_id":534739674,"message":"[CQ:at,qq=14444]阿罗娜不在呢！"},"echo":{"reqid":"GbHQKg89YJ"}} 

4/21/2024, 2:57:16 AM 阿罗娜(2324545622): 消息发送结果 {"msgId":"7434242366189755305","msgRandom":"957100566","msgSeq":"9268","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":1,"senderUid":"u_aoQ2el1VVpV93f9631CRCw","peerUid":"534739674","channelId":"","guildId":"undefined","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1713639436","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"阿罗娜","sendNickName":"阿罗娜","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7360025331865766813","extBufForUI":"0x","textElement":{"content":"@Sakana","atType":2,"atUid":"14444","atTinyId":"0","atNtUid":"u_WlV8PEpWmKN6jeE5iv9-xw","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null},{"elementType":1,"elementId":"7360025331865766814","extBufForUI":"0x","textElement":{"content":"阿罗娜不在呢！","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"英语视听10班6组","freqLimitInfo":null,"editable":true,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":2,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"25499","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"2324545622","peerUin":"534739674","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"msgShortId":-2147437994} 

4/21/2024, 2:57:16 AM 阿罗娜(2324545622): ws 消息上报  {"status":"ok","retcode":0,"data":{"message_id":-2147437994},"message":"","wording":"","echo":{"reqid":"GbHQKg89YJ"}}

**Comment by Loukyuu1120** [comment]
> @Loukyuu1120 先尝试更新LLOneBot 之前艾特无效后某个版本开始又合并转发有问题 在群里艾特触发有问题 最新版已经修复

我用的是docker版本的LLoneBot，已经按照你说的更新了最新版本
![image](https://github.com/Tsuk1ko/cq-picsearcher-bot/assets/29080642/8c9c1785-3bf0-4303-849a-db98a8b6581b)
还是有我说的问题。另外合并转发应该没问题，直接艾特加图片没问题，只有回复图片艾特不行。

**Comment by Tsuk1ko** [comment]
@Loukyuu1120 pull 下 master 最新代码看看是否解决了

**Comment by Loukyuu1120** [comment]
@Tsuk1ko pull最新之后已经解决了
