### ISSUE TITLE
bili订阅推送不显示播放和收藏

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#460]
请说明：

1. 加什么功能 如题，（可选的）不给订阅推送显示播放和收藏数
2. 理由 信息流推送模式下一定是0播放0收藏，在原up能看见推送时会发生小小的尴尬

**Comment by Tsuk1ko** [comment]
确实，也不用加选项了，推送的话我直接不显示这个得了
