### ISSUE TITLE
请问cq-picsearcher-bot可以对接LiteLoadQQNT正常使用吗？

### ISSUE THREAD

**Issue by chaosChildrens** [Tsuk1ko/cq-picsearcher-bot#461]
我cq-picsearcher-bot和LiteLoadQQNT都是按对应教程正常部署的，运行没有报错。
cq-picsearcher-bot启用后可以向管理员发送上线信息，但是其他功能都没有反应，想问下是我的设置问题，还是2个组件本身就没有对接。

**Comment by Tsuk1ko** [comment]
基本支持 LLOneBot 的，已经有人试过 #455

可以设置 `bot.debug` 后看 cqps 日志是否有正常收到消息

**Comment by chaosChildrens** [comment]
> 基本支持 LLOneBot 的，已经有人试过 #455
> 
> 可以设置 `bot.debug` 后看 cqps 日志是否有正常收到消息

谢谢，解决了，是消息的上报格式对接问题。
有新的问题，部分搜图会提示“该图片已过期，请尝试二次截图后发送”，部分搜图是可用的。
重新截图，或者新图也会有这个提示，请问可能是什么原因导致的？

**Comment by Tsuk1ko** [comment]
> 谢谢，解决了，是消息的上报格式对接问题。

🤔按理说是兼容数组上报的，因为我会直接取 raw_message，只要机器人客户端遵循 onebot11 就应该会提供，上面 issue 中的用户看日志也是用的数组上报

> 部分搜图会提示“该图片已过期，请尝试二次截图后发送”

这个跟机器人客户端和发送方客户端有关系，部分机器人客户端有 bug 无法正确拼接部分客户端发送的图片 URL，可以看看客户端日志看看 URL

类似 #459 Mrs4s/MiraiGo#341

**Comment by chaosChildrens** [comment]
> > 基本支持 LLOneBot 的，已经有人试过 #455
> > 可以设置 `bot.debug` 后看 cqps 日志是否有正常收到消息
> 
> 谢谢，解决了，是消息的上报格式对接问题。 有新的问题，部分搜图会提示“该图片已过期，请尝试二次截图后发送”，部分搜图是可用的。 重新截图，或者新图也会有这个提示，请问可能是什么原因导致的？

我之前机器人只有上线信息，我把LLONEBOT信息上报格式从默认“消息段”改成了“CQ码”，无法搜图但是发图。



> > 谢谢，解决了，是消息的上报格式对接问题。
> 
> 🤔按理说是兼容数组上报的，因为我会尽可能使用 raw_message，只要机器人客户端遵循 onebot11 就应该会提供，上面 issue 中的用户看日志也是用的数组上报
> 
> > 部分搜图会提示“该图片已过期，请尝试二次截图后发送”
> 
> 这个跟机器人客户端和发送方客户端有关系，部分机器人客户端有 bug 无法正确拼接部分客户端发送的图片 URL，可以看看客户端日志看看 URL
> 
> 类似 #459 [Mrs4s/MiraiGo#341](https://github.com/Mrs4s/MiraiGo/issues/341)

然后我现在改回“消息码”。搜图和发图功能都正常了，很怪的BUG。

但总体而言，对接已经完成了。感谢协助。
