### ISSUE TITLE
FR:搜图，长图自动截选并跳过SauceNao

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#462]
请说明：

1. 加什么功能 搜图时，如果图片纵横比大于一设定值，比如纵向尺寸超过横向尺寸4倍时，按照纵对横3:2截取最上部分并（可选的）跳过SauceNao
2. 理由 
对于一些喜欢发长图本子的人比较省事，长图进去出来也是鬼图
自动3:2之后SauceNao估计很难出结果

**Comment by Tsuk1ko** [comment]
确实，直接不搜并默认回复“检测到长图，不予搜索”得了

增加 忽略长图 开关和 长图回复内容 配置

截就不截了，自己截的也没法确保只截一页

要搜的自己去 soutubot.moe 搜，也可以在回复内容里加这个提示（

**Comment by A2Sumie** [comment]
> 确实，直接不搜并默认回复“检测到长图，不予搜索”得了
> 
> 增加 忽略长图 开关和 长图回复内容 配置
> 
> 截就不截了，自己截的也没法确保只截一页
> 
> 要搜的自己去 soutubot.moe 搜，也可以在回复内容里加这个提示（

草，也行xD
