### ISSUE TITLE
Linux 下 Lagrange 无法发送 https://multimedia.nt.qq.com.cn 域下的图片

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#467]
可以做个特殊处理转成base64吗，合并转发因为第一条就是收到的原图导致一直发不出去

https://github.com/LagrangeDev/Lagrange.Core/issues/315#issuecomment-2100941579

另外缓存又失效了，测试的时候同一张图一直没触发缓存

```
[2024-07-16 16:47:43] [MessagingLogic] [VERBOSE]: [MessageChain(612645549)(982809597)] [Image: 768x1024] [图片] 6eafeea60ff2a232a8682eeef387ab0d.jpg 92207 https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=Cgk5ODI4MDk1OTcSFIgpaBOJGHDkpLsDodmJLu9p_MnEGK_QBSD_CiiX6877iKuHA1CAvaMB&rkey=CAISMMYQKd4arC2zl08LS8pC23UeXoW0ON-QHbKzSE1xQ1RR97xgY-oA4ovEgVVMnLjVWw&spec=0
```
```
[2024-07-16 16:48:11] [MessagingLogic] [VERBOSE]: [MessageChain(612645549)(982809597)] [Image: 768x1024] [图片] 6eafeea60ff2a232a8682eeef387ab0d.jpg 92207 https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=Cgk5ODI4MDk1OTcSFIgpaBOJGHDkpLsDodmJLu9p_MnEGK_QBSD_CiiVopiJiauHA1CAvaMB&rkey=CAMSMNJmVGYUQ6P1kU7YYEijTnUG1wxQFE3F6QdJCPpkmIP8nrXlL6qL3n7Kad_ZpT8fEw&spec=0
```
![Code_GJv5v7mz87](https://github.com/user-attachments/assets/fd8d95dd-cc28-4378-9dcf-e86289464d38)

**Comment by Tsuk1ko** [comment]
那我判断下如果遇到这个域名就改成 http 协议应该就行

缓存的话这俩链接 fileid 也不一样，试了下只有前三节是必须，得额外处理下

**Comment by Tsuk1ko** [comment]
好像也不太对，按前三节做id好了

**Comment by Miuzarte** [comment]
群聊
```
https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=Cgk5ODI4MDk1OTcSFIgpaBOJGHDkpLsDodmJLu9p_MnEGK_QBSD_CijQ4sj5i6uHA1CAvaMB&rkey=CAQSMFYmFMzEaRxpMlrFtMoX1VOfkWFpIitVcTpUDjbk7a8prNv95Gbh9M3hV8twFQsQ7w&spec=0
```

私聊
```
https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=Cgk5ODI4MDk1OTcSFIgpaBOJGHDkpLsDodmJLu9p_MnEGK_QBSD-CijE5tWRjKuHAw&rkey=CAESMCwPuSjPoAwgedDwZIsPTYbmvm-ULQUiUStWLUnOWWYddTsaI8DEzKy9449i-OYf0Q&spec=0
```

换一个人发的话测不了，没别的bot，本地用插件实现的复制链接得到的结果还是 https://gchat.qpic.cn 域的

**Comment by Tsuk1ko** [comment]
其他人发的，bot收到就不是这个域名了么

**Comment by Miuzarte** [comment]
> 其他人发的，bot收到就不是这个域名了么

你等我找个群友发来试试，域名是一样的

**Comment by Miuzarte** [comment]
> 其他人发的，bot收到就不是这个域名了么

我手上倒是还有个别人的bot
同一个群内我发图
```
https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=Cgk5ODI4MDk1OTcSFIgpaBOJGHDkpLsDodmJLu9p_MnEGK_QBSD_Cijxg4zzjauHA1CAvaMB&rkey=CAISMCsV16WERkqG6r_-8Y3iCrHYqWybrbnFZ-OCYlirkiFGBDGf9dy2dSVsKbB6lDxiow&spec=0
```
```
https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=Cgk5ODI4MDk1OTcSFIgpaBOJGHDkpLsDodmJLu9p_MnEGK_QBSD_Cijxg4zzjauHA1CAvaMB&rkey=CAISMCsV16WERkqG6r_-8Y3iCrHYqWybrbnFZ-OCYlirkiFGBDGf9dy2dSVsKbB6lDxiow&spec=0
```
两个接收方得到的链接是一样的

**Comment by Tsuk1ko** [comment]
行，那看来就取前三节就行了

![image](https://github.com/user-attachments/assets/d5447be5-c4a7-4f08-8069-bffa2bd35a21)

**Comment by Miuzarte** [comment]
> 那我判断下如果遇到这个域名就改成 http 协议应该就行
> 
> 缓存的话这俩链接 fileid 也不一样，试了下只有中间2节是必须，得额外处理下

不知道什么时候开始又变成 https 了

<details>
  <summary>图片</summary>

  ![Image](https://github.com/user-attachments/assets/0d2f182e-2590-4484-a3cf-e81f7edeb6ad)

</details>

另外缓存也又双叒寄了

同一张图发三次

```
[CQ:image,file=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_woo4IDWyPHJiwMyBHByb2RQgL2jAVoQ_OqIqJ17S1076nPmHQFqSw&rkey=CAESKG0EIKe3_88rQmVxTvOJqO_Fh7fAvHTgKoaHP9E-KSUPqtg-upEMy54]

[CQ:image,file=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_woo9t6myfHJiwMyBHByb2RQgL2jAVoQZelETf9OGQLWJaQRXb0ddg&rkey=CAESKG0EIKe3_88rOt5Xynv_0RZyIMwLC5r5ciMws_FJ5QOrtJfFFk4HP0c]

[CQ:image,file=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_woooOqFyvHJiwMyBHByb2RQgL2jAVoQj7rFksmeuWCcGSVtsxXJrQ&rkey=CAMSKCnRkWXeilTOH6JOOa1Fle5ntNaA1m3NDkZ-c3eG7M-sjq4tSSIQOOE]
```

**Comment by Tsuk1ko** [comment]
试试

**Comment by Miuzarte** [comment]
> 试试

还是没触发缓存

**Comment by Miuzarte** [comment]
> 😭不该啊
> 
> https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/d04e9f6472cf2e957c72f5d00030b0c98b4b066e/src/utils/psCache.mjs
> 
> 要不你在这文件的61和62行中间加个
> 
> console.log(img, key);
> 看看输出

![Image](https://github.com/user-attachments/assets/496184dd-62c7-4cd3-8b9b-f2f4ff4ca205)

```
2/17/2025, 1:17:12 PM MsgImage {
  cq: CQ {
    type: 'image',
    data: Map(1) {
      'file' => 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_wooy_a8nPrJiwMyBHByb2RQgL2jAVoQ_b44rIbtZTCfZNH1MHmdfw&rkey=CAESKG0EIKe3_88rzKKyagG-gUoNmE6KKpr6XFlkFJK_HfH4lRoGwEAk1os'
    }
  },
  file: 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_wooy_a8nPrJiwMyBHByb2RQgL2jAVoQ_b44rIbtZTCfZNH1MHmdfw&rkey=CAESKG0EIKe3_88rzKKyagG-gUoNmE6KKpr6XFlkFJK_HfH4lRoGwEAk1os',
  url: 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_wooy_a8nPrJiwMyBHByb2RQgL2jAVoQ_b44rIbtZTCfZNH1MHmdfw&rkey=CAESKG0EIKe3_88rzKKyagG-gUoNmE6KKpr6XFlkFJK_HfH4lRoGwEAk1os',
  path: undefined,
  key: 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_wooy_a8nPrJiwMyBHByb2RQgL2jAVoQ_b44rIbtZTCfZNH1MHmdfw&rkey=CAESKG0EIKe3_88rzKKyagG-gUoNmE6KKpr6XFlkFJK_HfH4lRoGwEAk1os'
} EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg
2/17/2025, 1:17:31 PM MsgImage {
  cq: CQ {
    type: 'image',
    data: Map(1) {
      'file' => 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_woo5KjSpfrJiwMyBHByb2RQgL2jAVoQXnuOmETL4Kpv2lTlvw2piw&rkey=CAISKHim-nm2GSiHh0RSolSYLTqA1i784YqNWaaXZLnfdh_j6RZG2urNl30'
      }
    },
  file: 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_woo5KjSpfrJiwMyBHByb2RQgL2jAVoQXnuOmETL4Kpv2lTlvw2piw&rkey=CAISKHim-nm2GSiHh0RSolSYLTqA1i784YqNWaaXZLnfdh_j6RZG2urNl30',
  url: 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_woo5KjSpfrJiwMyBHByb2RQgL2jAVoQXnuOmETL4Kpv2lTlvw2piw&rkey=CAISKHim-nm2GSiHh0RSolSYLTqA1i784YqNWaaXZLnfdh_j6RZG2urNl30',
  path: undefined,
  key: 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg_woo5KjSpfrJiwMyBHByb2RQgL2jAVoQXnuOmETL4Kpv2lTlvw2piw&rkey=CAISKHim-nm2GSiHh0RSolSYLTqA1i784YqNWaaXZLnfdh_j6RZG2urNl30'
} EhS2PDmRAotuC7LNrDKT20QT3QkKvBjj5AYg
```

**Comment by Tsuk1ko** [comment]
那看起来应该没问题啊……

**Comment by Miuzarte** [comment]
> 那看起来应该没问题啊……

这些就是缓存么

![Image](https://github.com/user-attachments/assets/5a1d4246-a695-48ee-abc3-e7134379aec3)

**Comment by Tsuk1ko** [comment]
是

**Comment by Miuzarte** [comment]
> 是

那是不是没写缓存..?

**Comment by Tsuk1ko** [comment]
配置里 `bot.cache.enable` 应该 `true` 了吧？

不然就得看这里有没有走到

https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/6b6773fb08fdd00a9ea7a171c185f4a28d462b07/src/index.mjs#L676-L679

**Comment by Miuzarte** [comment]
> 配置里 `bot.cache.enable` 应该 `true` 了吧？
> 
> 不然就得看这里有没有走到
> 
> [cq-picsearcher-bot/src/index.mjs](https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/6b6773fb08fdd00a9ea7a171c185f4a28d462b07/src/index.mjs#L676-L679)
> 
> Lines 676 to 679 in [6b6773f](/Tsuk1ko/cq-picsearcher-bot/commit/6b6773fb08fdd00a9ea7a171c185f4a28d462b07)
> 
>  // 将需要缓存的信息写入数据库 
>  if (psCache.enable && success) { 
>    psCache.set(img, db, needCacheMsgs); 
>  }

![Image](https://github.com/user-attachments/assets/e0dd63a2-38a6-4c0c-b1ab-120dcac9d595)

![Image](https://github.com/user-attachments/assets/a072c393-a450-42aa-acd1-6b55a5ebae85)

啊？

**Comment by Miuzarte** [comment]
> 配置里 `bot.cache.enable` 应该 `true` 了吧？
> 
> 不然就得看这里有没有走到
> 
> [cq-picsearcher-bot/src/index.mjs](https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/6b6773fb08fdd00a9ea7a171c185f4a28d462b07/src/index.mjs#L676-L679)
> 
> Lines 676 to 679 in [6b6773f](/Tsuk1ko/cq-picsearcher-bot/commit/6b6773fb08fdd00a9ea7a171c185f4a28d462b07)
> 
>  // 将需要缓存的信息写入数据库 
>  if (psCache.enable && success) { 
>    psCache.set(img, db, needCacheMsgs); 
>  }

![Image](https://github.com/user-attachments/assets/54084eac-b2d4-4c9c-935f-b3d30ec150a9)

success 为 false

**Comment by Tsuk1ko** [comment]
那大概是是相似度之类的原因没缓存吧……

你找个成功搜图的试下有没有缓存

**Comment by Miuzarte** [comment]
> 那大概是是相似度之类的原因没缓存吧……
> 
> 你找个成功搜图的试下有没有缓存

没明白怎么判断的，SauceNAO成功了确实缓存了，但是我看缓存里也有用了a2d的也缓存了

![Image](https://github.com/user-attachments/assets/3de4f40b-61d7-47c9-9077-574d68c604f0)

![Image](https://github.com/user-attachments/assets/3aaf8d1f-3f45-42e7-86fa-7e0e26967d95)

**Comment by Miuzarte** [comment]
哦可能是nhentai没搜到也判失败了
