### ISSUE TITLE
B站动态解析无法解析带有图片的动态

### ISSUE THREAD

**Issue by a741222077** [Tsuk1ko/cq-picsearcher-bot#468]
![image](https://github.com/user-attachments/assets/6630becb-3c82-4421-9d15-ce07c36b3feb)
![image](https://github.com/user-attachments/assets/cfcd5ca1-21e2-4a9d-9be7-81ae219d7595)
![image](https://github.com/user-attachments/assets/fc6c9da3-f4ba-45d0-bdb9-cd911385908a)

**Comment by Tsuk1ko** [comment]
已修复
