### ISSUE TITLE
B站动态又有新类型了

### ISSUE THREAD

**Issue by huankong233** [Tsuk1ko/cq-picsearcher-bot#469]
B站动态新类型，发现咱们没有，提一嘴😜

## demo地址: 
[https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&features=itemOpusStyle&id=968344417525039106](https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&features=itemOpusStyle&id=968344417525039106)

## 解析的小demo
~~~ javascript
  // 纯文本动态
  DYNAMIC_TYPE_WORD: async ({
    opus: {
      summary: { rich_text_nodes }
    }
  }) => Structs.text({ text: rich_text_nodes.map((node) => node.text) })

~~~

**Comment by Tsuk1ko** [comment]
这个好像没关系呀，我这识别的 major type `MAJOR_TYPE_OPUS`，这个很早就支持了

**Comment by huankong233** [comment]
> 这个好像没关系呀，我这识别的 major type `MAJOR_TYPE_OPUS`，这个很早就支持了

搞错了🥺，抱歉，干了好几回这猪逼事了
