### ISSUE TITLE
希望搜图结果能够调用go-cqhttp的回复CQ码

### ISSUE THREAD

**Issue by CiaranZhou** [Tsuk1ko/cq-picsearcher-bot#84]
希望加的功能：
能够回复指定图片的搜图结果

理由：
1. 因为现在也换成了go-cqhttp，它拓展了一些CQ码，其中包括回复消息，即`[CQ:reply]`
2. 当短时间内同时提交了多个搜图请求时，机器人返回的结果可以更好的体现是哪一张图的搜图结果

**Comment by Tsuk1ko** [comment]
该功能已实装

**Comment by benx1n** [comment]
> 该功能已实装

测试了一下在群内未显示为回复格式而是直接以文本形式显示了CQ码，cqhttp版本为0.9.18，错误日志显示未支持的CQ码
![78T%TYCUCY7 V823H{M_G E](https://user-images.githubusercontent.com/48101337/90069471-eb08b900-dd24-11ea-8615-9f7f5675aa2c.png)

**Comment by Tsuk1ko** [comment]
没能复现，我使用的是 v0.9.18，你这个错误是必现还是偶现？

<img src="https://user-images.githubusercontent.com/24877906/90082957-bc4e0b00-dd43-11ea-96bf-ef8ef41e2408.png" width="320">

**Comment by Tsuk1ko** [comment]
@benx1n 没能复现，我使用的是 v0.9.18，你这个错误是必现还是偶现？

<img src="https://user-images.githubusercontent.com/24877906/90082957-bc4e0b00-dd43-11ea-96bf-ef8ef41e2408.png" width="320">

**Comment by benx1n** [comment]
@Tsuk1ko 目前看来是必现 推测可能是内置数据库的问题，已经提交给go-cqhttp那边了
