### ISSUE TITLE
私聊没有反应

### ISSUE THREAD

**Issue by Effie123** [Tsuk1ko/cq-picsearcher-bot#85]
搭建好后测试发现只有管理员QQ私聊发送消息有回复，换另外一个QQ发送消息无回应。

**Comment by Tsuk1ko** [comment]
是否在`config.json`中配置`"debug": true`了，调试模式被设计成只响应`admin`的消息

**Comment by Effie123** [comment]
> 是否在中配置了，调试模式被设计成只响应的消息`config.json``"debug": true``admin`

并没有开启dubug,通过观察发现没有监听私聊消息。群聊是有监听的。

**Comment by Tsuk1ko** [comment]
go-cqhttp 上日志有显示收到消息么

**Comment by Effie123** [comment]
> go-cqhttp 上日志有显示收到消息么

没有收到消息，只有管理员QQ发送时才有。

**Comment by Tsuk1ko** [comment]
群临时会话从 https://github.com/Mrs4s/go-cqhttp/releases/tag/v0.9.16 开始就支持了，看下是否是你用的 go-cqhttp 版本过旧

**Comment by Effie123** [comment]
> 群临时会话从 https://github.com/Mrs4s/go-cqhttp/releases/tag/v0.9.16 开始就支持了，看下是否是你用的 go-cqhttp 版本过旧

发现用的是0.9.15。我去更新下看看。目前是不管临时会话还是好友之都收不到消息。

**Comment by Effie123** [comment]
我发现仍然不行，我重新部署了发现仍然接收不到私聊。

**Comment by Tsuk1ko** [comment]
我测试了双向好友和群临时会话是没问题的

单向好友和陌生人的情况没试（如果机器人QQ本身设置的是自动同意所有好友申请，那么加进来的都是单向好友），有可能是这个问题吧，具体需要再确认下

另外因为 go-cqhttp 的私聊仍然存在收到重复消息的问题，暂不建议私聊使用，新版本也加入了设置可以自由开关私聊与群消息的监听

**Comment by Effie123** [comment]
> 我测试了双向好友和群临时会话是没问题的
> 
> 单向好友和陌生人的情况没试（如果机器人QQ本身设置的是自动同意所有好友申请，那么加进来的都是单向好友），有可能是这个问题吧，具体需要再确认下
> 
> 另外因为 go-cqhttp 的私聊仍然存在收到重复消息的问题，暂不建议私聊使用，新版本也加入了设置可以自由开关私聊与群消息的监听

好的，看了下就是单项好友和陌生人的情况导致无法接受消息。非常感谢你的耐心讲解。

**Comment by Tsuk1ko** [comment]
不用谢，待我今晚测试一下之后会向 go-cqhttp 提 issue

**Comment by Tsuk1ko** [comment]
已经提了 issue，后续跟进 Mrs4s/go-cqhttp#98 即可
