### ISSUE TITLE
broadcast功能似乎失效

### ISSUE THREAD

**Issue by assassingyk** [Tsuk1ko/cq-picsearcher-bot#86]
如题，想给几个群发个公告发现--broadcast=这个命令似乎是失效了……

看了下log似乎是因为调用的API是 /send_group_msg_rate_limited，但go-cqhttp目前只支持了/send_group_msg……？如果不限频率直接调用是不是容易被qq封号来着……是应该这边修改下还是去go-cqhttp那边提Issue增加API支持比较好啊）

**Comment by Tsuk1ko** [comment]
我去问问

**Comment by Tsuk1ko** [comment]
我去问问，暂时也可以先由我这里实现限速调用

**Comment by Tsuk1ko** [comment]
go-cqhttp 那边有计划支持 rate limitd 但得慢慢来，我这边先手动限速调用了
