### ISSUE TITLE
antiBiliMiniApp功能似乎有点问题

### ISSUE THREAD

**Issue by LoliconXX** [Tsuk1ko/cq-picsearcher-bot#87]
npm启动或重启后私聊第一次发链接会返回视频信息，后面发就没反应了，群里不管怎么发都没有反应。
不知道是不是go-cqhttp的问题
如图片所示
![image](https://user-images.githubusercontent.com/35798517/90292564-b4fa3f00-deb4-11ea-8028-370c164856f1.png)

**Comment by Tsuk1ko** [comment]
防刷屏的逻辑有点问题，稍后修复

**Comment by Tsuk1ko** [comment]
修复了，更新再试
