### ISSUE TITLE
定时提醒功能出错导致刷屏

### ISSUE THREAD

**Issue by assassingyk** [Tsuk1ko/cq-picsearcher-bot#90]
1. Bug 描述

如题，尝试设置精确到某月某日某时某分的提醒则立即发生刷屏，消息数量可以达到一秒近百条……做了几次测试都稳定复现（没被封号实在万幸）

发生刷屏时可以看到`(node:*****) TimeoutOverflowWarning`的报错，`(node:*****)`里面的数字每次重启都有变化，应该是node那边出的问题？

复现示例命令：--rmd=复现测试 --time=0;12;1;1;*

2. 截图、日志、配置（issue 内上传图片可直接粘贴）
   - 问题相关截图
![image](https://user-images.githubusercontent.com/55473115/90339426-569f9e80-e023-11ea-9b64-19200ffa73ec.png)

   - 问题日志
```
(node:12756) TimeoutOverflowWarning: 7301446289867 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:12756) TimeoutOverflowWarning: 7333068689861 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:12756) TimeoutOverflowWarning: 7364604689858 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

3. 运行环境
   -  win 和 linux 测试都有出现，现象一致
   - node版本win上是v12.13.1.，linux上是v12.16.1
   - go-cqhttp 版本win上是v0.9.15  linux上是v0.9.17

**Comment by Tsuk1ko** [comment]
已修复

**Comment by Tsuk1ko** [comment]
如果刚才你已经更过的话麻烦再更一下，漏写了一行（

**Comment by assassingyk** [comment]
好的好的，多谢大佬光速修复了
~~强者都是不睡觉的吗.jpg~~

**Comment by Tsuk1ko** [comment]
刚好在写别的东西（
