### ISSUE TITLE
识图时已缓存的图片发送失败

### ISSUE THREAD

**Issue by CiaranZhou** [Tsuk1ko/cq-picsearcher-bot#91]
1. Bug 描述
   - 在使用识图功能时，机器人发送缓存过的图片失败
   - 文字部分无问题，并没有接收到机器人发过来的图片
2. 截图、日志、配置（issue 内上传图片可直接粘贴）
   - go-cqhttp日志
`[2020-08-18 08:48:08] [WARNING]: 警告: 私聊 xxxxxxxxx 消息图片上传失败. `
↑QQ号已隐蔽处理
   - bot日志
在时间前后五分钟内，error日志内无相关报错
   - bot回复的内容
![image](https://user-images.githubusercontent.com/33545847/90462854-27c91b80-e13c-11ea-88da-c6ee6ceeb255.png)
   - 相关信息
上一次也是首次识别这张图的时间为`2020.8.17 9:47:47`，本次时间为`2020.8.18 8:48:08`
**经测试，刚识别过的图片再次让bot识别，回复的内容依然如上文**
其实这个问题在迁移go-cqhhtp之后就存在了，只是平时二次识别场景较少，所以说现在才反馈
~~缓存时间设置的30天，应该和这个无关~~
3. 运行环境
   - 系统：Ubuntu16.04
   - Node 版本：v10.22.0
   - go-cqhttp 版本：v0.9.19

**Comment by Tsuk1ko** [comment]
go-cqhttp 从 v0.20.0 开始支持发图缓存了，按理来说这个问题应该解决了

**Comment by CiaranZhou** [comment]
经过这几天的测试，已经没有对应问题
