### ISSUE TITLE
希望增加命令机器人撤回某条消息的功能，有时候搜图结果出来很奇怪的缩略图(引起不适或r18)

### ISSUE THREAD

**Issue by Utopia-015** [Tsuk1ko/cq-picsearcher-bot#92]
或者其他解决这种情况的办法，酷Q的时代里不用担心，毕竟发不了图片，现在有可能发出来的缩略图让群都没了(逃
开启低相似度隐藏缩略图仅能隐藏saucenao的结果，并不能隐藏后续的a2d结果

**Comment by shitianshiwa** [comment]
其实搜动画也要防备下。

**Comment by Tsuk1ko** [comment]
那我加上不发缩略图的选项吧，低相似度的话搜的 a2d 的图也隐藏了，动画就隐藏 r18 的结果的封面

如果要出撤回命令不如直接让管理员撤了（

**Comment by Tsuk1ko** [comment]
实装了，详情请看更新日志和 wiki 中的配置项说明
