### ISSUE TITLE
请问setu功能如何指定数量发图？

### ISSUE THREAD

**Issue by 0769559** [Tsuk1ko/cq-picsearcher-bot#95]
请参考默认正则表达式^竹竹.*[来來发發给給][张張个個幅点點]?(?<r18>[Rr]18的?)?(?<keyword>.*?)?的?[色瑟][图圖]|^--setu$，在这之中，(?<r18>r18的?)和(?<keyword>.*)即为两个捕获组，尖括号对中的内容为捕获组的名字，程序会取r18和keyword两个捕获组作为 R18 和关键字参数

我不是很明白正则表达式，不过已经会根据参考的基础上自己修改触发条件了，但却不是很明白该怎么用正则表达式指定色图数量。请求指导(﹁ ﹁)
"setu": "^警犬.*?(?<r18>[Rr]18的?)?(?<keyword>.*?)[色瑟][来图圖]|^--setu$"

**Comment by Tsuk1ko** [comment]
目前固定一张无法指定数量，将来也不会有指定数量的功能
