### ISSUE TITLE
r18撤回功能无法正常运行

### ISSUE THREAD

**Issue by xiaobaozi233** [Tsuk1ko/cq-picsearcher-bot#97]
go-cqhttp上提示获取信息时出现错误

- go-cqhttp-v0.9.23
- cq-picsearcher-bot 2.16.0

**Comment by Tsuk1ko** [comment]
我这里正常，没能复现

可能相关：

> 已知问题: 386架构在开启数据库的情况下依然无法使用数据库相关功能, 建议使用amd64.

如果你在使用 386 的 release，请换用 amd64 再试
