### ISSUE TITLE
希望可以关闭默认回复

### ISSUE THREAD

**Issue by samondlee** [Tsuk1ko/cq-picsearcher-bot#98]
请说明：

1. 提供关闭默认回复功能
 "replys": {
      // 默认回复
      "default": "必须要发送图片我才能帮你找噢_(:3」」\n支持批量！",
2. 理由
群里人艾特的太多 而且又其他机器人，每次艾特 都会有默认回复出现影响美观

**Comment by Tsuk1ko** [comment]
直接在配置中改为空字符串即可

```json
"default": "",
```

**Comment by samondlee** [comment]
啊这 感谢
