### ISSUE TITLE
关于在arm平台下armbian下提示缺少模块问题

### ISSUE THREAD

**Issue by samondlee** [Tsuk1ko/cq-picsearcher-bot#99]
picsearcher版本最新

go-cqhttp arm版本最新

node v14.5

运行CNPM INSTALL后 好像仍然缺少模块

不知怎么办才好了emmmm

日志如下：

`0 info it worked if it ends with ok

1 verbose cli [

1 verbose cli   '/root/node-v14.5.0-linux-arm64/bin/node',

1 verbose cli   '/root/node-v14.5.0-linux-arm64/bin/npm',

1 verbose cli   'run',

1 verbose cli   'test'

1 verbose cli ]

2 info using npm@6.14.5

3 info using node@v14.5.0

4 verbose run-script [ 'pretest', 'test', 'posttest' ]

5 info lifecycle cq-picsearcher-bot@2.17.0~pretest: cq-picsearcher-bot@2.17.0

6 info lifecycle cq-picsearcher-bot@2.17.0~test: cq-picsearcher-bot@2.17.0

7 verbose lifecycle cq-picsearcher-bot@2.17.0~test: unsafe-perm in lifecycle true

8 verbose lifecycle cq-picsearcher-bot@2.17.0~test: PATH: /root/node-v14.5.0-linux-arm64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/mirai/picsearcher/node_modules/.bin:/root/node-v14.5.0-linux-arm64/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin

9 verbose lifecycle cq-picsearcher-bot@2.17.0~test: CWD: /home/mirai/picsearcher

10 silly lifecycle cq-picsearcher-bot@2.17.0~test: Args: [ '-c', 'node index.js' ]

11 silly lifecycle cq-picsearcher-bot@2.17.0~test: Returned: code: 1  signal: null

12 info lifecycle cq-picsearcher-bot@2.17.0~test: Failed to exec test script

13 verbose stack Error: cq-picsearcher-bot@2.17.0 test: `node index.js`

13 verbose stack Exit status 1

13 verbose stack     at EventEmitter.<anonymous> (/root/node-v14.5.0-linux-arm64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)

13 verbose stack     at EventEmitter.emit (events.js:314:20)

13 verbose stack     at ChildProcess.<anonymous> (/root/node-v14.5.0-linux-arm64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)

13 verbose stack     at ChildProcess.emit (events.js:314:20)

13 verbose stack     at maybeClose (internal/child_process.js:1051:16)

13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

14 verbose pkgid cq-picsearcher-bot@2.17.0

15 verbose cwd /home/mirai/picsearcher

16 verbose Linux 4.18.7-aml-s9xxx

17 verbose argv "/root/node-v14.5.0-linux-arm64/bin/node" "/root/node-v14.5.0-linux-arm64/bin/npm" "run" "test"

18 verbose node v14.5.0

19 verbose npm  v6.14.5

20 error code ELIFECYCLE

21 error errno 1

22 error cq-picsearcher-bot@2.17.0 test: `node index.js`

22 error Exit status 1

23 error Failed at the cq-picsearcher-bot@2.17.0 test script.

23 error This is probably not a problem with npm. There is likely additional logging output above.

24 verbose exit [ 1, true ]
`

**Comment by samondlee** [comment]
补充在运行时的错误
`root@aml:/home/mirai/picsearcher# npm run test

> cq-picsearcher-bot@2.17.0 test /home/mirai/picsearcher
> node index.js

/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/lib/bindings.js:1
Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/lib/bindings.js
- /home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/lib/canvas.js
- /home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/index.js
- /home/mirai/picsearcher/src/plugin/akhr.draw.js
- /home/mirai/picsearcher/src/plugin/akhr.js
- /home/mirai/picsearcher/src/config.js
- /home/mirai/picsearcher/main.js
- /home/mirai/picsearcher/index.js
    at Object.<anonymous> (/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/lib/bindings.js:3:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/lib/bindings.js',
    '/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/lib/canvas.js',
    '/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/index.js',
    '/home/mirai/picsearcher/src/plugin/akhr.draw.js',
    '/home/mirai/picsearcher/src/plugin/akhr.js',
    '/home/mirai/picsearcher/src/config.js',
    '/home/mirai/picsearcher/main.js',
    '/home/mirai/picsearcher/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cq-picsearcher-bot@2.17.0 test: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cq-picsearcher-bot@2.17.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-08T05_55_27_102Z-debug.log
root@aml:/home/mirai/picsearcher# `

**Comment by Tsuk1ko** [comment]
canvas 这个依赖需要编译二进制 node 文件，删除`node_modules`文件夹后重新`npm i`，关注有没有错误，按 wiki 部署流程处理

**Comment by samondlee** [comment]
> canvas 这个依赖需要编译二进制 node 文件，删除`node_modules`文件夹后重新`npm i`，关注有没有错误，按 wiki 部署流程处理

啊这，是不是要把node删了 然后从新从官网下source安装

**Comment by Tsuk1ko** [comment]
> > canvas 这个依赖需要编译二进制 node 文件，删除`node_modules`文件夹后重新`npm i`，关注有没有错误，按 wiki 部署流程处理
> 
> 啊这，是不是要把node删了 然后从新从官网下source安装

不是，第一句话的意思是 canvas 这个包需要用到它自己编译的一个二进制模块 (binary modules)，其扩展名通常为`.node`

如果该包已经含有你系统的预编译二进制文件则会直接下载使用，否则会进行编译，如果这个过程中出现错误就会有找不到模块问题，按 wiki 中所说的处理

**Comment by samondlee** [comment]
> > > canvas 这个依赖需要编译二进制 node 文件，删除`node_modules`文件夹后重新`npm i`，关注有没有错误，按 wiki 部署流程处理
> > 
> > 
> > 啊这，是不是要把node删了 然后从新从官网下source安装
> 
> 不是，第一句话的意思是 canvas 这个包需要用到它自己编译的一个二进制模块 (binary modules)，其扩展名通常为`.node`
> 
> 如果该包已经含有你系统的预编译二进制文件则会直接下载使用，否则会进行编译，如果这个过程中出现错误就会有找不到模块问题，按 wiki 中所说的处理

啊这 用了 https://github.com/node-gfx/node-canvas-prebuilt 的包尝试修复本地编译完了 还是不行 然后试了一下npm install --save canvas emmm报错 emmmm 啊这= =放弃了 躺平。。。。

`node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://cdn.npm.taobao.org/dist/node-canvas-prebuilt/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-arm64.tar.gz
node-pre-gyp http 404 https://cdn.npm.taobao.org/dist/node-canvas-prebuilt/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-arm64.tar.gz
node-pre-gyp WARN Tried to download(404): https://cdn.npm.taobao.org/dist/node-canvas-prebuilt/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.5.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://cdn.npm.taobao.org/dist/node-canvas-prebuilt/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-arm64.tar.gz 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/mirai/picsearcher/node_modules/_node-gyp@3.8.0@node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.18.7-aml-s9xxx
gyp ERR! command "/root/node-v14.5.0-linux-arm64/bin/node" "/home/mirai/picsearcher/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/node-v14.5.0-linux-arm64/bin/node /home/mirai/picsearcher/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/mirai/picsearcher/node_modules/_node-pre-gyp@0.11.0@node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.18.7-aml-s9xxx
node-pre-gyp ERR! command "/root/node-v14.5.0-linux-arm64/bin/node" "/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas
node-pre-gyp ERR! node -v v14.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/root/node-v14.5.0-linux-arm64/bin/node /home/mirai/picsearcher/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/mirai/picsearcher/node_modules/_canvas@2.6.1@canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
[npminstall:runscript:error] canvas@>=2.6.1 scripts.install run "node-pre-gyp install --fallback-to-build" error: Error [RunScriptError]: Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
    at ChildProcess.<anonymous> (/root/node-v14.5.0-linux-arm64/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  stdio: [Object],
  exitcode: 1
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
RunScriptError: Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
    at ChildProcess.<anonymous> (/root/node-v14.5.0-linux-arm64/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npminstall version: 3.27.0
npminstall args: /root/node-v14.5.0-linux-arm64/bin/node /root/node-v14.5.0-linux-arm64/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org --save canvas
root@aml:/home/mirai/picsearcher# `

**Comment by Tsuk1ko** [comment]
可能是缺少编译工具，可以自行 google arm 平台上有没有解决方案
